/* Generated by Yosys 0.14 (git sha1 UNKNOWN, clang 13.0.0 -fPIC -Os) */

module ula(clk14, a, d, mreq_n, ioreq_n, clkcpu, msk_int_n, va, vramoe_n, vramcs_n, vramwe_n, vram_in_use, BorderColor, r, g, b, i, csync);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire AOLatch_n;
  wire AttrLatch_n;
  wire \AttrOut[0] ;
  wire \AttrOut[1] ;
  wire \AttrOut[2] ;
  wire \AttrOut[3] ;
  wire \AttrOut[4] ;
  wire \AttrOut[5] ;
  wire \AttrOut[6] ;
  wire \AttrOut[7] ;
  wire \AttrReg[0] ;
  wire \AttrReg[1] ;
  wire \AttrReg[2] ;
  wire \AttrReg[3] ;
  wire \AttrReg[4] ;
  wire \AttrReg[5] ;
  wire \AttrReg[6] ;
  wire \AttrReg[7] ;
  wire \BitmapReg[0] ;
  wire \BitmapReg[1] ;
  wire \BitmapReg[2] ;
  wire \BitmapReg[3] ;
  wire \BitmapReg[4] ;
  wire \BitmapReg[5] ;
  wire \BitmapReg[6] ;
  wire \BitmapReg[7] ;
  input [2:0] BorderColor;
  wire [2:0] BorderColor;
  wire Border_n;
  wire DataLatch_n;
  wire \FlashCnt[0] ;
  wire \FlashCnt[1] ;
  wire \FlashCnt[2] ;
  wire \FlashCnt[3] ;
  wire \FlashCnt[4] ;
  wire HBlank_n;
  wire HSync_n;
  wire SLoad;
  wire \SRegister[0] ;
  wire \SRegister[1] ;
  wire \SRegister[2] ;
  wire \SRegister[3] ;
  wire \SRegister[4] ;
  wire \SRegister[5] ;
  wire \SRegister[6] ;
  wire \SRegister[7] ;
  wire VBlank_n;
  wire VSync_n;
  wire VidEN_n;
  input [15:0] a;
  wire [15:0] a;
  output b;
  wire b;
  input clk14;
  wire clk14;
  wire clk7;
  output clkcpu;
  wire clkcpu;
  output csync;
  wire csync;
  input [7:0] d;
  wire [7:0] d;
  output g;
  wire g;
  wire \hc[0] ;
  wire \hc[1] ;
  wire \hc[2] ;
  wire \hc[3] ;
  wire \hc[4] ;
  wire \hc[5] ;
  wire \hc[6] ;
  wire \hc[7] ;
  wire \hc[8] ;
  output i;
  wire i;
  input ioreq_n;
  wire ioreq_n;
  wire ioreqtw3;
  input mreq_n;
  wire mreq_n;
  wire mreqt23;
  output msk_int_n;
  wire msk_int_n;
  output r;
  wire r;
  wire \v[0] ;
  wire \v[1] ;
  wire \v[2] ;
  wire \v[6] ;
  wire \v[7] ;
  output [13:0] va;
  wire [13:0] va;
  wire \vc[0] ;
  wire \vc[1] ;
  wire \vc[2] ;
  wire \vc[3] ;
  wire \vc[4] ;
  wire \vc[5] ;
  wire \vc[6] ;
  wire \vc[7] ;
  wire \vc[8] ;
  output vram_in_use;
  wire vram_in_use;
  output vramcs_n;
  wire vramcs_n;
  output vramoe_n;
  wire vramoe_n;
  output vramwe_n;
  wire vramwe_n;
  sky130_fd_sc_hd__clkinv_1 _197_ (
    .A(VSync_n),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _198_ (
    .A(\hc[0] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _199_ (
    .A(clk7),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _200_ (
    .A(\AttrReg[0] ),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _201_ (
    .A(\AttrReg[1] ),
    .Y(_127_)
  );
  sky130_fd_sc_hd__clkinv_1 _202_ (
    .A(\AttrReg[2] ),
    .Y(_128_)
  );
  sky130_fd_sc_hd__clkinv_1 _203_ (
    .A(\AttrReg[3] ),
    .Y(_129_)
  );
  sky130_fd_sc_hd__clkinv_1 _204_ (
    .A(\AttrReg[4] ),
    .Y(_130_)
  );
  sky130_fd_sc_hd__clkinv_1 _205_ (
    .A(\AttrReg[5] ),
    .Y(_131_)
  );
  sky130_fd_sc_hd__clkinv_1 _206_ (
    .A(\FlashCnt[0] ),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _207_ (
    .A(AOLatch_n),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _208_ (
    .A(AttrLatch_n),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _209_ (
    .A(DataLatch_n),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(\hc[3] ),
    .B(Border_n),
    .Y(_132_)
  );
  sky130_fd_sc_hd__clkinv_1 _211_ (
    .A(_132_),
    .Y(vram_in_use)
  );
  sky130_fd_sc_hd__nand4_1 _212_ (
    .A(\hc[3] ),
    .B(\hc[0] ),
    .C(\hc[1] ),
    .D(Border_n),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _213_ (
    .A(\hc[2] ),
    .B(_001_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand3_1 _214_ (
    .A(\hc[0] ),
    .B(\hc[1] ),
    .C(\hc[2] ),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(\hc[3] ),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21oi_1 _216_ (
    .A1(Border_n),
    .A2(_135_),
    .B1(_133_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__mux2_1 _217_ (
    .A0(\hc[4] ),
    .A1(va[1]),
    .S(_136_),
    .X(_125_)
  );
  sky130_fd_sc_hd__a21o_1 _218_ (
    .A1(va[0]),
    .A2(_136_),
    .B1(_133_),
    .X(_124_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _219_ (
    .A(\hc[0] ),
    .SLEEP(\hc[1] ),
    .X(_137_)
  );
  sky130_fd_sc_hd__nor4_1 _220_ (
    .A(\hc[4] ),
    .B(\hc[3] ),
    .C(\hc[2] ),
    .D(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(\hc[7] ),
    .B(\hc[8] ),
    .Y(_139_)
  );
  sky130_fd_sc_hd__and4b_1 _222_ (
    .A_N(\hc[6] ),
    .B(\hc[5] ),
    .C(\hc[8] ),
    .D(\hc[7] ),
    .X(_140_)
  );
  sky130_fd_sc_hd__a21oi_1 _223_ (
    .A1(_138_),
    .A2(_140_),
    .B1(HBlank_n),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand3b_1 _224_ (
    .A_N(\hc[7] ),
    .B(\hc[6] ),
    .C(\hc[8] ),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _225_ (
    .A(\hc[5] ),
    .B(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21oi_1 _226_ (
    .A1(_138_),
    .A2(_143_),
    .B1(_141_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(\hc[4] ),
    .B(\hc[3] ),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor4_1 _228_ (
    .A(\hc[2] ),
    .B(_137_),
    .C(_142_),
    .D(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__mux2_1 _229_ (
    .A0(HSync_n),
    .A1(\hc[5] ),
    .S(_145_),
    .X(_113_)
  );
  sky130_fd_sc_hd__nor3_1 _230_ (
    .A(\vc[5] ),
    .B(\vc[4] ),
    .C(\vc[2] ),
    .Y(_146_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _231_ (
    .A(\vc[8] ),
    .SLEEP(\vc[3] ),
    .X(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(\vc[7] ),
    .B(\vc[6] ),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _233_ (
    .A(\vc[1] ),
    .B(\vc[0] ),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a41oi_1 _234_ (
    .A1(_146_),
    .A2(_147_),
    .A3(_148_),
    .A4(_149_),
    .B1(VBlank_n),
    .Y(_150_)
  );
  sky130_fd_sc_hd__and2_0 _235_ (
    .A(\vc[5] ),
    .B(\vc[4] ),
    .X(_151_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _236_ (
    .A(\vc[3] ),
    .SLEEP(\vc[8] ),
    .X(_152_)
  );
  sky130_fd_sc_hd__and2_0 _237_ (
    .A(\vc[7] ),
    .B(\vc[6] ),
    .X(_153_)
  );
  sky130_fd_sc_hd__nand4_1 _238_ (
    .A(_149_),
    .B(_151_),
    .C(_152_),
    .D(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(\vc[2] ),
    .B(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _240_ (
    .A(_150_),
    .B(_155_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_1 _241_ (
    .A1(_052_),
    .A2(_154_),
    .B1(_155_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor3_1 _242_ (
    .A(\hc[7] ),
    .B(\hc[6] ),
    .C(\hc[8] ),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand3_1 _243_ (
    .A(_138_),
    .B(_155_),
    .C(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__mux2_1 _244_ (
    .A0(\hc[5] ),
    .A1(msk_int_n),
    .S(_157_),
    .X(_110_)
  );
  sky130_fd_sc_hd__and2_0 _245_ (
    .A(\BitmapReg[0] ),
    .B(SLoad),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_1 _246_ (
    .A0(\vc[7] ),
    .A1(\v[7] ),
    .S(_136_),
    .X(_099_)
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(\vc[6] ),
    .A1(\v[6] ),
    .S(_136_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _248_ (
    .A0(\vc[5] ),
    .A1(va[7]),
    .S(_136_),
    .X(_097_)
  );
  sky130_fd_sc_hd__mux2_1 _249_ (
    .A0(\vc[4] ),
    .A1(va[6]),
    .S(_136_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_1 _250_ (
    .A0(\vc[3] ),
    .A1(va[5]),
    .S(_136_),
    .X(_095_)
  );
  sky130_fd_sc_hd__mux2_1 _251_ (
    .A0(\vc[2] ),
    .A1(\v[2] ),
    .S(_136_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_1 _252_ (
    .A0(\vc[1] ),
    .A1(\v[1] ),
    .S(_136_),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(\vc[0] ),
    .A1(\v[0] ),
    .S(_136_),
    .X(_092_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _254_ (
    .A(\AttrReg[7] ),
    .SLEEP(VidEN_n),
    .X(_091_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _255_ (
    .A(\AttrReg[6] ),
    .SLEEP(VidEN_n),
    .X(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _256_ (
    .A(\hc[3] ),
    .B(VidEN_n),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor2_1 _257_ (
    .A(vram_in_use),
    .B(_158_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _258_ (
    .A0(\hc[7] ),
    .A1(va[4]),
    .S(_136_),
    .X(_088_)
  );
  sky130_fd_sc_hd__mux2_1 _259_ (
    .A0(\hc[6] ),
    .A1(va[3]),
    .S(_136_),
    .X(_087_)
  );
  sky130_fd_sc_hd__mux2_1 _260_ (
    .A0(\hc[5] ),
    .A1(va[2]),
    .S(_136_),
    .X(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _261_ (
    .A(\hc[1] ),
    .B(_132_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__mux2_1 _262_ (
    .A0(\v[6] ),
    .A1(\v[0] ),
    .S(_159_),
    .X(va[8])
  );
  sky130_fd_sc_hd__mux2_1 _263_ (
    .A0(\v[7] ),
    .A1(\v[1] ),
    .S(_159_),
    .X(va[9])
  );
  sky130_fd_sc_hd__and2_0 _264_ (
    .A(\v[2] ),
    .B(_159_),
    .X(va[10])
  );
  sky130_fd_sc_hd__or3_1 _265_ (
    .A(\v[6] ),
    .B(\hc[1] ),
    .C(_132_),
    .X(va[11])
  );
  sky130_fd_sc_hd__or3_1 _266_ (
    .A(\v[7] ),
    .B(\hc[1] ),
    .C(_132_),
    .X(va[12])
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(HBlank_n),
    .B(VBlank_n),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(\AttrOut[7] ),
    .B(\FlashCnt[4] ),
    .Y(_161_)
  );
  sky130_fd_sc_hd__xor2_1 _269_ (
    .A(\SRegister[7] ),
    .B(_161_),
    .X(_162_)
  );
  sky130_fd_sc_hd__mux2i_1 _270_ (
    .A0(\AttrOut[0] ),
    .A1(\AttrOut[3] ),
    .S(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _271_ (
    .A(_160_),
    .B(_163_),
    .Y(b)
  );
  sky130_fd_sc_hd__mux2i_1 _272_ (
    .A0(\AttrOut[1] ),
    .A1(\AttrOut[4] ),
    .S(_162_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2_1 _273_ (
    .A(_160_),
    .B(_164_),
    .Y(r)
  );
  sky130_fd_sc_hd__mux2i_1 _274_ (
    .A0(\AttrOut[2] ),
    .A1(\AttrOut[5] ),
    .S(_162_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _275_ (
    .A(_160_),
    .B(_165_),
    .Y(g)
  );
  sky130_fd_sc_hd__and3_1 _276_ (
    .A(HBlank_n),
    .B(VBlank_n),
    .C(\AttrOut[6] ),
    .X(i)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(VidEN_n),
    .B(BorderColor[0]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o21ai_0 _278_ (
    .A1(VidEN_n),
    .A2(_126_),
    .B1(_166_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(VidEN_n),
    .B(BorderColor[1]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o21ai_0 _280_ (
    .A1(VidEN_n),
    .A2(_127_),
    .B1(_167_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(VidEN_n),
    .B(BorderColor[2]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__o21ai_0 _282_ (
    .A1(VidEN_n),
    .A2(_128_),
    .B1(_168_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__o21ai_0 _283_ (
    .A1(VidEN_n),
    .A2(_129_),
    .B1(_166_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__o21ai_0 _284_ (
    .A1(VidEN_n),
    .A2(_130_),
    .B1(_167_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21ai_0 _285_ (
    .A1(VidEN_n),
    .A2(_131_),
    .B1(_168_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _286_ (
    .A0(\SRegister[0] ),
    .A1(\BitmapReg[1] ),
    .S(SLoad),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _287_ (
    .A0(\SRegister[1] ),
    .A1(\BitmapReg[2] ),
    .S(SLoad),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _288_ (
    .A0(\SRegister[2] ),
    .A1(\BitmapReg[3] ),
    .S(SLoad),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _289_ (
    .A0(\SRegister[3] ),
    .A1(\BitmapReg[4] ),
    .S(SLoad),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _290_ (
    .A0(\SRegister[4] ),
    .A1(\BitmapReg[5] ),
    .S(SLoad),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _291_ (
    .A0(\SRegister[5] ),
    .A1(\BitmapReg[6] ),
    .S(SLoad),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _292_ (
    .A0(\SRegister[6] ),
    .A1(\BitmapReg[7] ),
    .S(SLoad),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(a[14]),
    .B(mreqt23),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _294_ (
    .A1(a[15]),
    .A2(_169_),
    .B1(ioreq_n),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o2111ai_1 _295_ (
    .A1(\hc[3] ),
    .A2(\hc[2] ),
    .B1(Border_n),
    .C1(ioreqtw3),
    .D1(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _296_ (
    .A(clkcpu),
    .B(_171_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand3b_1 _297_ (
    .A_N(\hc[1] ),
    .B(\hc[2] ),
    .C(\hc[0] ),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(\hc[0] ),
    .B(_159_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor3_1 _299_ (
    .A(\hc[8] ),
    .B(\vc[8] ),
    .C(_153_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(\FlashCnt[0] ),
    .B(\FlashCnt[1] ),
    .Y(_172_)
  );
  sky130_fd_sc_hd__xor2_1 _301_ (
    .A(\FlashCnt[0] ),
    .B(\FlashCnt[1] ),
    .X(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _302_ (
    .A(\FlashCnt[2] ),
    .B(_172_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand4_1 _303_ (
    .A(\FlashCnt[0] ),
    .B(\FlashCnt[1] ),
    .C(\FlashCnt[2] ),
    .D(\FlashCnt[3] ),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a31oi_1 _304_ (
    .A1(\FlashCnt[0] ),
    .A2(\FlashCnt[1] ),
    .A3(\FlashCnt[2] ),
    .B1(\FlashCnt[3] ),
    .Y(_174_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _305_ (
    .A(_173_),
    .SLEEP(_174_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _306_ (
    .A(\FlashCnt[4] ),
    .B(_173_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor3b_1 _307_ (
    .A(_137_),
    .B(VidEN_n),
    .C_N(\hc[2] ),
    .Y(_011_)
  );
  sky130_fd_sc_hd__and2_0 _308_ (
    .A(HSync_n),
    .B(VSync_n),
    .X(csync)
  );
  sky130_fd_sc_hd__xor2_1 _309_ (
    .A(\hc[0] ),
    .B(\hc[1] ),
    .X(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _310_ (
    .A1(\hc[0] ),
    .A2(\hc[1] ),
    .B1(\hc[2] ),
    .Y(_175_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _311_ (
    .A(_134_),
    .SLEEP(_175_),
    .X(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _312_ (
    .A(\hc[3] ),
    .B(_134_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__and4_1 _313_ (
    .A(\hc[3] ),
    .B(\hc[0] ),
    .C(\hc[1] ),
    .D(\hc[2] ),
    .X(_176_)
  );
  sky130_fd_sc_hd__xor2_1 _314_ (
    .A(\hc[4] ),
    .B(_176_),
    .X(_105_)
  );
  sky130_fd_sc_hd__and3_1 _315_ (
    .A(\hc[4] ),
    .B(\hc[5] ),
    .C(_176_),
    .X(_177_)
  );
  sky130_fd_sc_hd__nand3_1 _316_ (
    .A(\hc[4] ),
    .B(\hc[5] ),
    .C(_176_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a21oi_1 _317_ (
    .A1(\hc[4] ),
    .A2(_176_),
    .B1(\hc[5] ),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2_1 _318_ (
    .A(_177_),
    .B(_179_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21oi_1 _319_ (
    .A1(_139_),
    .A2(_177_),
    .B1(\hc[6] ),
    .Y(_180_)
  );
  sky130_fd_sc_hd__a21oi_1 _320_ (
    .A1(\hc[6] ),
    .A2(_177_),
    .B1(_180_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__and3_1 _321_ (
    .A(\hc[7] ),
    .B(\hc[6] ),
    .C(_177_),
    .X(_181_)
  );
  sky130_fd_sc_hd__nor3_1 _322_ (
    .A(\hc[6] ),
    .B(_139_),
    .C(_178_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a21oi_1 _323_ (
    .A1(\hc[6] ),
    .A2(_177_),
    .B1(\hc[7] ),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nor3_1 _324_ (
    .A(_181_),
    .B(_182_),
    .C(_183_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o22a_1 _325_ (
    .A1(_139_),
    .A2(_178_),
    .B1(_181_),
    .B2(\hc[8] ),
    .X(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _326_ (
    .A(\vc[0] ),
    .B(_182_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__and4_1 _327_ (
    .A(\hc[4] ),
    .B(\vc[0] ),
    .C(_140_),
    .D(_176_),
    .X(_185_)
  );
  sky130_fd_sc_hd__nor2_1 _328_ (
    .A(_184_),
    .B(_185_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(\vc[1] ),
    .B(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xor2_1 _330_ (
    .A(\vc[1] ),
    .B(_185_),
    .X(_116_)
  );
  sky130_fd_sc_hd__nand3_1 _331_ (
    .A(\vc[2] ),
    .B(\vc[1] ),
    .C(_185_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__xnor2_1 _332_ (
    .A(\vc[2] ),
    .B(_186_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__and4_1 _333_ (
    .A(\vc[3] ),
    .B(\vc[2] ),
    .C(\vc[1] ),
    .D(_185_),
    .X(_188_)
  );
  sky130_fd_sc_hd__nand3_1 _334_ (
    .A(_147_),
    .B(_148_),
    .C(_151_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a41oi_1 _335_ (
    .A1(\vc[2] ),
    .A2(\vc[1] ),
    .A3(_185_),
    .A4(_189_),
    .B1(\vc[3] ),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(_188_),
    .B(_190_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _337_ (
    .A(_187_),
    .B(_189_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__xnor2_1 _338_ (
    .A(\vc[4] ),
    .B(_188_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(_191_),
    .B(_192_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _340_ (
    .A1(\vc[4] ),
    .A2(_188_),
    .B1(\vc[5] ),
    .Y(_193_)
  );
  sky130_fd_sc_hd__and2_0 _341_ (
    .A(_151_),
    .B(_188_),
    .X(_194_)
  );
  sky130_fd_sc_hd__nor3_1 _342_ (
    .A(_191_),
    .B(_193_),
    .C(_194_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand3_1 _343_ (
    .A(\vc[6] ),
    .B(_151_),
    .C(_188_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__xor2_1 _344_ (
    .A(\vc[6] ),
    .B(_194_),
    .X(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _345_ (
    .A(\vc[7] ),
    .B(_195_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a31oi_1 _346_ (
    .A1(_151_),
    .A2(_153_),
    .A3(_188_),
    .B1(\vc[8] ),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a311oi_1 _347_ (
    .A1(\vc[8] ),
    .A2(_153_),
    .A3(_194_),
    .B1(_196_),
    .C1(_191_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__clkinv_1 _348_ (
    .A(clk7),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(clk7),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _350_ (
    .A(clk7),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(clk7),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _352_ (
    .A(clk7),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(clk7),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _354_ (
    .A(clk7),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _355_ (
    .A(clk7),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _356_ (
    .A(clk7),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(clk7),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _358_ (
    .A(AOLatch_n),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _359_ (
    .A(AOLatch_n),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _360_ (
    .A(AOLatch_n),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _361_ (
    .A(AOLatch_n),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _362_ (
    .A(AOLatch_n),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _363_ (
    .A(clk7),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _364_ (
    .A(AOLatch_n),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _365_ (
    .A(AOLatch_n),
    .Y(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _366_ (
    .A(clk7),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _367_ (
    .A(clk7),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _368_ (
    .A(clk7),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _369_ (
    .A(clk7),
    .Y(_047_)
  );
  sky130_fd_sc_hd__clkinv_1 _370_ (
    .A(clk7),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _371_ (
    .A(clk7),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkinv_1 _372_ (
    .A(clk7),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _373_ (
    .A(clk7),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _374_ (
    .A(VSync_n),
    .Y(_053_)
  );
  sky130_fd_sc_hd__clkinv_1 _375_ (
    .A(VSync_n),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _376_ (
    .A(VSync_n),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _377_ (
    .A(VSync_n),
    .Y(_056_)
  );
  sky130_fd_sc_hd__clkinv_1 _378_ (
    .A(clk7),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _379_ (
    .A(AttrLatch_n),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _380_ (
    .A(AttrLatch_n),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _381_ (
    .A(AttrLatch_n),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _382_ (
    .A(AttrLatch_n),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _383_ (
    .A(AttrLatch_n),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _384_ (
    .A(AttrLatch_n),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _385_ (
    .A(AttrLatch_n),
    .Y(_065_)
  );
  sky130_fd_sc_hd__clkinv_1 _386_ (
    .A(DataLatch_n),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(DataLatch_n),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _388_ (
    .A(DataLatch_n),
    .Y(_069_)
  );
  sky130_fd_sc_hd__clkinv_1 _389_ (
    .A(DataLatch_n),
    .Y(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _390_ (
    .A(DataLatch_n),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _391_ (
    .A(DataLatch_n),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _392_ (
    .A(DataLatch_n),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _393_ (
    .A(clk7),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _394_ (
    .A(clk7),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _395_ (
    .A(clk7),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _396_ (
    .A(clk7),
    .Y(_077_)
  );
  sky130_fd_sc_hd__clkinv_1 _397_ (
    .A(clk7),
    .Y(_078_)
  );
  sky130_fd_sc_hd__clkinv_1 _398_ (
    .A(clk7),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _399_ (
    .A(clk7),
    .Y(_080_)
  );
  sky130_fd_sc_hd__clkinv_1 _400_ (
    .A(clk7),
    .Y(_081_)
  );
  sky130_fd_sc_hd__clkinv_1 _401_ (
    .A(clk7),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _402_ (
    .A(clk7),
    .Y(_083_)
  );
  sky130_fd_sc_hd__clkinv_1 _403_ (
    .A(clk7),
    .Y(_084_)
  );
  sky130_fd_sc_hd__clkinv_1 _404_ (
    .A(clk7),
    .Y(_085_)
  );
  sky130_fd_sc_hd__dfxtp_1 _405_ (
    .CLK(_025_),
    .D(_086_),
    .Q(va[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _406_ (
    .CLK(_026_),
    .D(_087_),
    .Q(va[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _407_ (
    .CLK(_027_),
    .D(_088_),
    .Q(va[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _408_ (
    .CLK(clk14),
    .D(_019_),
    .Q(clk7)
  );
  sky130_fd_sc_hd__dfxtp_1 _409_ (
    .CLK(_028_),
    .D(_012_),
    .Q(\SRegister[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _410_ (
    .CLK(_029_),
    .D(_013_),
    .Q(\SRegister[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _411_ (
    .CLK(_030_),
    .D(_014_),
    .Q(\SRegister[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _412_ (
    .CLK(_031_),
    .D(_015_),
    .Q(\SRegister[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _413_ (
    .CLK(_032_),
    .D(_016_),
    .Q(\SRegister[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _414_ (
    .CLK(_033_),
    .D(_017_),
    .Q(\SRegister[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _415_ (
    .CLK(_034_),
    .D(_018_),
    .Q(\SRegister[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _416_ (
    .CLK(_035_),
    .D(_002_),
    .Q(\AttrOut[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _417_ (
    .CLK(_036_),
    .D(_003_),
    .Q(\AttrOut[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _418_ (
    .CLK(_037_),
    .D(_004_),
    .Q(\AttrOut[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _419_ (
    .CLK(_038_),
    .D(_005_),
    .Q(\AttrOut[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _420_ (
    .CLK(_039_),
    .D(_006_),
    .Q(\AttrOut[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _421_ (
    .CLK(_040_),
    .D(_007_),
    .Q(\AttrOut[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _422_ (
    .CLK(_041_),
    .D(_089_),
    .Q(VidEN_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _423_ (
    .CLK(clkcpu),
    .D(ioreq_n),
    .Q(ioreqtw3)
  );
  sky130_fd_sc_hd__dfxtp_1 _424_ (
    .CLK(clkcpu),
    .D(mreq_n),
    .Q(mreqt23)
  );
  sky130_fd_sc_hd__dfxtp_1 _425_ (
    .CLK(clk7),
    .D(_009_),
    .Q(clkcpu)
  );
  sky130_fd_sc_hd__dfxtp_1 _426_ (
    .CLK(_042_),
    .D(_090_),
    .Q(\AttrOut[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _427_ (
    .CLK(_043_),
    .D(_091_),
    .Q(\AttrOut[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _428_ (
    .CLK(_044_),
    .D(_092_),
    .Q(\v[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _429_ (
    .CLK(_045_),
    .D(_093_),
    .Q(\v[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _430_ (
    .CLK(_046_),
    .D(_094_),
    .Q(\v[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _431_ (
    .CLK(_047_),
    .D(_095_),
    .Q(va[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _432_ (
    .CLK(_048_),
    .D(_096_),
    .Q(va[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _433_ (
    .CLK(_049_),
    .D(_097_),
    .Q(va[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _434_ (
    .CLK(_050_),
    .D(_098_),
    .Q(\v[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _435_ (
    .CLK(_051_),
    .D(_099_),
    .Q(\v[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _436_ (
    .CLK(_052_),
    .D(_020_),
    .Q(\FlashCnt[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _437_ (
    .CLK(_053_),
    .D(_021_),
    .Q(\FlashCnt[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _438_ (
    .CLK(_054_),
    .D(_022_),
    .Q(\FlashCnt[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _439_ (
    .CLK(_055_),
    .D(_023_),
    .Q(\FlashCnt[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _440_ (
    .CLK(_056_),
    .D(_024_),
    .Q(\FlashCnt[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _441_ (
    .CLK(_057_),
    .D(_100_),
    .Q(\SRegister[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _442_ (
    .CLK(_058_),
    .D(d[0]),
    .Q(\AttrReg[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _443_ (
    .CLK(_059_),
    .D(d[1]),
    .Q(\AttrReg[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _444_ (
    .CLK(_060_),
    .D(d[2]),
    .Q(\AttrReg[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _445_ (
    .CLK(_061_),
    .D(d[3]),
    .Q(\AttrReg[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _446_ (
    .CLK(_062_),
    .D(d[4]),
    .Q(\AttrReg[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _447_ (
    .CLK(_063_),
    .D(d[5]),
    .Q(\AttrReg[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _448_ (
    .CLK(_064_),
    .D(d[6]),
    .Q(\AttrReg[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _449_ (
    .CLK(_065_),
    .D(d[7]),
    .Q(\AttrReg[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _450_ (
    .CLK(_066_),
    .D(d[0]),
    .Q(\BitmapReg[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _451_ (
    .CLK(_067_),
    .D(d[1]),
    .Q(\BitmapReg[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _452_ (
    .CLK(_068_),
    .D(d[2]),
    .Q(\BitmapReg[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _453_ (
    .CLK(_069_),
    .D(d[3]),
    .Q(\BitmapReg[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _454_ (
    .CLK(_070_),
    .D(d[4]),
    .Q(\BitmapReg[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _455_ (
    .CLK(_071_),
    .D(d[5]),
    .Q(\BitmapReg[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _456_ (
    .CLK(_072_),
    .D(d[6]),
    .Q(\BitmapReg[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _457_ (
    .CLK(_073_),
    .D(d[7]),
    .Q(\BitmapReg[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _458_ (
    .CLK(_074_),
    .D(_000_),
    .Q(AOLatch_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _459_ (
    .CLK(_075_),
    .D(_011_),
    .Q(SLoad)
  );
  sky130_fd_sc_hd__dfxtp_1 _460_ (
    .CLK(_076_),
    .D(_001_),
    .Q(AttrLatch_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _461_ (
    .CLK(_077_),
    .D(_010_),
    .Q(DataLatch_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _462_ (
    .CLK(clk7),
    .D(_101_),
    .Q(\hc[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _463_ (
    .CLK(clk7),
    .D(_102_),
    .Q(\hc[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _464_ (
    .CLK(clk7),
    .D(_103_),
    .Q(\hc[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _465_ (
    .CLK(clk7),
    .D(_104_),
    .Q(\hc[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _466_ (
    .CLK(clk7),
    .D(_105_),
    .Q(\hc[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _467_ (
    .CLK(clk7),
    .D(_106_),
    .Q(\hc[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _468_ (
    .CLK(clk7),
    .D(_107_),
    .Q(\hc[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _469_ (
    .CLK(clk7),
    .D(_108_),
    .Q(\hc[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _470_ (
    .CLK(clk7),
    .D(_109_),
    .Q(\hc[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _471_ (
    .CLK(_078_),
    .D(_008_),
    .Q(Border_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _472_ (
    .CLK(_079_),
    .D(_110_),
    .Q(msk_int_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _473_ (
    .CLK(_080_),
    .D(_111_),
    .Q(VSync_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _474_ (
    .CLK(_081_),
    .D(_112_),
    .Q(VBlank_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _475_ (
    .CLK(_082_),
    .D(_113_),
    .Q(HSync_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _476_ (
    .CLK(_083_),
    .D(_114_),
    .Q(HBlank_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _477_ (
    .CLK(clk7),
    .D(_115_),
    .Q(\vc[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _478_ (
    .CLK(clk7),
    .D(_116_),
    .Q(\vc[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _479_ (
    .CLK(clk7),
    .D(_117_),
    .Q(\vc[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _480_ (
    .CLK(clk7),
    .D(_118_),
    .Q(\vc[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _481_ (
    .CLK(clk7),
    .D(_119_),
    .Q(\vc[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _482_ (
    .CLK(clk7),
    .D(_120_),
    .Q(\vc[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _483_ (
    .CLK(clk7),
    .D(_121_),
    .Q(\vc[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _484_ (
    .CLK(clk7),
    .D(_122_),
    .Q(\vc[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _485_ (
    .CLK(clk7),
    .D(_123_),
    .Q(\vc[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _486_ (
    .CLK(_084_),
    .D(_124_),
    .Q(va[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _487_ (
    .CLK(_085_),
    .D(_125_),
    .Q(va[1])
  );
  sky130_fd_sc_hd__conb_1 _488_ (
    .HI(vramwe_n)
  );
  sky130_fd_sc_hd__conb_1 _489_ (
    .LO(va[13])
  );
  sky130_fd_sc_hd__conb_1 _490_ (
    .LO(vramcs_n)
  );
  sky130_fd_sc_hd__conb_1 _491_ (
    .LO(vramoe_n)
  );
endmodule
