/* Generated by Yosys 0.16 (git sha1 UNKNOWN, clang 13.1.6 -fPIC -Os) */

module AHB_MASTER(HCLK, HRESETn, HADDR, HTRANS, HSIZE, HWRITE, HWDATA, HREADY, HRDATA, wr, rd, done, busy, addr, wdata, rdata);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  output [31:0] HADDR;
  wire [31:0] HADDR;
  input HCLK;
  wire HCLK;
  input [31:0] HRDATA;
  wire [31:0] HRDATA;
  input HREADY;
  wire HREADY;
  input HRESETn;
  wire HRESETn;
  output [2:0] HSIZE;
  wire [2:0] HSIZE;
  output [1:0] HTRANS;
  wire [1:0] HTRANS;
  output [31:0] HWDATA;
  wire [31:0] HWDATA;
  output HWRITE;
  wire HWRITE;
  input [31:0] addr;
  wire [31:0] addr;
  output busy;
  wire busy;
  output done;
  wire done;
  wire [2:0] nstate;
  input rd;
  wire rd;
  output [31:0] rdata;
  wire [31:0] rdata;
  wire [2:0] state;
  input [31:0] wdata;
  wire [31:0] wdata;
  input wr;
  wire wr;
  sky130_fd_sc_hd__clkinv_1 _014_ (
    .A(state[2]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _015_ (
    .A(state[0]),
    .SLEEP(state[1]),
    .X(_001_)
  );
  sky130_fd_sc_hd__nand3b_1 _016_ (
    .A_N(state[1]),
    .B(state[0]),
    .C(state[2]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _017_ (
    .A(_002_),
    .Y(HWRITE)
  );
  sky130_fd_sc_hd__nand2_1 _018_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21a_1 _019_ (
    .A1(state[2]),
    .A2(_003_),
    .B1(_002_),
    .X(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _020_ (
    .A(_004_),
    .Y(HTRANS[1])
  );
  sky130_fd_sc_hd__nor2_1 _021_ (
    .A(state[2]),
    .B(state[0]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__or3_1 _022_ (
    .A(state[2]),
    .B(state[1]),
    .C(state[0]),
    .X(busy)
  );
  sky130_fd_sc_hd__nor2_1 _023_ (
    .A(_000_),
    .B(state[0]),
    .Y(done)
  );
  sky130_fd_sc_hd__a21oi_1 _024_ (
    .A1(HREADY),
    .A2(wr),
    .B1(rd),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand3_1 _025_ (
    .A(state[1]),
    .B(HREADY),
    .C(_005_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a32oi_1 _026_ (
    .A1(state[1]),
    .A2(HREADY),
    .A3(_005_),
    .B1(_001_),
    .B2(_000_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o221ai_1 _027_ (
    .A1(HREADY),
    .A2(_004_),
    .B1(busy),
    .B2(_006_),
    .C1(_008_),
    .Y(nstate[0])
  );
  sky130_fd_sc_hd__nor3b_1 _028_ (
    .A(HREADY),
    .B(rd),
    .C_N(wr),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _029_ (
    .A1(HREADY),
    .A2(rd),
    .B1(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _030_ (
    .A(state[2]),
    .B(HREADY),
    .Y(_011_)
  );
  sky130_fd_sc_hd__o22ai_1 _031_ (
    .A1(state[1]),
    .A2(HREADY),
    .B1(_001_),
    .B2(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__o21ai_0 _032_ (
    .A1(busy),
    .A2(_010_),
    .B1(_012_),
    .Y(nstate[1])
  );
  sky130_fd_sc_hd__nand3b_1 _033_ (
    .A_N(rd),
    .B(wr),
    .C(HREADY),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o221ai_1 _034_ (
    .A1(_004_),
    .A2(_011_),
    .B1(_013_),
    .B2(busy),
    .C1(_007_),
    .Y(nstate[2])
  );
  sky130_fd_sc_hd__dfrtp_1 _035_ (
    .CLK(HCLK),
    .D(nstate[0]),
    .Q(state[0]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _036_ (
    .CLK(HCLK),
    .D(nstate[1]),
    .Q(state[1]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _037_ (
    .CLK(HCLK),
    .D(nstate[2]),
    .Q(state[2]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__conb_1 _038_ (
    .HI(HSIZE[1])
  );
  sky130_fd_sc_hd__conb_1 _039_ (
    .LO(HSIZE[0])
  );
  sky130_fd_sc_hd__conb_1 _040_ (
    .LO(HSIZE[2])
  );
  sky130_fd_sc_hd__conb_1 _041_ (
    .LO(HTRANS[0])
  );
  sky130_fd_sc_hd__buf_2 _042_ (
    .A(addr[0]),
    .X(HADDR[0])
  );
  sky130_fd_sc_hd__buf_2 _043_ (
    .A(addr[1]),
    .X(HADDR[1])
  );
  sky130_fd_sc_hd__buf_2 _044_ (
    .A(addr[2]),
    .X(HADDR[2])
  );
  sky130_fd_sc_hd__buf_2 _045_ (
    .A(addr[3]),
    .X(HADDR[3])
  );
  sky130_fd_sc_hd__buf_2 _046_ (
    .A(addr[4]),
    .X(HADDR[4])
  );
  sky130_fd_sc_hd__buf_2 _047_ (
    .A(addr[5]),
    .X(HADDR[5])
  );
  sky130_fd_sc_hd__buf_2 _048_ (
    .A(addr[6]),
    .X(HADDR[6])
  );
  sky130_fd_sc_hd__buf_2 _049_ (
    .A(addr[7]),
    .X(HADDR[7])
  );
  sky130_fd_sc_hd__buf_2 _050_ (
    .A(addr[8]),
    .X(HADDR[8])
  );
  sky130_fd_sc_hd__buf_2 _051_ (
    .A(addr[9]),
    .X(HADDR[9])
  );
  sky130_fd_sc_hd__buf_2 _052_ (
    .A(addr[10]),
    .X(HADDR[10])
  );
  sky130_fd_sc_hd__buf_2 _053_ (
    .A(addr[11]),
    .X(HADDR[11])
  );
  sky130_fd_sc_hd__buf_2 _054_ (
    .A(addr[12]),
    .X(HADDR[12])
  );
  sky130_fd_sc_hd__buf_2 _055_ (
    .A(addr[13]),
    .X(HADDR[13])
  );
  sky130_fd_sc_hd__buf_2 _056_ (
    .A(addr[14]),
    .X(HADDR[14])
  );
  sky130_fd_sc_hd__buf_2 _057_ (
    .A(addr[15]),
    .X(HADDR[15])
  );
  sky130_fd_sc_hd__buf_2 _058_ (
    .A(addr[16]),
    .X(HADDR[16])
  );
  sky130_fd_sc_hd__buf_2 _059_ (
    .A(addr[17]),
    .X(HADDR[17])
  );
  sky130_fd_sc_hd__buf_2 _060_ (
    .A(addr[18]),
    .X(HADDR[18])
  );
  sky130_fd_sc_hd__buf_2 _061_ (
    .A(addr[19]),
    .X(HADDR[19])
  );
  sky130_fd_sc_hd__buf_2 _062_ (
    .A(addr[20]),
    .X(HADDR[20])
  );
  sky130_fd_sc_hd__buf_2 _063_ (
    .A(addr[21]),
    .X(HADDR[21])
  );
  sky130_fd_sc_hd__buf_2 _064_ (
    .A(addr[22]),
    .X(HADDR[22])
  );
  sky130_fd_sc_hd__buf_2 _065_ (
    .A(addr[23]),
    .X(HADDR[23])
  );
  sky130_fd_sc_hd__buf_2 _066_ (
    .A(addr[24]),
    .X(HADDR[24])
  );
  sky130_fd_sc_hd__buf_2 _067_ (
    .A(addr[25]),
    .X(HADDR[25])
  );
  sky130_fd_sc_hd__buf_2 _068_ (
    .A(addr[26]),
    .X(HADDR[26])
  );
  sky130_fd_sc_hd__buf_2 _069_ (
    .A(addr[27]),
    .X(HADDR[27])
  );
  sky130_fd_sc_hd__buf_2 _070_ (
    .A(addr[28]),
    .X(HADDR[28])
  );
  sky130_fd_sc_hd__buf_2 _071_ (
    .A(addr[29]),
    .X(HADDR[29])
  );
  sky130_fd_sc_hd__buf_2 _072_ (
    .A(addr[30]),
    .X(HADDR[30])
  );
  sky130_fd_sc_hd__buf_2 _073_ (
    .A(addr[31]),
    .X(HADDR[31])
  );
  sky130_fd_sc_hd__buf_2 _074_ (
    .A(wdata[0]),
    .X(HWDATA[0])
  );
  sky130_fd_sc_hd__buf_2 _075_ (
    .A(wdata[1]),
    .X(HWDATA[1])
  );
  sky130_fd_sc_hd__buf_2 _076_ (
    .A(wdata[2]),
    .X(HWDATA[2])
  );
  sky130_fd_sc_hd__buf_2 _077_ (
    .A(wdata[3]),
    .X(HWDATA[3])
  );
  sky130_fd_sc_hd__buf_2 _078_ (
    .A(wdata[4]),
    .X(HWDATA[4])
  );
  sky130_fd_sc_hd__buf_2 _079_ (
    .A(wdata[5]),
    .X(HWDATA[5])
  );
  sky130_fd_sc_hd__buf_2 _080_ (
    .A(wdata[6]),
    .X(HWDATA[6])
  );
  sky130_fd_sc_hd__buf_2 _081_ (
    .A(wdata[7]),
    .X(HWDATA[7])
  );
  sky130_fd_sc_hd__buf_2 _082_ (
    .A(wdata[8]),
    .X(HWDATA[8])
  );
  sky130_fd_sc_hd__buf_2 _083_ (
    .A(wdata[9]),
    .X(HWDATA[9])
  );
  sky130_fd_sc_hd__buf_2 _084_ (
    .A(wdata[10]),
    .X(HWDATA[10])
  );
  sky130_fd_sc_hd__buf_2 _085_ (
    .A(wdata[11]),
    .X(HWDATA[11])
  );
  sky130_fd_sc_hd__buf_2 _086_ (
    .A(wdata[12]),
    .X(HWDATA[12])
  );
  sky130_fd_sc_hd__buf_2 _087_ (
    .A(wdata[13]),
    .X(HWDATA[13])
  );
  sky130_fd_sc_hd__buf_2 _088_ (
    .A(wdata[14]),
    .X(HWDATA[14])
  );
  sky130_fd_sc_hd__buf_2 _089_ (
    .A(wdata[15]),
    .X(HWDATA[15])
  );
  sky130_fd_sc_hd__buf_2 _090_ (
    .A(wdata[16]),
    .X(HWDATA[16])
  );
  sky130_fd_sc_hd__buf_2 _091_ (
    .A(wdata[17]),
    .X(HWDATA[17])
  );
  sky130_fd_sc_hd__buf_2 _092_ (
    .A(wdata[18]),
    .X(HWDATA[18])
  );
  sky130_fd_sc_hd__buf_2 _093_ (
    .A(wdata[19]),
    .X(HWDATA[19])
  );
  sky130_fd_sc_hd__buf_2 _094_ (
    .A(wdata[20]),
    .X(HWDATA[20])
  );
  sky130_fd_sc_hd__buf_2 _095_ (
    .A(wdata[21]),
    .X(HWDATA[21])
  );
  sky130_fd_sc_hd__buf_2 _096_ (
    .A(wdata[22]),
    .X(HWDATA[22])
  );
  sky130_fd_sc_hd__buf_2 _097_ (
    .A(wdata[23]),
    .X(HWDATA[23])
  );
  sky130_fd_sc_hd__buf_2 _098_ (
    .A(wdata[24]),
    .X(HWDATA[24])
  );
  sky130_fd_sc_hd__buf_2 _099_ (
    .A(wdata[25]),
    .X(HWDATA[25])
  );
  sky130_fd_sc_hd__buf_2 _100_ (
    .A(wdata[26]),
    .X(HWDATA[26])
  );
  sky130_fd_sc_hd__buf_2 _101_ (
    .A(wdata[27]),
    .X(HWDATA[27])
  );
  sky130_fd_sc_hd__buf_2 _102_ (
    .A(wdata[28]),
    .X(HWDATA[28])
  );
  sky130_fd_sc_hd__buf_2 _103_ (
    .A(wdata[29]),
    .X(HWDATA[29])
  );
  sky130_fd_sc_hd__buf_2 _104_ (
    .A(wdata[30]),
    .X(HWDATA[30])
  );
  sky130_fd_sc_hd__buf_2 _105_ (
    .A(wdata[31]),
    .X(HWDATA[31])
  );
  sky130_fd_sc_hd__buf_2 _106_ (
    .A(HRDATA[0]),
    .X(rdata[0])
  );
  sky130_fd_sc_hd__buf_2 _107_ (
    .A(HRDATA[1]),
    .X(rdata[1])
  );
  sky130_fd_sc_hd__buf_2 _108_ (
    .A(HRDATA[2]),
    .X(rdata[2])
  );
  sky130_fd_sc_hd__buf_2 _109_ (
    .A(HRDATA[3]),
    .X(rdata[3])
  );
  sky130_fd_sc_hd__buf_2 _110_ (
    .A(HRDATA[4]),
    .X(rdata[4])
  );
  sky130_fd_sc_hd__buf_2 _111_ (
    .A(HRDATA[5]),
    .X(rdata[5])
  );
  sky130_fd_sc_hd__buf_2 _112_ (
    .A(HRDATA[6]),
    .X(rdata[6])
  );
  sky130_fd_sc_hd__buf_2 _113_ (
    .A(HRDATA[7]),
    .X(rdata[7])
  );
  sky130_fd_sc_hd__buf_2 _114_ (
    .A(HRDATA[8]),
    .X(rdata[8])
  );
  sky130_fd_sc_hd__buf_2 _115_ (
    .A(HRDATA[9]),
    .X(rdata[9])
  );
  sky130_fd_sc_hd__buf_2 _116_ (
    .A(HRDATA[10]),
    .X(rdata[10])
  );
  sky130_fd_sc_hd__buf_2 _117_ (
    .A(HRDATA[11]),
    .X(rdata[11])
  );
  sky130_fd_sc_hd__buf_2 _118_ (
    .A(HRDATA[12]),
    .X(rdata[12])
  );
  sky130_fd_sc_hd__buf_2 _119_ (
    .A(HRDATA[13]),
    .X(rdata[13])
  );
  sky130_fd_sc_hd__buf_2 _120_ (
    .A(HRDATA[14]),
    .X(rdata[14])
  );
  sky130_fd_sc_hd__buf_2 _121_ (
    .A(HRDATA[15]),
    .X(rdata[15])
  );
  sky130_fd_sc_hd__buf_2 _122_ (
    .A(HRDATA[16]),
    .X(rdata[16])
  );
  sky130_fd_sc_hd__buf_2 _123_ (
    .A(HRDATA[17]),
    .X(rdata[17])
  );
  sky130_fd_sc_hd__buf_2 _124_ (
    .A(HRDATA[18]),
    .X(rdata[18])
  );
  sky130_fd_sc_hd__buf_2 _125_ (
    .A(HRDATA[19]),
    .X(rdata[19])
  );
  sky130_fd_sc_hd__buf_2 _126_ (
    .A(HRDATA[20]),
    .X(rdata[20])
  );
  sky130_fd_sc_hd__buf_2 _127_ (
    .A(HRDATA[21]),
    .X(rdata[21])
  );
  sky130_fd_sc_hd__buf_2 _128_ (
    .A(HRDATA[22]),
    .X(rdata[22])
  );
  sky130_fd_sc_hd__buf_2 _129_ (
    .A(HRDATA[23]),
    .X(rdata[23])
  );
  sky130_fd_sc_hd__buf_2 _130_ (
    .A(HRDATA[24]),
    .X(rdata[24])
  );
  sky130_fd_sc_hd__buf_2 _131_ (
    .A(HRDATA[25]),
    .X(rdata[25])
  );
  sky130_fd_sc_hd__buf_2 _132_ (
    .A(HRDATA[26]),
    .X(rdata[26])
  );
  sky130_fd_sc_hd__buf_2 _133_ (
    .A(HRDATA[27]),
    .X(rdata[27])
  );
  sky130_fd_sc_hd__buf_2 _134_ (
    .A(HRDATA[28]),
    .X(rdata[28])
  );
  sky130_fd_sc_hd__buf_2 _135_ (
    .A(HRDATA[29]),
    .X(rdata[29])
  );
  sky130_fd_sc_hd__buf_2 _136_ (
    .A(HRDATA[30]),
    .X(rdata[30])
  );
  sky130_fd_sc_hd__buf_2 _137_ (
    .A(HRDATA[31]),
    .X(rdata[31])
  );
endmodule

module AHB_UART_MASTER(HCLK, HRESETn, HADDR, HTRANS, HSIZE, HWRITE, HWDATA, HREADY, HRDATA, RX, TX);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire [51:0] _107_;
  wire [3:0] _108_;
  output [31:0] HADDR;
  wire [31:0] HADDR;
  input HCLK;
  wire HCLK;
  input [31:0] HRDATA;
  wire [31:0] HRDATA;
  input HREADY;
  wire HREADY;
  input HRESETn;
  wire HRESETn;
  output [2:0] HSIZE;
  wire [2:0] HSIZE;
  output [1:0] HTRANS;
  wire [1:0] HTRANS;
  output [31:0] HWDATA;
  wire [31:0] HWDATA;
  output HWRITE;
  wire HWRITE;
  input RX;
  wire RX;
  output TX;
  wire TX;
  wire [31:0] addr;
  wire b_tick;
  wire cmd_rd;
  wire cmd_wr;
  wire done;
  wire [3:0] nstate;
  wire rd;
  wire [31:0] rdata;
  wire [31:0] rdata_reg;
  wire [7:0] rx_data;
  wire rx_done;
  wire [3:0] state;
  wire [7:0] tx_data;
  wire tx_done;
  wire tx_start;
  wire [31:0] wdata;
  wire wr;
  sky130_fd_sc_hd__clkinv_1 _109_ (
    .A(done),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _110_ (
    .A(tx_done),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _111_ (
    .A(rd),
    .Y(_064_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _112_ (
    .A(state[2]),
    .SLEEP(state[3]),
    .X(_065_)
  );
  sky130_fd_sc_hd__and2_0 _113_ (
    .A(state[1]),
    .B(state[0]),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand3_1 _114_ (
    .A(state[1]),
    .B(state[0]),
    .C(rx_done),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _115_ (
    .A(_065_),
    .B(_067_),
    .Y(_107_[50])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _116_ (
    .A(state[2]),
    .SLEEP(state[3]),
    .X(_068_)
  );
  sky130_fd_sc_hd__nand2b_1 _117_ (
    .A_N(state[3]),
    .B(state[2]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _118_ (
    .A(state[0]),
    .SLEEP(state[1]),
    .X(_070_)
  );
  sky130_fd_sc_hd__and3_1 _119_ (
    .A(rx_done),
    .B(_068_),
    .C(_070_),
    .X(_107_[41])
  );
  sky130_fd_sc_hd__nor2_1 _120_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__and3_1 _121_ (
    .A(rx_done),
    .B(_068_),
    .C(_071_),
    .X(_107_[44])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _122_ (
    .A(rx_data[0]),
    .SLEEP(rx_data[4]),
    .X(_072_)
  );
  sky130_fd_sc_hd__and3b_1 _123_ (
    .A_N(rx_data[6]),
    .B(rx_data[7]),
    .C(rx_data[5]),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor3b_1 _124_ (
    .A(rx_data[1]),
    .B(rx_data[3]),
    .C_N(rx_data[2]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__and3_1 _125_ (
    .A(_072_),
    .B(_073_),
    .C(_074_),
    .X(cmd_rd)
  );
  sky130_fd_sc_hd__nor3b_1 _126_ (
    .A(rx_data[3]),
    .B(rx_data[2]),
    .C_N(rx_data[1]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__and3_1 _127_ (
    .A(_072_),
    .B(_073_),
    .C(_075_),
    .X(cmd_wr)
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _129_ (
    .A(state[1]),
    .B(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand3b_1 _130_ (
    .A_N(state[1]),
    .B(state[3]),
    .C(state[2]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor3b_1 _131_ (
    .A(state[0]),
    .B(_076_),
    .C_N(state[1]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand4b_1 _132_ (
    .A_N(state[0]),
    .B(state[1]),
    .C(state[3]),
    .D(state[2]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__mux2i_1 _133_ (
    .A0(rdata_reg[16]),
    .A1(rdata_reg[24]),
    .S(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _134_ (
    .A(state[0]),
    .B(_078_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and4b_1 _135_ (
    .A_N(state[1]),
    .B(state[0]),
    .C(state[2]),
    .D(state[3]),
    .X(_015_)
  );
  sky130_fd_sc_hd__a22oi_1 _136_ (
    .A1(rdata_reg[0]),
    .A2(_014_),
    .B1(_015_),
    .B2(rdata_reg[8]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o21ai_0 _137_ (
    .A1(_077_),
    .A2(_013_),
    .B1(_016_),
    .Y(tx_data[0])
  );
  sky130_fd_sc_hd__nand3_1 _138_ (
    .A(rdata_reg[25]),
    .B(_078_),
    .C(_012_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a222oi_1 _139_ (
    .A1(rdata_reg[17]),
    .A2(_011_),
    .B1(_014_),
    .B2(rdata_reg[1]),
    .C1(_015_),
    .C2(rdata_reg[9]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(_017_),
    .B(_018_),
    .Y(tx_data[1])
  );
  sky130_fd_sc_hd__nand3_1 _141_ (
    .A(rdata_reg[26]),
    .B(_078_),
    .C(_012_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a222oi_1 _142_ (
    .A1(rdata_reg[18]),
    .A2(_011_),
    .B1(_014_),
    .B2(rdata_reg[2]),
    .C1(_015_),
    .C2(rdata_reg[10]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(_019_),
    .B(_020_),
    .Y(tx_data[2])
  );
  sky130_fd_sc_hd__nand3_1 _144_ (
    .A(rdata_reg[27]),
    .B(_078_),
    .C(_012_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a222oi_1 _145_ (
    .A1(rdata_reg[19]),
    .A2(_011_),
    .B1(_014_),
    .B2(rdata_reg[3]),
    .C1(_015_),
    .C2(rdata_reg[11]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _146_ (
    .A(_021_),
    .B(_022_),
    .Y(tx_data[3])
  );
  sky130_fd_sc_hd__nand3_1 _147_ (
    .A(rdata_reg[28]),
    .B(_078_),
    .C(_012_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a222oi_1 _148_ (
    .A1(rdata_reg[20]),
    .A2(_011_),
    .B1(_014_),
    .B2(rdata_reg[4]),
    .C1(_015_),
    .C2(rdata_reg[12]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _149_ (
    .A(_023_),
    .B(_024_),
    .Y(tx_data[4])
  );
  sky130_fd_sc_hd__nand3_1 _150_ (
    .A(rdata_reg[29]),
    .B(_078_),
    .C(_012_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a222oi_1 _151_ (
    .A1(rdata_reg[21]),
    .A2(_011_),
    .B1(_014_),
    .B2(rdata_reg[5]),
    .C1(_015_),
    .C2(rdata_reg[13]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _152_ (
    .A(_025_),
    .B(_026_),
    .Y(tx_data[5])
  );
  sky130_fd_sc_hd__nand3_1 _153_ (
    .A(rdata_reg[30]),
    .B(_078_),
    .C(_012_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a222oi_1 _154_ (
    .A1(rdata_reg[22]),
    .A2(_011_),
    .B1(_014_),
    .B2(rdata_reg[6]),
    .C1(_015_),
    .C2(rdata_reg[14]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _155_ (
    .A(_027_),
    .B(_028_),
    .Y(tx_data[6])
  );
  sky130_fd_sc_hd__nand3_1 _156_ (
    .A(rdata_reg[31]),
    .B(_078_),
    .C(_012_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a222oi_1 _157_ (
    .A1(rdata_reg[23]),
    .A2(_011_),
    .B1(_014_),
    .B2(rdata_reg[7]),
    .C1(_015_),
    .C2(rdata_reg[15]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _158_ (
    .A(_029_),
    .B(_030_),
    .Y(tx_data[7])
  );
  sky130_fd_sc_hd__nor4bb_1 _159_ (
    .A(state[3]),
    .B(state[0]),
    .C_N(state[1]),
    .D_N(state[2]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__and2_0 _160_ (
    .A(rx_done),
    .B(_031_),
    .X(_001_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _161_ (
    .A(rd),
    .SLEEP(wr),
    .X(_032_)
  );
  sky130_fd_sc_hd__and3_1 _162_ (
    .A(rx_done),
    .B(rd),
    .C(_031_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _163_ (
    .A(_001_),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor3b_1 _164_ (
    .A(state[3]),
    .B(rx_done),
    .C_N(_066_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a311oi_1 _165_ (
    .A1(wr),
    .A2(_064_),
    .A3(_001_),
    .B1(_034_),
    .C1(_107_[44]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand4_1 _166_ (
    .A(state[2]),
    .B(state[3]),
    .C(state[1]),
    .D(state[0]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor3_1 _167_ (
    .A(_065_),
    .B(_066_),
    .C(_071_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__o31ai_1 _168_ (
    .A1(_065_),
    .A2(_066_),
    .A3(_071_),
    .B1(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _169_ (
    .A(state[3]),
    .SLEEP(state[2]),
    .X(_038_)
  );
  sky130_fd_sc_hd__a31oi_1 _170_ (
    .A1(_062_),
    .A2(_066_),
    .A3(_038_),
    .B1(_037_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor3b_1 _171_ (
    .A(rx_done),
    .B(_069_),
    .C_N(_070_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a32oi_1 _172_ (
    .A1(rx_done),
    .A2(_071_),
    .A3(_038_),
    .B1(_015_),
    .B2(_063_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor4bb_1 _173_ (
    .A(state[2]),
    .B(state[1]),
    .C_N(state[0]),
    .D_N(state[3]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor4bb_1 _174_ (
    .A(state[2]),
    .B(state[0]),
    .C_N(state[1]),
    .D_N(state[3]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(rx_done),
    .B(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux2i_1 _176_ (
    .A0(_042_),
    .A1(_043_),
    .S(rx_done),
    .Y(_045_)
  );
  sky130_fd_sc_hd__or3b_1 _177_ (
    .A(state[1]),
    .B(state[0]),
    .C_N(tx_done),
    .X(_046_)
  );
  sky130_fd_sc_hd__a21o_1 _178_ (
    .A1(_065_),
    .A2(_076_),
    .B1(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__and4b_1 _179_ (
    .A_N(_040_),
    .B(_041_),
    .C(_045_),
    .D(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand4_1 _180_ (
    .A(_033_),
    .B(_035_),
    .C(_039_),
    .D(_048_),
    .Y(_108_[0])
  );
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(rx_done),
    .B(_042_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a21oi_1 _182_ (
    .A1(tx_done),
    .A2(_015_),
    .B1(_107_[41]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o22ai_1 _183_ (
    .A1(tx_done),
    .A2(_012_),
    .B1(_046_),
    .B2(_065_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor4_1 _184_ (
    .A(_031_),
    .B(_034_),
    .C(_043_),
    .D(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand4_1 _185_ (
    .A(_039_),
    .B(_049_),
    .C(_050_),
    .D(_052_),
    .Y(_108_[1])
  );
  sky130_fd_sc_hd__o2111ai_1 _186_ (
    .A1(_074_),
    .A2(_075_),
    .B1(rx_done),
    .C1(_072_),
    .D1(_073_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _187_ (
    .A(_037_),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(_077_),
    .B(_051_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o211ai_1 _189_ (
    .A1(state[0]),
    .A2(_032_),
    .B1(rx_done),
    .C1(state[1]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(_068_),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand3_1 _191_ (
    .A(done),
    .B(_066_),
    .C(_038_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__and3b_1 _192_ (
    .A_N(_107_[50]),
    .B(_044_),
    .C(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand4_1 _193_ (
    .A(_054_),
    .B(_055_),
    .C(_057_),
    .D(_059_),
    .Y(_108_[2])
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(_067_),
    .B(_069_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _195_ (
    .A(_038_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand4_1 _196_ (
    .A(_033_),
    .B(_054_),
    .C(_055_),
    .D(_061_),
    .Y(_108_[3])
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(_067_),
    .B(_076_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__and2_0 _198_ (
    .A(wr),
    .B(_060_),
    .X(_002_)
  );
  sky130_fd_sc_hd__and4_1 _199_ (
    .A(rx_done),
    .B(wr),
    .C(_071_),
    .D(_038_),
    .X(_003_)
  );
  sky130_fd_sc_hd__and3_1 _200_ (
    .A(rx_done),
    .B(wr),
    .C(_042_),
    .X(_004_)
  );
  sky130_fd_sc_hd__and3_1 _201_ (
    .A(rx_done),
    .B(wr),
    .C(_043_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _202_ (
    .A(_062_),
    .B(_064_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__o31ai_1 _203_ (
    .A1(_063_),
    .A2(_066_),
    .A3(_076_),
    .B1(_058_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__and3_1 _204_ (
    .A(rx_done),
    .B(wr),
    .C(_043_),
    .X(_006_)
  );
  sky130_fd_sc_hd__dlclkp_1 _205_ (
    .CLK(HCLK),
    .GATE(_000_),
    .GCLK(_079_)
  );
  sky130_fd_sc_hd__dlclkp_1 _206_ (
    .CLK(HCLK),
    .GATE(_000_),
    .GCLK(_080_)
  );
  sky130_fd_sc_hd__dlclkp_2 _207_ (
    .CLK(HCLK),
    .GATE(_107_[50]),
    .GCLK(_081_)
  );
  sky130_fd_sc_hd__dlclkp_2 _208_ (
    .CLK(HCLK),
    .GATE(_107_[44]),
    .GCLK(_082_)
  );
  sky130_fd_sc_hd__dlclkp_2 _209_ (
    .CLK(HCLK),
    .GATE(_107_[41]),
    .GCLK(_083_)
  );
  sky130_fd_sc_hd__dlclkp_2 _210_ (
    .CLK(HCLK),
    .GATE(_001_),
    .GCLK(_084_)
  );
  sky130_fd_sc_hd__dlclkp_2 _211_ (
    .CLK(HCLK),
    .GATE(_002_),
    .GCLK(_085_)
  );
  sky130_fd_sc_hd__dlclkp_2 _212_ (
    .CLK(HCLK),
    .GATE(_003_),
    .GCLK(_086_)
  );
  sky130_fd_sc_hd__dlclkp_2 _213_ (
    .CLK(HCLK),
    .GATE(_004_),
    .GCLK(_087_)
  );
  sky130_fd_sc_hd__dlclkp_2 _214_ (
    .CLK(HCLK),
    .GATE(_005_),
    .GCLK(_088_)
  );
  sky130_fd_sc_hd__dlclkp_4 _215_ (
    .CLK(HCLK),
    .GATE(_008_),
    .GCLK(_089_)
  );
  sky130_fd_sc_hd__dfrtp_1 _216_ (
    .CLK(_080_),
    .D(cmd_rd),
    .Q(rd),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfxtp_1 _217_ (
    .CLK(_081_),
    .D(rx_data[0]),
    .Q(addr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _218_ (
    .CLK(_081_),
    .D(rx_data[1]),
    .Q(addr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _219_ (
    .CLK(_081_),
    .D(rx_data[2]),
    .Q(addr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _220_ (
    .CLK(_081_),
    .D(rx_data[3]),
    .Q(addr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _221_ (
    .CLK(_081_),
    .D(rx_data[4]),
    .Q(addr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _222_ (
    .CLK(_081_),
    .D(rx_data[5]),
    .Q(addr[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _223_ (
    .CLK(_081_),
    .D(rx_data[6]),
    .Q(addr[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _224_ (
    .CLK(_081_),
    .D(rx_data[7]),
    .Q(addr[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _225_ (
    .CLK(_082_),
    .D(rx_data[0]),
    .Q(addr[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _226_ (
    .CLK(_082_),
    .D(rx_data[1]),
    .Q(addr[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _227_ (
    .CLK(_082_),
    .D(rx_data[2]),
    .Q(addr[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _228_ (
    .CLK(_082_),
    .D(rx_data[3]),
    .Q(addr[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _229_ (
    .CLK(_082_),
    .D(rx_data[4]),
    .Q(addr[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _230_ (
    .CLK(_082_),
    .D(rx_data[5]),
    .Q(addr[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _231_ (
    .CLK(_082_),
    .D(rx_data[6]),
    .Q(addr[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _232_ (
    .CLK(_082_),
    .D(rx_data[7]),
    .Q(addr[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _233_ (
    .CLK(_083_),
    .D(rx_data[0]),
    .Q(addr[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _234_ (
    .CLK(_083_),
    .D(rx_data[1]),
    .Q(addr[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _235_ (
    .CLK(_083_),
    .D(rx_data[2]),
    .Q(addr[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _236_ (
    .CLK(_083_),
    .D(rx_data[3]),
    .Q(addr[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _237_ (
    .CLK(_083_),
    .D(rx_data[4]),
    .Q(addr[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _238_ (
    .CLK(_083_),
    .D(rx_data[5]),
    .Q(addr[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _239_ (
    .CLK(_083_),
    .D(rx_data[6]),
    .Q(addr[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _240_ (
    .CLK(_083_),
    .D(rx_data[7]),
    .Q(addr[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _241_ (
    .CLK(_084_),
    .D(rx_data[0]),
    .Q(addr[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _242_ (
    .CLK(_084_),
    .D(rx_data[1]),
    .Q(addr[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _243_ (
    .CLK(_084_),
    .D(rx_data[2]),
    .Q(addr[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _244_ (
    .CLK(_084_),
    .D(rx_data[3]),
    .Q(addr[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _245_ (
    .CLK(_084_),
    .D(rx_data[4]),
    .Q(addr[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _246_ (
    .CLK(_084_),
    .D(rx_data[5]),
    .Q(addr[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _247_ (
    .CLK(_084_),
    .D(rx_data[6]),
    .Q(addr[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _248_ (
    .CLK(_084_),
    .D(rx_data[7]),
    .Q(addr[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _249_ (
    .CLK(_085_),
    .D(rx_data[0]),
    .Q(wdata[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _250_ (
    .CLK(_085_),
    .D(rx_data[1]),
    .Q(wdata[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _251_ (
    .CLK(_085_),
    .D(rx_data[2]),
    .Q(wdata[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _252_ (
    .CLK(_085_),
    .D(rx_data[3]),
    .Q(wdata[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _253_ (
    .CLK(_085_),
    .D(rx_data[4]),
    .Q(wdata[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _254_ (
    .CLK(_085_),
    .D(rx_data[5]),
    .Q(wdata[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _255_ (
    .CLK(_085_),
    .D(rx_data[6]),
    .Q(wdata[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _256_ (
    .CLK(_085_),
    .D(rx_data[7]),
    .Q(wdata[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _257_ (
    .CLK(_086_),
    .D(rx_data[0]),
    .Q(wdata[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _258_ (
    .CLK(_086_),
    .D(rx_data[1]),
    .Q(wdata[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _259_ (
    .CLK(_086_),
    .D(rx_data[2]),
    .Q(wdata[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _260_ (
    .CLK(_086_),
    .D(rx_data[3]),
    .Q(wdata[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _261_ (
    .CLK(_086_),
    .D(rx_data[4]),
    .Q(wdata[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _262_ (
    .CLK(_086_),
    .D(rx_data[5]),
    .Q(wdata[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _263_ (
    .CLK(_086_),
    .D(rx_data[6]),
    .Q(wdata[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _264_ (
    .CLK(_086_),
    .D(rx_data[7]),
    .Q(wdata[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _265_ (
    .CLK(_087_),
    .D(rx_data[0]),
    .Q(wdata[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _266_ (
    .CLK(_087_),
    .D(rx_data[1]),
    .Q(wdata[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _267_ (
    .CLK(_087_),
    .D(rx_data[2]),
    .Q(wdata[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _268_ (
    .CLK(_087_),
    .D(rx_data[3]),
    .Q(wdata[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _269_ (
    .CLK(_087_),
    .D(rx_data[4]),
    .Q(wdata[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _270_ (
    .CLK(_087_),
    .D(rx_data[5]),
    .Q(wdata[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _271_ (
    .CLK(_087_),
    .D(rx_data[6]),
    .Q(wdata[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _272_ (
    .CLK(_087_),
    .D(rx_data[7]),
    .Q(wdata[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _273_ (
    .CLK(_088_),
    .D(rx_data[0]),
    .Q(wdata[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _274_ (
    .CLK(_088_),
    .D(rx_data[1]),
    .Q(wdata[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _275_ (
    .CLK(_088_),
    .D(rx_data[2]),
    .Q(wdata[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _276_ (
    .CLK(_088_),
    .D(rx_data[3]),
    .Q(wdata[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _277_ (
    .CLK(_088_),
    .D(rx_data[4]),
    .Q(wdata[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _278_ (
    .CLK(_088_),
    .D(rx_data[5]),
    .Q(wdata[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _279_ (
    .CLK(_088_),
    .D(rx_data[6]),
    .Q(wdata[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _280_ (
    .CLK(_088_),
    .D(rx_data[7]),
    .Q(wdata[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _281_ (
    .CLK(_089_),
    .D(rdata[0]),
    .Q(rdata_reg[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _282_ (
    .CLK(_089_),
    .D(rdata[1]),
    .Q(rdata_reg[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _283_ (
    .CLK(_089_),
    .D(rdata[2]),
    .Q(rdata_reg[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _284_ (
    .CLK(_089_),
    .D(rdata[3]),
    .Q(rdata_reg[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _285_ (
    .CLK(_089_),
    .D(rdata[4]),
    .Q(rdata_reg[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _286_ (
    .CLK(_089_),
    .D(rdata[5]),
    .Q(rdata_reg[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _287_ (
    .CLK(_089_),
    .D(rdata[6]),
    .Q(rdata_reg[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _288_ (
    .CLK(_089_),
    .D(rdata[7]),
    .Q(rdata_reg[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _289_ (
    .CLK(_089_),
    .D(rdata[8]),
    .Q(rdata_reg[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _290_ (
    .CLK(_089_),
    .D(rdata[9]),
    .Q(rdata_reg[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _291_ (
    .CLK(_089_),
    .D(rdata[10]),
    .Q(rdata_reg[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _292_ (
    .CLK(_089_),
    .D(rdata[11]),
    .Q(rdata_reg[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _293_ (
    .CLK(_089_),
    .D(rdata[12]),
    .Q(rdata_reg[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _294_ (
    .CLK(_089_),
    .D(rdata[13]),
    .Q(rdata_reg[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _295_ (
    .CLK(_089_),
    .D(rdata[14]),
    .Q(rdata_reg[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _296_ (
    .CLK(_089_),
    .D(rdata[15]),
    .Q(rdata_reg[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _297_ (
    .CLK(_089_),
    .D(rdata[16]),
    .Q(rdata_reg[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _298_ (
    .CLK(_089_),
    .D(rdata[17]),
    .Q(rdata_reg[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _299_ (
    .CLK(_089_),
    .D(rdata[18]),
    .Q(rdata_reg[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _300_ (
    .CLK(_089_),
    .D(rdata[19]),
    .Q(rdata_reg[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _301_ (
    .CLK(_089_),
    .D(rdata[20]),
    .Q(rdata_reg[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _302_ (
    .CLK(_089_),
    .D(rdata[21]),
    .Q(rdata_reg[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _303_ (
    .CLK(_089_),
    .D(rdata[22]),
    .Q(rdata_reg[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _304_ (
    .CLK(_089_),
    .D(rdata[23]),
    .Q(rdata_reg[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _305_ (
    .CLK(_089_),
    .D(rdata[24]),
    .Q(rdata_reg[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _306_ (
    .CLK(_089_),
    .D(rdata[25]),
    .Q(rdata_reg[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _307_ (
    .CLK(_089_),
    .D(rdata[26]),
    .Q(rdata_reg[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _308_ (
    .CLK(_089_),
    .D(rdata[27]),
    .Q(rdata_reg[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _309_ (
    .CLK(_089_),
    .D(rdata[28]),
    .Q(rdata_reg[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _310_ (
    .CLK(_089_),
    .D(rdata[29]),
    .Q(rdata_reg[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _311_ (
    .CLK(_089_),
    .D(rdata[30]),
    .Q(rdata_reg[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _312_ (
    .CLK(_089_),
    .D(rdata[31]),
    .Q(rdata_reg[31])
  );
  sky130_fd_sc_hd__dfrtp_1 _313_ (
    .CLK(_079_),
    .D(cmd_wr),
    .Q(wr),
    .RESET_B(HRESETn)
  );
  \$_DLATCH_N_  \nstate_reg[0]  /* _314_ */ (
    .D(_108_[0]),
    .E(_009_),
    .Q(nstate[0])
  );
  \$_DLATCH_N_  \nstate_reg[1]  /* _315_ */ (
    .D(_108_[1]),
    .E(_009_),
    .Q(nstate[1])
  );
  \$_DLATCH_N_  \nstate_reg[2]  /* _316_ */ (
    .D(_108_[2]),
    .E(_009_),
    .Q(nstate[2])
  );
  \$_DLATCH_N_  \nstate_reg[3]  /* _317_ */ (
    .D(_108_[3]),
    .E(_009_),
    .Q(nstate[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _318_ (
    .CLK(HCLK),
    .D(_010_),
    .Q(tx_start)
  );
  sky130_fd_sc_hd__dfstp_2 _319_ (
    .CLK(HCLK),
    .D(nstate[0]),
    .Q(state[0]),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfstp_2 _320_ (
    .CLK(HCLK),
    .D(nstate[1]),
    .Q(state[1]),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfstp_2 _321_ (
    .CLK(HCLK),
    .D(nstate[2]),
    .Q(state[2]),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfstp_2 _322_ (
    .CLK(HCLK),
    .D(nstate[3]),
    .Q(state[3]),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__conb_1 _323_ (
    .HI(_090_)
  );
  sky130_fd_sc_hd__conb_1 _324_ (
    .HI(_091_)
  );
  sky130_fd_sc_hd__conb_1 _325_ (
    .HI(_092_)
  );
  sky130_fd_sc_hd__conb_1 _326_ (
    .HI(_093_)
  );
  sky130_fd_sc_hd__conb_1 _327_ (
    .HI(_094_)
  );
  sky130_fd_sc_hd__conb_1 _328_ (
    .LO(_095_)
  );
  sky130_fd_sc_hd__conb_1 _329_ (
    .LO(_096_)
  );
  sky130_fd_sc_hd__conb_1 _330_ (
    .LO(_097_)
  );
  sky130_fd_sc_hd__conb_1 _331_ (
    .LO(_098_)
  );
  sky130_fd_sc_hd__conb_1 _332_ (
    .LO(_099_)
  );
  sky130_fd_sc_hd__conb_1 _333_ (
    .LO(_100_)
  );
  sky130_fd_sc_hd__conb_1 _334_ (
    .LO(_101_)
  );
  sky130_fd_sc_hd__conb_1 _335_ (
    .LO(_102_)
  );
  sky130_fd_sc_hd__conb_1 _336_ (
    .LO(_103_)
  );
  sky130_fd_sc_hd__conb_1 _337_ (
    .LO(_104_)
  );
  sky130_fd_sc_hd__conb_1 _338_ (
    .LO(_105_)
  );
  sky130_fd_sc_hd__conb_1 _339_ (
    .LO(_106_)
  );
  AHB_MASTER M (
    .HADDR(HADDR),
    .HCLK(HCLK),
    .HRDATA(HRDATA),
    .HREADY(HREADY),
    .HRESETn(HRESETn),
    .HSIZE(HSIZE),
    .HTRANS(HTRANS),
    .HWDATA(HWDATA),
    .HWRITE(HWRITE),
    .addr(addr),
    .done(done),
    .rd(_007_),
    .rdata(rdata),
    .wdata(wdata),
    .wr(_006_)
  );
  BAUDGEN uBAUDGEN (
    .baudtick(b_tick),
    .clk(HCLK),
    .en(_090_),
    .prescale({ _106_, _105_, _104_, _103_, _102_, _101_, _100_, _099_, _098_, _097_, _094_, _093_, _096_, _095_, _092_, _091_ }),
    .rst_n(HRESETn)
  );
  UART_RX uUART_RX (
    .b_tick(b_tick),
    .clk(HCLK),
    .dout(rx_data),
    .resetn(HRESETn),
    .rx(RX),
    .rx_done(rx_done)
  );
  UART_TX uUART_TX (
    .b_tick(b_tick),
    .clk(HCLK),
    .d_in(tx_data),
    .resetn(HRESETn),
    .tx(TX),
    .tx_done(tx_done),
    .tx_start(tx_start)
  );
endmodule

module BAUDGEN(clk, rst_n, prescale, en, baudtick);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  output baudtick;
  wire baudtick;
  input clk;
  wire clk;
  wire [15:0] count_next;
  wire [15:0] count_reg;
  input en;
  wire en;
  input [15:0] prescale;
  wire [15:0] prescale;
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _048_ (
    .A(prescale[7]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _049_ (
    .A(prescale[9]),
    .B(count_reg[9]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _050_ (
    .A(prescale[3]),
    .B(count_reg[3]),
    .X(_010_)
  );
  sky130_fd_sc_hd__xor2_1 _051_ (
    .A(prescale[11]),
    .B(count_reg[11]),
    .X(_011_)
  );
  sky130_fd_sc_hd__xor2_1 _052_ (
    .A(prescale[5]),
    .B(count_reg[5]),
    .X(_012_)
  );
  sky130_fd_sc_hd__xor2_1 _053_ (
    .A(prescale[8]),
    .B(count_reg[8]),
    .X(_013_)
  );
  sky130_fd_sc_hd__xor2_1 _054_ (
    .A(prescale[4]),
    .B(count_reg[4]),
    .X(_014_)
  );
  sky130_fd_sc_hd__xor2_1 _055_ (
    .A(prescale[10]),
    .B(count_reg[10]),
    .X(_015_)
  );
  sky130_fd_sc_hd__xor2_1 _056_ (
    .A(prescale[14]),
    .B(count_reg[14]),
    .X(_016_)
  );
  sky130_fd_sc_hd__xor2_1 _057_ (
    .A(prescale[6]),
    .B(count_reg[6]),
    .X(_017_)
  );
  sky130_fd_sc_hd__xor2_1 _058_ (
    .A(prescale[13]),
    .B(count_reg[13]),
    .X(_018_)
  );
  sky130_fd_sc_hd__xor2_1 _059_ (
    .A(count_reg[0]),
    .B(prescale[0]),
    .X(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _060_ (
    .A(prescale[12]),
    .B(count_reg[12]),
    .X(_020_)
  );
  sky130_fd_sc_hd__xor2_1 _061_ (
    .A(prescale[1]),
    .B(count_reg[1]),
    .X(_021_)
  );
  sky130_fd_sc_hd__nor4_1 _062_ (
    .A(_010_),
    .B(_014_),
    .C(_015_),
    .D(_017_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor4_1 _063_ (
    .A(_011_),
    .B(_012_),
    .C(_013_),
    .D(_018_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xor2_1 _064_ (
    .A(prescale[2]),
    .B(count_reg[2]),
    .X(_024_)
  );
  sky130_fd_sc_hd__xor2_1 _065_ (
    .A(prescale[15]),
    .B(count_reg[15]),
    .X(_025_)
  );
  sky130_fd_sc_hd__a2111oi_0 _066_ (
    .A1(_008_),
    .A2(count_reg[7]),
    .B1(_016_),
    .C1(_024_),
    .D1(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o21ai_0 _067_ (
    .A1(_008_),
    .A2(count_reg[7]),
    .B1(_009_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor2_1 _068_ (
    .A(_019_),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand4_1 _069_ (
    .A(_022_),
    .B(_023_),
    .C(_026_),
    .D(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor3_1 _070_ (
    .A(_020_),
    .B(_021_),
    .C(_029_),
    .Y(baudtick)
  );
  sky130_fd_sc_hd__nor2_1 _071_ (
    .A(count_reg[0]),
    .B(baudtick),
    .Y(count_next[0])
  );
  sky130_fd_sc_hd__xnor2_1 _072_ (
    .A(count_reg[1]),
    .B(count_reg[0]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _073_ (
    .A(baudtick),
    .B(_030_),
    .Y(count_next[1])
  );
  sky130_fd_sc_hd__a21oi_1 _074_ (
    .A1(count_reg[1]),
    .A2(count_reg[0]),
    .B1(count_reg[2]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__and3_1 _075_ (
    .A(count_reg[1]),
    .B(count_reg[2]),
    .C(count_reg[0]),
    .X(_032_)
  );
  sky130_fd_sc_hd__nor3_1 _076_ (
    .A(baudtick),
    .B(_031_),
    .C(_032_),
    .Y(count_next[2])
  );
  sky130_fd_sc_hd__nor2_1 _077_ (
    .A(count_reg[3]),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__and4_1 _078_ (
    .A(count_reg[1]),
    .B(count_reg[2]),
    .C(count_reg[3]),
    .D(count_reg[0]),
    .X(_034_)
  );
  sky130_fd_sc_hd__nor3_1 _079_ (
    .A(baudtick),
    .B(_033_),
    .C(_034_),
    .Y(count_next[3])
  );
  sky130_fd_sc_hd__nor2_1 _080_ (
    .A(count_reg[4]),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__and2_0 _081_ (
    .A(count_reg[4]),
    .B(_034_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nor3_1 _082_ (
    .A(baudtick),
    .B(_035_),
    .C(_036_),
    .Y(count_next[4])
  );
  sky130_fd_sc_hd__xnor2_1 _083_ (
    .A(count_reg[5]),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _084_ (
    .A(baudtick),
    .B(_037_),
    .Y(count_next[5])
  );
  sky130_fd_sc_hd__and4_1 _085_ (
    .A(count_reg[4]),
    .B(count_reg[5]),
    .C(count_reg[6]),
    .D(_034_),
    .X(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _086_ (
    .A1(count_reg[5]),
    .A2(_036_),
    .B1(count_reg[6]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor3_1 _087_ (
    .A(baudtick),
    .B(_038_),
    .C(_039_),
    .Y(count_next[6])
  );
  sky130_fd_sc_hd__and2_0 _088_ (
    .A(count_reg[7]),
    .B(_038_),
    .X(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _089_ (
    .A(count_reg[7]),
    .B(_038_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor3_1 _090_ (
    .A(baudtick),
    .B(_040_),
    .C(_041_),
    .Y(count_next[7])
  );
  sky130_fd_sc_hd__nor2_1 _091_ (
    .A(count_reg[8]),
    .B(_040_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a311oi_1 _092_ (
    .A1(count_reg[7]),
    .A2(count_reg[8]),
    .A3(_038_),
    .B1(_042_),
    .C1(baudtick),
    .Y(count_next[8])
  );
  sky130_fd_sc_hd__and4_1 _093_ (
    .A(count_reg[7]),
    .B(count_reg[8]),
    .C(count_reg[9]),
    .D(_038_),
    .X(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _094_ (
    .A1(count_reg[8]),
    .A2(_040_),
    .B1(count_reg[9]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor3_1 _095_ (
    .A(baudtick),
    .B(_043_),
    .C(_044_),
    .Y(count_next[9])
  );
  sky130_fd_sc_hd__and2_0 _096_ (
    .A(count_reg[10]),
    .B(_043_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _097_ (
    .A(count_reg[10]),
    .B(_043_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor3_1 _098_ (
    .A(baudtick),
    .B(_045_),
    .C(_046_),
    .Y(count_next[10])
  );
  sky130_fd_sc_hd__and3_1 _099_ (
    .A(count_reg[10]),
    .B(count_reg[11]),
    .C(_043_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(count_reg[11]),
    .B(_045_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor3_1 _101_ (
    .A(baudtick),
    .B(_000_),
    .C(_001_),
    .Y(count_next[11])
  );
  sky130_fd_sc_hd__and4_1 _102_ (
    .A(count_reg[10]),
    .B(count_reg[11]),
    .C(count_reg[12]),
    .D(_043_),
    .X(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(count_reg[12]),
    .B(_000_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor3_1 _104_ (
    .A(baudtick),
    .B(_002_),
    .C(_003_),
    .Y(count_next[12])
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(count_reg[13]),
    .B(_002_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a311oi_1 _106_ (
    .A1(count_reg[12]),
    .A2(count_reg[13]),
    .A3(_000_),
    .B1(_004_),
    .C1(baudtick),
    .Y(count_next[13])
  );
  sky130_fd_sc_hd__a21oi_1 _107_ (
    .A1(count_reg[13]),
    .A2(_002_),
    .B1(count_reg[14]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a311oi_1 _108_ (
    .A1(count_reg[13]),
    .A2(count_reg[14]),
    .A3(_002_),
    .B1(_005_),
    .C1(baudtick),
    .Y(count_next[14])
  );
  sky130_fd_sc_hd__and4_1 _109_ (
    .A(count_reg[13]),
    .B(count_reg[14]),
    .C(count_reg[15]),
    .D(_002_),
    .X(_006_)
  );
  sky130_fd_sc_hd__a31oi_1 _110_ (
    .A1(count_reg[13]),
    .A2(count_reg[14]),
    .A3(_002_),
    .B1(count_reg[15]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor3_1 _111_ (
    .A(baudtick),
    .B(_006_),
    .C(_007_),
    .Y(count_next[15])
  );
  sky130_fd_sc_hd__dlclkp_2 _112_ (
    .CLK(clk),
    .GATE(en),
    .GCLK(_047_)
  );
  sky130_fd_sc_hd__dfrtp_1 _113_ (
    .CLK(_047_),
    .D(count_next[0]),
    .Q(count_reg[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _114_ (
    .CLK(_047_),
    .D(count_next[1]),
    .Q(count_reg[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _115_ (
    .CLK(_047_),
    .D(count_next[2]),
    .Q(count_reg[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _116_ (
    .CLK(_047_),
    .D(count_next[3]),
    .Q(count_reg[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _117_ (
    .CLK(_047_),
    .D(count_next[4]),
    .Q(count_reg[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _118_ (
    .CLK(_047_),
    .D(count_next[5]),
    .Q(count_reg[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _119_ (
    .CLK(_047_),
    .D(count_next[6]),
    .Q(count_reg[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _120_ (
    .CLK(_047_),
    .D(count_next[7]),
    .Q(count_reg[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _121_ (
    .CLK(_047_),
    .D(count_next[8]),
    .Q(count_reg[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(_047_),
    .D(count_next[9]),
    .Q(count_reg[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(_047_),
    .D(count_next[10]),
    .Q(count_reg[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(_047_),
    .D(count_next[11]),
    .Q(count_reg[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(_047_),
    .D(count_next[12]),
    .Q(count_reg[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(_047_),
    .D(count_next[13]),
    .Q(count_reg[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(_047_),
    .D(count_next[14]),
    .Q(count_reg[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(_047_),
    .D(count_next[15]),
    .Q(count_reg[15]),
    .RESET_B(rst_n)
  );
endmodule

module UART_RX(clk, resetn, b_tick, rx, rx_done, dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire [3:0] b_next;
  wire [3:0] b_reg;
  input b_tick;
  wire b_tick;
  input clk;
  wire clk;
  wire [2:0] count_next;
  wire [2:0] count_reg;
  wire [1:0] current_state;
  output [7:0] dout;
  wire [7:0] dout;
  wire [1:0] next_state;
  input resetn;
  wire resetn;
  input rx;
  wire rx;
  output rx_done;
  wire rx_done;
  sky130_fd_sc_hd__clkinv_1 _29_ (
    .A(current_state[1]),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__and3_1 _30_ (
    .A(b_reg[1]),
    .B(b_reg[0]),
    .C(b_reg[2]),
    .X(_04_)
  );
  sky130_fd_sc_hd__and4_1 _31_ (
    .A(b_reg[1]),
    .B(b_reg[0]),
    .C(b_reg[2]),
    .D(b_reg[3]),
    .X(_05_)
  );
  sky130_fd_sc_hd__and2_0 _32_ (
    .A(b_tick),
    .B(_05_),
    .X(_06_)
  );
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(b_tick),
    .B(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor3_1 _34_ (
    .A(next_state[0]),
    .B(current_state[0]),
    .C(_07_),
    .Y(rx_done)
  );
  sky130_fd_sc_hd__nor2_1 _35_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__o21bai_1 _36_ (
    .A1(current_state[1]),
    .A2(current_state[0]),
    .B1_N(b_tick),
    .Y(_09_)
  );
  sky130_fd_sc_hd__or3b_1 _37_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .C_N(rx),
    .X(_10_)
  );
  sky130_fd_sc_hd__o311a_1 _38_ (
    .A1(next_state[0]),
    .A2(current_state[0]),
    .A3(_07_),
    .B1(_09_),
    .C1(_10_),
    .X(_02_)
  );
  sky130_fd_sc_hd__and4b_1 _39_ (
    .A_N(b_reg[3]),
    .B(b_reg[2]),
    .C(b_reg[0]),
    .D(b_reg[1]),
    .X(_11_)
  );
  sky130_fd_sc_hd__nand2b_1 _40_ (
    .A_N(b_reg[3]),
    .B(_04_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand3b_1 _41_ (
    .A_N(current_state[1]),
    .B(current_state[0]),
    .C(b_tick),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand3b_1 _42_ (
    .A_N(current_state[0]),
    .B(b_tick),
    .C(current_state[1]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__o221ai_1 _43_ (
    .A1(_11_),
    .A2(_13_),
    .B1(_14_),
    .B2(_05_),
    .C1(_10_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand2_1 _44_ (
    .A(current_state[1]),
    .B(current_state[0]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor2_1 _45_ (
    .A(_07_),
    .B(_16_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a32oi_1 _46_ (
    .A1(b_reg[3]),
    .A2(b_tick),
    .A3(_04_),
    .B1(_09_),
    .B2(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a31o_1 _47_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .A3(count_reg[2]),
    .B1(_16_),
    .X(_18_)
  );
  sky130_fd_sc_hd__a31oi_1 _48_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .A3(count_reg[2]),
    .B1(_16_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a211oi_1 _49_ (
    .A1(_06_),
    .A2(_19_),
    .B1(_17_),
    .C1(_15_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__o22ai_1 _50_ (
    .A1(_12_),
    .A2(_13_),
    .B1(_18_),
    .B2(_07_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _51_ (
    .A(count_reg[0]),
    .B(_16_),
    .Y(count_next[0])
  );
  sky130_fd_sc_hd__o211ai_1 _52_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .B1(current_state[1]),
    .C1(current_state[0]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a21oi_1 _53_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .B1(_20_),
    .Y(count_next[1])
  );
  sky130_fd_sc_hd__a21oi_1 _54_ (
    .A1(count_reg[0]),
    .A2(count_reg[1]),
    .B1(count_reg[2]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor2_1 _55_ (
    .A(_18_),
    .B(_21_),
    .Y(count_next[2])
  );
  sky130_fd_sc_hd__nor2_1 _56_ (
    .A(b_reg[0]),
    .B(_08_),
    .Y(b_next[0])
  );
  sky130_fd_sc_hd__xnor2_1 _57_ (
    .A(b_reg[1]),
    .B(b_reg[0]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nor2_1 _58_ (
    .A(_08_),
    .B(_22_),
    .Y(b_next[1])
  );
  sky130_fd_sc_hd__a21oi_1 _59_ (
    .A1(b_reg[1]),
    .A2(b_reg[0]),
    .B1(b_reg[2]),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nor3_1 _60_ (
    .A(_04_),
    .B(_08_),
    .C(_23_),
    .Y(b_next[2])
  );
  sky130_fd_sc_hd__a21oi_1 _61_ (
    .A1(current_state[1]),
    .A2(_04_),
    .B1(b_reg[3]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nor3_1 _62_ (
    .A(_05_),
    .B(_08_),
    .C(_24_),
    .Y(b_next[3])
  );
  sky130_fd_sc_hd__buf_1 _63_ (
    .A(current_state[0]),
    .X(next_state[1])
  );
  sky130_fd_sc_hd__dlclkp_2 _64_ (
    .CLK(clk),
    .GATE(_00_),
    .GCLK(_25_)
  );
  sky130_fd_sc_hd__dlclkp_1 _65_ (
    .CLK(clk),
    .GATE(_01_),
    .GCLK(_26_)
  );
  sky130_fd_sc_hd__dlclkp_1 _66_ (
    .CLK(clk),
    .GATE(_02_),
    .GCLK(_27_)
  );
  sky130_fd_sc_hd__dlclkp_1 _67_ (
    .CLK(clk),
    .GATE(_03_),
    .GCLK(_28_)
  );
  sky130_fd_sc_hd__dfrtp_1 _68_ (
    .CLK(_26_),
    .D(next_state[0]),
    .Q(current_state[0]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _69_ (
    .CLK(_26_),
    .D(next_state[1]),
    .Q(current_state[1]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _70_ (
    .CLK(_28_),
    .D(count_next[0]),
    .Q(count_reg[0]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _71_ (
    .CLK(_28_),
    .D(count_next[1]),
    .Q(count_reg[1]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _72_ (
    .CLK(_28_),
    .D(count_next[2]),
    .Q(count_reg[2]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _73_ (
    .CLK(_27_),
    .D(b_next[0]),
    .Q(b_reg[0]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _74_ (
    .CLK(_27_),
    .D(b_next[1]),
    .Q(b_reg[1]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _75_ (
    .CLK(_27_),
    .D(b_next[2]),
    .Q(b_reg[2]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _76_ (
    .CLK(_27_),
    .D(b_next[3]),
    .Q(b_reg[3]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _77_ (
    .CLK(_25_),
    .D(dout[1]),
    .Q(dout[0]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _78_ (
    .CLK(_25_),
    .D(dout[2]),
    .Q(dout[1]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _79_ (
    .CLK(_25_),
    .D(dout[3]),
    .Q(dout[2]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _80_ (
    .CLK(_25_),
    .D(dout[4]),
    .Q(dout[3]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _81_ (
    .CLK(_25_),
    .D(dout[5]),
    .Q(dout[4]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _82_ (
    .CLK(_25_),
    .D(dout[6]),
    .Q(dout[5]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _83_ (
    .CLK(_25_),
    .D(dout[7]),
    .Q(dout[6]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _84_ (
    .CLK(_25_),
    .D(rx),
    .Q(dout[7]),
    .RESET_B(resetn)
  );
endmodule

module UART_TX(clk, resetn, tx_start, b_tick, d_in, tx_done, tx);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire [3:0] b_next;
  wire [3:0] b_reg;
  input b_tick;
  wire b_tick;
  input clk;
  wire clk;
  wire [2:0] count_next;
  wire [2:0] count_reg;
  wire [1:0] current_state;
  input [7:0] d_in;
  wire [7:0] d_in;
  wire [7:0] data_next;
  wire [7:0] data_reg;
  wire [1:0] next_state;
  input resetn;
  wire resetn;
  output tx;
  wire tx;
  output tx_done;
  wire tx_done;
  wire tx_next;
  input tx_start;
  wire tx_start;
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(current_state[1]),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__and3_1 _26_ (
    .A(b_reg[1]),
    .B(b_reg[0]),
    .C(b_reg[2]),
    .X(_04_)
  );
  sky130_fd_sc_hd__and4_1 _27_ (
    .A(b_reg[1]),
    .B(b_reg[0]),
    .C(b_reg[2]),
    .D(b_reg[3]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nand3_1 _28_ (
    .A(current_state[0]),
    .B(b_tick),
    .C(_05_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__and3_1 _29_ (
    .A(count_reg[1]),
    .B(count_reg[0]),
    .C(count_reg[2]),
    .X(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _30_ (
    .A(current_state[0]),
    .B(current_state[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21oi_1 _31_ (
    .A1(current_state[1]),
    .A2(_07_),
    .B1(_06_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _32_ (
    .A(current_state[0]),
    .B(current_state[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(tx_start),
    .B(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__o21ai_0 _34_ (
    .A1(current_state[0]),
    .A2(current_state[1]),
    .B1(b_tick),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a21boi_0 _35_ (
    .A1(tx_start),
    .A2(_09_),
    .B1_N(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2b_1 _36_ (
    .A_N(_05_),
    .B(_11_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o21ai_0 _37_ (
    .A1(_07_),
    .A2(_08_),
    .B1(_05_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(_13_),
    .A2(_14_),
    .B1(_12_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__o21ai_0 _39_ (
    .A1(next_state[0]),
    .A2(_06_),
    .B1(_10_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and4b_1 _40_ (
    .A_N(current_state[0]),
    .B(current_state[1]),
    .C(b_tick),
    .D(_05_),
    .X(tx_done)
  );
  sky130_fd_sc_hd__nor2_1 _41_ (
    .A(_12_),
    .B(tx_done),
    .Y(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _42_ (
    .A0(data_reg[1]),
    .A1(d_in[0]),
    .S(_08_),
    .X(data_next[0])
  );
  sky130_fd_sc_hd__mux2_1 _43_ (
    .A0(data_reg[2]),
    .A1(d_in[1]),
    .S(_08_),
    .X(data_next[1])
  );
  sky130_fd_sc_hd__mux2_1 _44_ (
    .A0(data_reg[3]),
    .A1(d_in[2]),
    .S(_08_),
    .X(data_next[2])
  );
  sky130_fd_sc_hd__mux2_1 _45_ (
    .A0(data_reg[4]),
    .A1(d_in[3]),
    .S(_08_),
    .X(data_next[3])
  );
  sky130_fd_sc_hd__mux2_1 _46_ (
    .A0(data_reg[5]),
    .A1(d_in[4]),
    .S(_08_),
    .X(data_next[4])
  );
  sky130_fd_sc_hd__mux2_1 _47_ (
    .A0(data_reg[6]),
    .A1(d_in[5]),
    .S(_08_),
    .X(data_next[5])
  );
  sky130_fd_sc_hd__mux2_1 _48_ (
    .A0(data_reg[7]),
    .A1(d_in[6]),
    .S(_08_),
    .X(data_next[6])
  );
  sky130_fd_sc_hd__and2_0 _49_ (
    .A(d_in[7]),
    .B(_08_),
    .X(data_next[7])
  );
  sky130_fd_sc_hd__nor2_1 _50_ (
    .A(count_reg[0]),
    .B(_08_),
    .Y(count_next[0])
  );
  sky130_fd_sc_hd__o211ai_1 _51_ (
    .A1(count_reg[1]),
    .A2(count_reg[0]),
    .B1(current_state[0]),
    .C1(current_state[1]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a21oi_1 _52_ (
    .A1(count_reg[1]),
    .A2(count_reg[0]),
    .B1(_15_),
    .Y(count_next[1])
  );
  sky130_fd_sc_hd__a21oi_1 _53_ (
    .A1(count_reg[1]),
    .A2(count_reg[0]),
    .B1(count_reg[2]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor3_1 _54_ (
    .A(_07_),
    .B(_08_),
    .C(_16_),
    .Y(count_next[2])
  );
  sky130_fd_sc_hd__nand2_1 _55_ (
    .A(current_state[1]),
    .B(data_reg[0]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand2_1 _56_ (
    .A(current_state[0]),
    .B(_17_),
    .Y(tx_next)
  );
  sky130_fd_sc_hd__nor2_1 _57_ (
    .A(b_reg[0]),
    .B(_09_),
    .Y(b_next[0])
  );
  sky130_fd_sc_hd__xnor2_1 _58_ (
    .A(b_reg[1]),
    .B(b_reg[0]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _59_ (
    .A(_09_),
    .B(_18_),
    .Y(b_next[1])
  );
  sky130_fd_sc_hd__a21oi_1 _60_ (
    .A1(b_reg[1]),
    .A2(b_reg[0]),
    .B1(b_reg[2]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor3_1 _61_ (
    .A(_04_),
    .B(_09_),
    .C(_19_),
    .Y(b_next[2])
  );
  sky130_fd_sc_hd__nor2_1 _62_ (
    .A(b_reg[3]),
    .B(_04_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor3_1 _63_ (
    .A(_05_),
    .B(_09_),
    .C(_20_),
    .Y(b_next[3])
  );
  sky130_fd_sc_hd__buf_1 _64_ (
    .A(current_state[0]),
    .X(next_state[1])
  );
  sky130_fd_sc_hd__dlclkp_1 _65_ (
    .CLK(clk),
    .GATE(_00_),
    .GCLK(_21_)
  );
  sky130_fd_sc_hd__dlclkp_2 _66_ (
    .CLK(clk),
    .GATE(_01_),
    .GCLK(_22_)
  );
  sky130_fd_sc_hd__dlclkp_1 _67_ (
    .CLK(clk),
    .GATE(_02_),
    .GCLK(_23_)
  );
  sky130_fd_sc_hd__dlclkp_1 _68_ (
    .CLK(clk),
    .GATE(_03_),
    .GCLK(_24_)
  );
  sky130_fd_sc_hd__dfrtp_1 _69_ (
    .CLK(_21_),
    .D(next_state[0]),
    .Q(current_state[0]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _70_ (
    .CLK(_21_),
    .D(next_state[1]),
    .Q(current_state[1]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _71_ (
    .CLK(_24_),
    .D(b_next[0]),
    .Q(b_reg[0]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _72_ (
    .CLK(_24_),
    .D(b_next[1]),
    .Q(b_reg[1]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _73_ (
    .CLK(_24_),
    .D(b_next[2]),
    .Q(b_reg[2]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _74_ (
    .CLK(_24_),
    .D(b_next[3]),
    .Q(b_reg[3]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _75_ (
    .CLK(_23_),
    .D(count_next[0]),
    .Q(count_reg[0]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _76_ (
    .CLK(_23_),
    .D(count_next[1]),
    .Q(count_reg[1]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _77_ (
    .CLK(_23_),
    .D(count_next[2]),
    .Q(count_reg[2]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _78_ (
    .CLK(_22_),
    .D(data_next[0]),
    .Q(data_reg[0]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _79_ (
    .CLK(_22_),
    .D(data_next[1]),
    .Q(data_reg[1]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _80_ (
    .CLK(_22_),
    .D(data_next[2]),
    .Q(data_reg[2]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _81_ (
    .CLK(_22_),
    .D(data_next[3]),
    .Q(data_reg[3]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _82_ (
    .CLK(_22_),
    .D(data_next[4]),
    .Q(data_reg[4]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _83_ (
    .CLK(_22_),
    .D(data_next[5]),
    .Q(data_reg[5]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _84_ (
    .CLK(_22_),
    .D(data_next[6]),
    .Q(data_reg[6]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfrtp_1 _85_ (
    .CLK(_22_),
    .D(data_next[7]),
    .Q(data_reg[7]),
    .RESET_B(resetn)
  );
  sky130_fd_sc_hd__dfstp_2 _86_ (
    .CLK(clk),
    .D(tx_next),
    .Q(tx),
    .SET_B(resetn)
  );
endmodule
