/* Generated by Yosys 0.13 (git sha1 UNKNOWN, clang 13.0.0 -fPIC -Os) */

module LoopyGen(clk, ce, is_rendering, ain, din, read, write, is_pre_render, cycle, loopy, fine_x_scroll);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  input [2:0] ain;
  input ce;
  input clk;
  input [8:0] cycle;
  input [7:0] din;
  output [2:0] fine_x_scroll;
  input is_pre_render;
  input is_rendering;
  output [14:0] loopy;
  wire \loopy_t[0] ;
  wire \loopy_t[10] ;
  wire \loopy_t[11] ;
  wire \loopy_t[12] ;
  wire \loopy_t[13] ;
  wire \loopy_t[14] ;
  wire \loopy_t[1] ;
  wire \loopy_t[2] ;
  wire \loopy_t[3] ;
  wire \loopy_t[4] ;
  wire \loopy_t[5] ;
  wire \loopy_t[6] ;
  wire \loopy_t[7] ;
  wire \loopy_t[8] ;
  wire \loopy_t[9] ;
  wire ppu_address_latch;
  wire ppu_incr;
  input read;
  input write;
  sky130_fd_sc_hd__clkinv_1 _235_ (
    .A(is_rendering),
    .Y(_223_)
  );
  sky130_fd_sc_hd__clkinv_1 _236_ (
    .A(loopy[10]),
    .Y(_224_)
  );
  sky130_fd_sc_hd__clkinv_1 _237_ (
    .A(loopy[11]),
    .Y(_225_)
  );
  sky130_fd_sc_hd__clkinv_1 _238_ (
    .A(loopy[9]),
    .Y(_226_)
  );
  sky130_fd_sc_hd__clkinv_1 _239_ (
    .A(loopy[7]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _240_ (
    .A(loopy[6]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _241_ (
    .A(loopy[2]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _242_ (
    .A(loopy[0]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _243_ (
    .A(loopy[1]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _244_ (
    .A(\loopy_t[5] ),
    .Y(_043_)
  );
  sky130_fd_sc_hd__and4b_1 _245_ (
    .A_N(ain[1]),
    .B(ain[0]),
    .C(write),
    .D(ain[2]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand4b_1 _246_ (
    .A_N(ain[1]),
    .B(ain[0]),
    .C(write),
    .D(ain[2]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2b_1 _247_ (
    .A_N(ain[0]),
    .B(write),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(ain[2]),
    .B(ain[1]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _249_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _250_ (
    .A(_044_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor3_1 _251_ (
    .A(ain[2]),
    .B(ain[1]),
    .C(_046_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2b_1 _252_ (
    .A_N(_050_),
    .B(ce),
    .Y(_051_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _253_ (
    .A(_049_),
    .SLEEP(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _254_ (
    .A(ppu_address_latch),
    .SLEEP(_052_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nor3_1 _255_ (
    .A(ppu_address_latch),
    .B(_046_),
    .C(_047_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a211oi_1 _256_ (
    .A1(ppu_address_latch),
    .A2(_044_),
    .B1(_052_),
    .C1(_053_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__and2_0 _257_ (
    .A(ppu_address_latch),
    .B(_048_),
    .X(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(ppu_address_latch),
    .B(_048_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o21ai_0 _259_ (
    .A1(ppu_address_latch),
    .A2(_045_),
    .B1(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor2_1 _260_ (
    .A(_052_),
    .B(_056_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__o2111a_1 _261_ (
    .A1(_048_),
    .A2(_050_),
    .B1(_055_),
    .C1(_045_),
    .D1(ce),
    .X(_003_)
  );
  sky130_fd_sc_hd__nor3_1 _262_ (
    .A(ppu_address_latch),
    .B(_045_),
    .C(_051_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _263_ (
    .A(ain[2]),
    .B(ain[0]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand3_1 _264_ (
    .A(ain[1]),
    .B(read),
    .C(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21oi_1 _265_ (
    .A1(_049_),
    .A2(_058_),
    .B1(_051_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and2_0 _266_ (
    .A(ce),
    .B(_050_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(din[4]),
    .B(_045_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(din[0]),
    .B(_044_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _269_ (
    .A(_059_),
    .B(_060_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(din[5]),
    .B(_045_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(din[1]),
    .B(_044_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(_061_),
    .B(_062_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(loopy[5]),
    .B(ppu_incr),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xor2_1 _274_ (
    .A(loopy[5]),
    .B(ppu_incr),
    .X(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _275_ (
    .A(ppu_incr),
    .B(_041_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__and4b_1 _276_ (
    .A_N(ppu_incr),
    .B(loopy[2]),
    .C(loopy[0]),
    .D(loopy[1]),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand4_1 _277_ (
    .A(loopy[4]),
    .B(loopy[3]),
    .C(_064_),
    .D(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a21oi_1 _278_ (
    .A1(_063_),
    .A2(_067_),
    .B1(_039_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(loopy[8]),
    .B(loopy[7]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _280_ (
    .A(_068_),
    .SLEEP(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd__a2111oi_0 _281_ (
    .A1(_063_),
    .A2(_067_),
    .B1(_069_),
    .C1(_039_),
    .D1(_226_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__and3_1 _282_ (
    .A(loopy[10]),
    .B(loopy[11]),
    .C(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(loopy[12]),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _284_ (
    .A(write),
    .B(read),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_047_),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand3_1 _286_ (
    .A(ain[0]),
    .B(_223_),
    .C(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__xnor2_1 _287_ (
    .A(loopy[12]),
    .B(_072_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _288_ (
    .A(\loopy_t[12] ),
    .B(_054_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor4_1 _289_ (
    .A(cycle[1]),
    .B(cycle[0]),
    .C(cycle[2]),
    .D(cycle[3]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor3b_1 _290_ (
    .A(cycle[6]),
    .B(cycle[7]),
    .C_N(cycle[8]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__and2_0 _291_ (
    .A(cycle[4]),
    .B(cycle[5]),
    .X(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _292_ (
    .A(cycle[4]),
    .B(cycle[5]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__and4_1 _293_ (
    .A(is_pre_render),
    .B(_079_),
    .C(_080_),
    .D(_081_),
    .X(_083_)
  );
  sky130_fd_sc_hd__nand3b_1 _294_ (
    .A_N(cycle[2]),
    .B(cycle[0]),
    .C(cycle[1]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand4b_1 _295_ (
    .A_N(cycle[8]),
    .B(cycle[7]),
    .C(cycle[6]),
    .D(cycle[3]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor3_1 _296_ (
    .A(_082_),
    .B(_084_),
    .C(_085_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _297_ (
    .A1(_083_),
    .A2(_086_),
    .B1(is_rendering),
    .Y(_087_)
  );
  sky130_fd_sc_hd__and4_1 _298_ (
    .A(is_pre_render),
    .B(_079_),
    .C(_080_),
    .D(_081_),
    .X(_088_)
  );
  sky130_fd_sc_hd__nor2b_1 _299_ (
    .A(loopy[12]),
    .B_N(_087_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(_055_),
    .B(_076_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__and2_0 _301_ (
    .A(_055_),
    .B(_076_),
    .X(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _302_ (
    .A(loopy[12]),
    .B(_083_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(_087_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(\loopy_t[12] ),
    .B(_083_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a211o_1 _305_ (
    .A1(_093_),
    .A2(_094_),
    .B1(_089_),
    .C1(_090_),
    .X(_095_)
  );
  sky130_fd_sc_hd__o211ai_1 _306_ (
    .A1(_076_),
    .A2(_077_),
    .B1(_078_),
    .C1(_095_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(loopy[12]),
    .B(loopy[13]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand3_1 _308_ (
    .A(loopy[12]),
    .B(loopy[13]),
    .C(_072_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__xor2_1 _309_ (
    .A(loopy[13]),
    .B(_073_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(\loopy_t[13] ),
    .B(_054_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor4_1 _311_ (
    .A(_082_),
    .B(_084_),
    .C(_085_),
    .D(_096_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4_1 _312_ (
    .A(_082_),
    .B(_084_),
    .C(_085_),
    .D(_096_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _313_ (
    .A1(_088_),
    .A2(_101_),
    .B1(is_rendering),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21o_1 _314_ (
    .A1(\loopy_t[13] ),
    .A2(_088_),
    .B1(_102_),
    .X(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _315_ (
    .A1(loopy[13]),
    .A2(_093_),
    .B1(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o221ai_1 _316_ (
    .A1(_076_),
    .A2(_098_),
    .B1(_104_),
    .B2(_090_),
    .C1(_099_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xor2_1 _317_ (
    .A(loopy[14]),
    .B(_097_),
    .X(_105_)
  );
  sky130_fd_sc_hd__nand2b_1 _318_ (
    .A_N(loopy[14]),
    .B(_102_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a21o_1 _319_ (
    .A1(loopy[14]),
    .A2(_100_),
    .B1(_083_),
    .X(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(is_rendering),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21o_1 _321_ (
    .A1(\loopy_t[14] ),
    .A2(_083_),
    .B1(_108_),
    .X(_109_)
  );
  sky130_fd_sc_hd__a32oi_1 _322_ (
    .A1(_091_),
    .A2(_106_),
    .A3(_109_),
    .B1(_054_),
    .B2(\loopy_t[14] ),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o21ai_0 _323_ (
    .A1(_076_),
    .A2(_105_),
    .B1(_110_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(din[0]),
    .B(_045_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(din[3]),
    .B(_044_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_111_),
    .B(_112_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(din[1]),
    .B(_045_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(din[4]),
    .B(_044_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(_113_),
    .B(_114_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(din[2]),
    .B(_045_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(din[5]),
    .B(_044_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2_1 _332_ (
    .A(_115_),
    .B(_116_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(din[3]),
    .B(_045_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(din[6]),
    .B(_044_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(_117_),
    .B(_118_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(din[7]),
    .B(_044_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(_059_),
    .B(_119_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _338_ (
    .A0(din[2]),
    .A1(din[0]),
    .S(_050_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _339_ (
    .A0(din[3]),
    .A1(din[1]),
    .S(_050_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _340_ (
    .A(_111_),
    .B(_118_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _341_ (
    .A(_113_),
    .B(_119_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(cycle[4]),
    .B(cycle[5]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__or4b_1 _343_ (
    .A(cycle[4]),
    .B(cycle[5]),
    .C(cycle[7]),
    .D_N(cycle[6]),
    .X(_121_)
  );
  sky130_fd_sc_hd__a21oi_1 _344_ (
    .A1(cycle[8]),
    .A2(_121_),
    .B1(_084_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(loopy[0]),
    .B(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a31oi_1 _346_ (
    .A1(_079_),
    .A2(_080_),
    .A3(_120_),
    .B1(_083_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _347_ (
    .A1(\loopy_t[0] ),
    .A2(_124_),
    .B1(_123_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__and3_1 _348_ (
    .A(_079_),
    .B(_080_),
    .C(_120_),
    .X(_126_)
  );
  sky130_fd_sc_hd__a41oi_1 _349_ (
    .A1(is_pre_render),
    .A2(_079_),
    .A3(_080_),
    .A4(_081_),
    .B1(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _350_ (
    .A(_088_),
    .SLEEP(_126_),
    .X(_128_)
  );
  sky130_fd_sc_hd__o21ai_0 _351_ (
    .A1(_122_),
    .A2(_128_),
    .B1(is_rendering),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a22o_1 _352_ (
    .A1(is_rendering),
    .A2(_125_),
    .B1(_129_),
    .B2(_041_),
    .X(_130_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _353_ (
    .A(ppu_incr),
    .SLEEP(loopy[0]),
    .X(_131_)
  );
  sky130_fd_sc_hd__nor3_1 _354_ (
    .A(_065_),
    .B(_076_),
    .C(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _355_ (
    .A1(din[0]),
    .A2(_054_),
    .B1(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o21ai_0 _356_ (
    .A1(_090_),
    .A2(_130_),
    .B1(_133_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _357_ (
    .A(is_rendering),
    .B(_042_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a2111oi_0 _358_ (
    .A1(cycle[8]),
    .A2(_121_),
    .B1(_084_),
    .C1(_042_),
    .D1(_041_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__xnor2_1 _359_ (
    .A(_042_),
    .B(_123_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _360_ (
    .A(\loopy_t[1] ),
    .B(_127_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a211oi_1 _361_ (
    .A1(_127_),
    .A2(_136_),
    .B1(_137_),
    .C1(_223_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__o21ai_0 _362_ (
    .A1(_134_),
    .A2(_138_),
    .B1(_091_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xnor2_1 _363_ (
    .A(loopy[1]),
    .B(_065_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _364_ (
    .A(din[1]),
    .B(_054_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o211ai_1 _365_ (
    .A1(_076_),
    .A2(_140_),
    .B1(_141_),
    .C1(_139_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(loopy[2]),
    .B(_135_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__xnor2_1 _367_ (
    .A(_040_),
    .B(_135_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor2_1 _368_ (
    .A(_128_),
    .B(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o21ai_0 _369_ (
    .A1(\loopy_t[2] ),
    .A2(_127_),
    .B1(is_rendering),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o22ai_1 _370_ (
    .A1(is_rendering),
    .A2(_040_),
    .B1(_144_),
    .B2(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a21oi_1 _371_ (
    .A1(loopy[1]),
    .A2(_065_),
    .B1(loopy[2]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor3_1 _372_ (
    .A(_066_),
    .B(_076_),
    .C(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a221o_1 _373_ (
    .A1(din[2]),
    .A2(_054_),
    .B1(_091_),
    .B2(_146_),
    .C1(_148_),
    .X(_023_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _374_ (
    .A(loopy[3]),
    .SLEEP(is_rendering),
    .X(_149_)
  );
  sky130_fd_sc_hd__xor2_1 _375_ (
    .A(loopy[3]),
    .B(_142_),
    .X(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _376_ (
    .A1(\loopy_t[3] ),
    .A2(_127_),
    .B1(is_rendering),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21oi_1 _377_ (
    .A1(_127_),
    .A2(_150_),
    .B1(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _378_ (
    .A1(_149_),
    .A2(_152_),
    .B1(_091_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(din[3]),
    .B(_054_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a21oi_1 _380_ (
    .A1(loopy[3]),
    .A2(_066_),
    .B1(_076_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21ai_0 _381_ (
    .A1(loopy[3]),
    .A2(_066_),
    .B1(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand3_1 _382_ (
    .A(_153_),
    .B(_154_),
    .C(_156_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a31o_1 _383_ (
    .A1(loopy[3]),
    .A2(loopy[2]),
    .A3(_135_),
    .B1(loopy[4]),
    .X(_157_)
  );
  sky130_fd_sc_hd__nand4_1 _384_ (
    .A(loopy[4]),
    .B(loopy[3]),
    .C(loopy[2]),
    .D(_135_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _385_ (
    .A(_157_),
    .B(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__o21ai_0 _386_ (
    .A1(\loopy_t[4] ),
    .A2(_127_),
    .B1(is_rendering),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _387_ (
    .A1(_127_),
    .A2(_159_),
    .B1(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a21oi_1 _388_ (
    .A1(_223_),
    .A2(loopy[4]),
    .B1(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a21oi_1 _389_ (
    .A1(loopy[3]),
    .A2(_066_),
    .B1(loopy[4]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a311oi_1 _390_ (
    .A1(loopy[4]),
    .A2(loopy[3]),
    .A3(_066_),
    .B1(_076_),
    .C1(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a21oi_1 _391_ (
    .A1(din[4]),
    .A2(_054_),
    .B1(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _392_ (
    .A1(_090_),
    .A2(_162_),
    .B1(_165_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _393_ (
    .A1(is_rendering),
    .A2(_107_),
    .B1(loopy[5]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a32oi_1 _394_ (
    .A1(loopy[5]),
    .A2(loopy[14]),
    .A3(_100_),
    .B1(_083_),
    .B2(_043_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _395_ (
    .A(is_rendering),
    .SLEEP(_167_),
    .X(_168_)
  );
  sky130_fd_sc_hd__nor3_1 _396_ (
    .A(_090_),
    .B(_166_),
    .C(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a31oi_1 _397_ (
    .A1(loopy[4]),
    .A2(loopy[3]),
    .A3(_066_),
    .B1(_064_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _398_ (
    .A(_076_),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a221o_1 _399_ (
    .A1(din[5]),
    .A2(_054_),
    .B1(_067_),
    .B2(_171_),
    .C1(_169_),
    .X(_030_)
  );
  sky130_fd_sc_hd__a31oi_1 _400_ (
    .A1(loopy[5]),
    .A2(loopy[14]),
    .A3(_100_),
    .B1(loopy[6]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__and3_1 _401_ (
    .A(loopy[8]),
    .B(loopy[7]),
    .C(loopy[5]),
    .X(_173_)
  );
  sky130_fd_sc_hd__and3_1 _402_ (
    .A(loopy[9]),
    .B(_039_),
    .C(_173_),
    .X(_174_)
  );
  sky130_fd_sc_hd__nand4_1 _403_ (
    .A(loopy[6]),
    .B(loopy[5]),
    .C(loopy[14]),
    .D(_101_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand3_1 _404_ (
    .A(loopy[14]),
    .B(_101_),
    .C(_174_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__a31oi_1 _405_ (
    .A1(loopy[14]),
    .A2(_101_),
    .A3(_174_),
    .B1(_088_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(_175_),
    .B(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__o21ai_0 _407_ (
    .A1(_172_),
    .A2(_178_),
    .B1(is_rendering),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a21oi_1 _408_ (
    .A1(\loopy_t[6] ),
    .A2(_088_),
    .B1(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__o21ai_0 _409_ (
    .A1(is_rendering),
    .A2(loopy[6]),
    .B1(_091_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a311oi_1 _410_ (
    .A1(_039_),
    .A2(_063_),
    .A3(_067_),
    .B1(_068_),
    .C1(_076_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a21oi_1 _411_ (
    .A1(din[6]),
    .A2(_054_),
    .B1(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__o21ai_0 _412_ (
    .A1(_180_),
    .A2(_181_),
    .B1(_183_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xnor2_1 _413_ (
    .A(loopy[7]),
    .B(_175_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand2_1 _414_ (
    .A(\loopy_t[7] ),
    .B(_083_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _415_ (
    .A(is_rendering),
    .B(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a21oi_1 _416_ (
    .A1(_177_),
    .A2(_184_),
    .B1(_186_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__o21ai_0 _417_ (
    .A1(is_rendering),
    .A2(loopy[7]),
    .B1(_091_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__xnor2_1 _418_ (
    .A(loopy[7]),
    .B(_068_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _419_ (
    .A(_076_),
    .B(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__a21oi_1 _420_ (
    .A1(din[7]),
    .A2(_054_),
    .B1(_190_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__o21ai_0 _421_ (
    .A1(_187_),
    .A2(_188_),
    .B1(_191_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand4_1 _422_ (
    .A(loopy[6]),
    .B(loopy[14]),
    .C(_101_),
    .D(_173_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(_177_),
    .B(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _424_ (
    .A(is_rendering),
    .B(_193_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand2_1 _425_ (
    .A(\loopy_t[8] ),
    .B(_088_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__o31ai_1 _426_ (
    .A1(_038_),
    .A2(_175_),
    .A3(_193_),
    .B1(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a22oi_1 _427_ (
    .A1(loopy[8]),
    .A2(_194_),
    .B1(_196_),
    .B2(is_rendering),
    .Y(_197_)
  );
  sky130_fd_sc_hd__a21oi_1 _428_ (
    .A1(loopy[7]),
    .A2(_068_),
    .B1(loopy[8]),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor3_1 _429_ (
    .A(_070_),
    .B(_076_),
    .C(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a21oi_1 _430_ (
    .A1(\loopy_t[8] ),
    .A2(_054_),
    .B1(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__o21ai_0 _431_ (
    .A1(_090_),
    .A2(_197_),
    .B1(_200_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xnor2_1 _432_ (
    .A(loopy[9]),
    .B(_192_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(\loopy_t[9] ),
    .B(_083_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nand2_1 _434_ (
    .A(is_rendering),
    .B(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__a21oi_1 _435_ (
    .A1(_177_),
    .A2(_201_),
    .B1(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__o21ai_0 _436_ (
    .A1(is_rendering),
    .A2(loopy[9]),
    .B1(_091_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nor2_1 _437_ (
    .A(_071_),
    .B(_076_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21a_1 _438_ (
    .A1(loopy[9]),
    .A2(_070_),
    .B1(_206_),
    .X(_207_)
  );
  sky130_fd_sc_hd__a21oi_1 _439_ (
    .A1(\loopy_t[9] ),
    .A2(_054_),
    .B1(_207_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o21ai_0 _440_ (
    .A1(_204_),
    .A2(_205_),
    .B1(_208_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xnor2_1 _441_ (
    .A(loopy[11]),
    .B(_176_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__o21ai_0 _442_ (
    .A1(_088_),
    .A2(_209_),
    .B1(is_rendering),
    .Y(_210_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _443_ (
    .A(_088_),
    .SLEEP(\loopy_t[11] ),
    .X(_211_)
  );
  sky130_fd_sc_hd__o22ai_1 _444_ (
    .A1(is_rendering),
    .A2(_225_),
    .B1(_210_),
    .B2(_211_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__a21oi_1 _445_ (
    .A1(loopy[10]),
    .A2(_071_),
    .B1(loopy[11]),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor3_1 _446_ (
    .A(_072_),
    .B(_076_),
    .C(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__a221o_1 _447_ (
    .A1(\loopy_t[11] ),
    .A2(_054_),
    .B1(_091_),
    .B2(_212_),
    .C1(_214_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _448_ (
    .A(_061_),
    .B(_112_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _449_ (
    .A(din[6]),
    .B(_045_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(_114_),
    .B(_215_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _451_ (
    .A(din[7]),
    .B(_045_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand2_1 _452_ (
    .A(_116_),
    .B(_216_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xnor2_1 _453_ (
    .A(loopy[10]),
    .B(_158_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__o21ai_0 _454_ (
    .A1(_128_),
    .A2(_217_),
    .B1(is_rendering),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nor2_1 _455_ (
    .A(\loopy_t[10] ),
    .B(_127_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o22ai_1 _456_ (
    .A1(is_rendering),
    .A2(_224_),
    .B1(_218_),
    .B2(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__xnor2_1 _457_ (
    .A(loopy[10]),
    .B(_071_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nor2_1 _458_ (
    .A(_076_),
    .B(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__a221o_1 _459_ (
    .A1(\loopy_t[10] ),
    .A2(_054_),
    .B1(_091_),
    .B2(_220_),
    .C1(_222_),
    .X(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _460_ (
    .A(ppu_address_latch),
    .B(_049_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__and2_0 _461_ (
    .A(din[2]),
    .B(_044_),
    .X(_037_)
  );
  sky130_fd_sc_hd__dfxtp_1 _462_ (
    .CLK(_229_),
    .D(_037_),
    .Q(\loopy_t[14] )
  );
  sky130_fd_sc_hd__dfxtp_1 _463_ (
    .CLK(_229_),
    .D(_018_),
    .Q(\loopy_t[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _464_ (
    .CLK(_229_),
    .D(_019_),
    .Q(\loopy_t[9] )
  );
  sky130_fd_sc_hd__dfxtp_1 _465_ (
    .CLK(_229_),
    .D(_010_),
    .Q(\loopy_t[12] )
  );
  sky130_fd_sc_hd__dfxtp_1 _466_ (
    .CLK(_229_),
    .D(_011_),
    .Q(\loopy_t[13] )
  );
  sky130_fd_sc_hd__dfxtp_1 _467_ (
    .CLK(_231_),
    .D(din[0]),
    .Q(fine_x_scroll[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _468_ (
    .CLK(_231_),
    .D(din[1]),
    .Q(fine_x_scroll[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _469_ (
    .CLK(_231_),
    .D(din[2]),
    .Q(fine_x_scroll[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _470_ (
    .CLK(_230_),
    .D(_017_),
    .Q(\loopy_t[10] )
  );
  sky130_fd_sc_hd__dfxtp_1 _471_ (
    .CLK(_230_),
    .D(_020_),
    .Q(\loopy_t[11] )
  );
  sky130_fd_sc_hd__dfxtp_1 _472_ (
    .CLK(_233_),
    .D(din[2]),
    .Q(ppu_incr)
  );
  sky130_fd_sc_hd__dfxtp_1 _473_ (
    .CLK(_234_),
    .D(_021_),
    .Q(loopy[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _474_ (
    .CLK(_234_),
    .D(_022_),
    .Q(loopy[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _475_ (
    .CLK(_234_),
    .D(_023_),
    .Q(loopy[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _476_ (
    .CLK(_234_),
    .D(_024_),
    .Q(loopy[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _477_ (
    .CLK(_234_),
    .D(_025_),
    .Q(loopy[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _478_ (
    .CLK(_234_),
    .D(_030_),
    .Q(loopy[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _479_ (
    .CLK(_234_),
    .D(_031_),
    .Q(loopy[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _480_ (
    .CLK(_234_),
    .D(_032_),
    .Q(loopy[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _481_ (
    .CLK(_234_),
    .D(_033_),
    .Q(loopy[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _482_ (
    .CLK(_234_),
    .D(_034_),
    .Q(loopy[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _483_ (
    .CLK(_234_),
    .D(_035_),
    .Q(loopy[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _484_ (
    .CLK(_234_),
    .D(_026_),
    .Q(loopy[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _485_ (
    .CLK(_234_),
    .D(_007_),
    .Q(loopy[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _486_ (
    .CLK(_234_),
    .D(_008_),
    .Q(loopy[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _487_ (
    .CLK(_234_),
    .D(_009_),
    .Q(loopy[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _488_ (
    .CLK(_232_),
    .D(_036_),
    .Q(ppu_address_latch)
  );
  sky130_fd_sc_hd__dfxtp_1 _489_ (
    .CLK(_228_),
    .D(_012_),
    .Q(\loopy_t[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _490_ (
    .CLK(_228_),
    .D(_013_),
    .Q(\loopy_t[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _491_ (
    .CLK(_228_),
    .D(_014_),
    .Q(\loopy_t[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _492_ (
    .CLK(_228_),
    .D(_015_),
    .Q(\loopy_t[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _493_ (
    .CLK(_228_),
    .D(_016_),
    .Q(\loopy_t[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _494_ (
    .CLK(_227_),
    .D(_027_),
    .Q(\loopy_t[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _495_ (
    .CLK(_227_),
    .D(_028_),
    .Q(\loopy_t[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _496_ (
    .CLK(_227_),
    .D(_029_),
    .Q(\loopy_t[7] )
  );
  sky130_fd_sc_hd__dlclkp_1 _497_ (
    .CLK(clk),
    .GATE(_000_),
    .GCLK(_227_)
  );
  sky130_fd_sc_hd__dlclkp_2 _498_ (
    .CLK(clk),
    .GATE(_001_),
    .GCLK(_228_)
  );
  sky130_fd_sc_hd__dlclkp_2 _499_ (
    .CLK(clk),
    .GATE(_002_),
    .GCLK(_229_)
  );
  sky130_fd_sc_hd__dlclkp_1 _500_ (
    .CLK(clk),
    .GATE(_003_),
    .GCLK(_230_)
  );
  sky130_fd_sc_hd__dlclkp_1 _501_ (
    .CLK(clk),
    .GATE(_004_),
    .GCLK(_231_)
  );
  sky130_fd_sc_hd__dlclkp_1 _502_ (
    .CLK(clk),
    .GATE(_005_),
    .GCLK(_232_)
  );
  sky130_fd_sc_hd__dlclkp_1 _503_ (
    .CLK(clk),
    .GATE(_006_),
    .GCLK(_233_)
  );
  sky130_fd_sc_hd__dlclkp_2 _504_ (
    .CLK(clk),
    .GATE(ce),
    .GCLK(_234_)
  );
endmodule
