/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module LoopyGen(clk, ce, is_rendering, ain, din, read, write, is_pre_render, cycle, loopy, fine_x_scroll);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  input [2:0] ain;
  input ce;
  input clk;
  input [8:0] cycle;
  input [7:0] din;
  output [2:0] fine_x_scroll;
  input is_pre_render;
  input is_rendering;
  output [14:0] loopy;
  wire \loopy_t[0] ;
  wire \loopy_t[10] ;
  wire \loopy_t[11] ;
  wire \loopy_t[12] ;
  wire \loopy_t[13] ;
  wire \loopy_t[14] ;
  wire \loopy_t[1] ;
  wire \loopy_t[2] ;
  wire \loopy_t[3] ;
  wire \loopy_t[4] ;
  wire \loopy_t[5] ;
  wire \loopy_t[6] ;
  wire \loopy_t[7] ;
  wire \loopy_t[8] ;
  wire \loopy_t[9] ;
  wire \loopy_v[0] ;
  wire \loopy_v[10] ;
  wire \loopy_v[11] ;
  wire \loopy_v[12] ;
  wire \loopy_v[13] ;
  wire \loopy_v[14] ;
  wire \loopy_v[1] ;
  wire \loopy_v[2] ;
  wire \loopy_v[3] ;
  wire \loopy_v[4] ;
  wire \loopy_v[5] ;
  wire \loopy_v[6] ;
  wire \loopy_v[7] ;
  wire \loopy_v[8] ;
  wire \loopy_v[9] ;
  wire \loopy_x[0] ;
  wire \loopy_x[1] ;
  wire \loopy_x[2] ;
  wire ppu_address_latch;
  wire ppu_incr;
  input read;
  input write;
  sky130_fd_sc_hd__clkinv_1 _276_ (
    .A(loopy[12]),
    .Y(_272_)
  );
  sky130_fd_sc_hd__clkinv_1 _277_ (
    .A(is_rendering),
    .Y(_273_)
  );
  sky130_fd_sc_hd__clkinv_1 _278_ (
    .A(ppu_incr),
    .Y(_274_)
  );
  sky130_fd_sc_hd__clkinv_1 _279_ (
    .A(loopy[5]),
    .Y(_275_)
  );
  sky130_fd_sc_hd__clkinv_1 _280_ (
    .A(loopy[4]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _281_ (
    .A(loopy[3]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _282_ (
    .A(loopy[2]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _283_ (
    .A(loopy[0]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _284_ (
    .A(loopy[1]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _285_ (
    .A(din[0]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _286_ (
    .A(\loopy_t[12] ),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _287_ (
    .A(\loopy_t[13] ),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _288_ (
    .A(din[1]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _289_ (
    .A(din[5]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _290_ (
    .A(\loopy_t[7] ),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(loopy[11]),
    .B(ce),
    .Y(_046_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _292_ (
    .A(loopy[11]),
    .SLEEP(is_rendering),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand3_1 _293_ (
    .A(loopy[8]),
    .B(loopy[7]),
    .C(loopy[9]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand3b_1 _294_ (
    .A_N(cycle[2]),
    .B(cycle[0]),
    .C(cycle[1]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(cycle[5]),
    .B(cycle[4]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand4b_1 _296_ (
    .A_N(cycle[8]),
    .B(cycle[6]),
    .C(cycle[7]),
    .D(cycle[3]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor3_1 _297_ (
    .A(_049_),
    .B(_050_),
    .C(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__and3_1 _298_ (
    .A(loopy[13]),
    .B(loopy[12]),
    .C(_052_),
    .X(_053_)
  );
  sky130_fd_sc_hd__nor4_1 _299_ (
    .A(_272_),
    .B(_049_),
    .C(_050_),
    .D(_051_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__and4_1 _300_ (
    .A(loopy[13]),
    .B(loopy[14]),
    .C(loopy[5]),
    .D(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__nand4_1 _301_ (
    .A(loopy[13]),
    .B(loopy[14]),
    .C(loopy[5]),
    .D(_054_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor3_1 _302_ (
    .A(loopy[6]),
    .B(_048_),
    .C(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _303_ (
    .A(loopy[11]),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand3_1 _304_ (
    .A(cycle[5]),
    .B(cycle[4]),
    .C(is_pre_render),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _305_ (
    .A(cycle[7]),
    .B(cycle[6]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _306_ (
    .A(cycle[1]),
    .B(cycle[0]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _307_ (
    .A(cycle[2]),
    .B(cycle[3]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand4_1 _308_ (
    .A(cycle[8]),
    .B(_060_),
    .C(_061_),
    .D(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2_1 _309_ (
    .A(_059_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor3_1 _310_ (
    .A(cycle[2]),
    .B(cycle[3]),
    .C(cycle[7]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand3_1 _311_ (
    .A(cycle[8]),
    .B(_061_),
    .C(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor3_1 _312_ (
    .A(cycle[6]),
    .B(_059_),
    .C(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__or3_1 _313_ (
    .A(cycle[6]),
    .B(_059_),
    .C(_066_),
    .X(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _314_ (
    .A(\loopy_t[11] ),
    .B(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a211oi_1 _315_ (
    .A1(_058_),
    .A2(_068_),
    .B1(_069_),
    .C1(_273_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _316_ (
    .A(ain[1]),
    .SLEEP(ain[0]),
    .X(_071_)
  );
  sky130_fd_sc_hd__and3_1 _317_ (
    .A(ain[2]),
    .B(write),
    .C(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nand3_1 _318_ (
    .A(ain[2]),
    .B(write),
    .C(_071_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__and2_0 _319_ (
    .A(ppu_address_latch),
    .B(_072_),
    .X(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(ain[0]),
    .B(ain[2]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o21ai_0 _321_ (
    .A1(write),
    .A2(read),
    .B1(ain[1]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor3_1 _322_ (
    .A(is_rendering),
    .B(_075_),
    .C(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__or3_1 _323_ (
    .A(is_rendering),
    .B(_075_),
    .C(_076_),
    .X(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _324_ (
    .A(_074_),
    .B(_077_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o21ai_0 _325_ (
    .A1(_047_),
    .A2(_070_),
    .B1(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_274_),
    .B(loopy[0]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor3_1 _327_ (
    .A(_037_),
    .B(_039_),
    .C(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand4b_1 _328_ (
    .A_N(ppu_incr),
    .B(loopy[2]),
    .C(loopy[0]),
    .D(loopy[1]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(ppu_incr),
    .B(loopy[5]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__o41ai_1 _330_ (
    .A1(_275_),
    .A2(_035_),
    .A3(_036_),
    .A4(_083_),
    .B1(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(loopy[6]),
    .B(_085_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__and4_1 _332_ (
    .A(loopy[8]),
    .B(loopy[7]),
    .C(loopy[6]),
    .D(_085_),
    .X(_087_)
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(_048_),
    .B(_086_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__and3_1 _334_ (
    .A(loopy[9]),
    .B(loopy[10]),
    .C(_087_),
    .X(_089_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(loopy[11]),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o211ai_1 _336_ (
    .A1(loopy[11]),
    .A2(_089_),
    .B1(_090_),
    .C1(_077_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(\loopy_t[11] ),
    .B(_074_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(ppu_address_latch),
    .B(_073_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a41oi_1 _339_ (
    .A1(ce),
    .A2(_080_),
    .A3(_091_),
    .A4(_092_),
    .B1(_046_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2b_1 _340_ (
    .A_N(ain[1]),
    .B(write),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor3_1 _341_ (
    .A(ain[0]),
    .B(ain[2]),
    .C(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(ce),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(_075_),
    .B(_094_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _344_ (
    .A(_075_),
    .SLEEP(_094_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(ce),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(ce),
    .B(_093_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(_096_),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__mux2i_1 _348_ (
    .A0(din[2]),
    .A1(din[0]),
    .S(_095_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(\loopy_t[10] ),
    .B(_101_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a21oi_1 _350_ (
    .A1(_101_),
    .A2(_102_),
    .B1(_103_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(loopy[12]),
    .B(ce),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand3_1 _352_ (
    .A(loopy[11]),
    .B(loopy[12]),
    .C(_089_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a21oi_1 _353_ (
    .A1(loopy[11]),
    .A2(_089_),
    .B1(loopy[12]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(_078_),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _355_ (
    .A(_105_),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o21ai_0 _356_ (
    .A1(_052_),
    .A2(_064_),
    .B1(is_rendering),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _357_ (
    .A(\loopy_t[12] ),
    .B(_067_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o21a_1 _358_ (
    .A1(_054_),
    .A2(_067_),
    .B1(is_rendering),
    .X(_111_)
  );
  sky130_fd_sc_hd__a22oi_1 _359_ (
    .A1(_272_),
    .A2(_109_),
    .B1(_110_),
    .B2(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _360_ (
    .A(_079_),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(\loopy_t[12] ),
    .B(_074_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a41oi_1 _362_ (
    .A1(ce),
    .A2(_108_),
    .A3(_113_),
    .A4(_114_),
    .B1(_104_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand4_1 _363_ (
    .A(loopy[11]),
    .B(loopy[13]),
    .C(loopy[12]),
    .D(_089_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2b_1 _364_ (
    .A_N(loopy[13]),
    .B(_105_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21ai_0 _365_ (
    .A1(loopy[13]),
    .A2(_111_),
    .B1(_079_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__o21ai_0 _366_ (
    .A1(_053_),
    .A2(_064_),
    .B1(is_rendering),
    .Y(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _367_ (
    .A1(\loopy_t[13] ),
    .A2(_064_),
    .B1(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _368_ (
    .A(\loopy_t[13] ),
    .B(_074_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o211ai_1 _369_ (
    .A1(_117_),
    .A2(_119_),
    .B1(_120_),
    .C1(ce),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a31oi_1 _370_ (
    .A1(_077_),
    .A2(_115_),
    .A3(_116_),
    .B1(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(loopy[13]),
    .B(ce),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor2_1 _372_ (
    .A(_122_),
    .B(_123_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _373_ (
    .A(loopy[14]),
    .B(ce),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xnor2_1 _374_ (
    .A(loopy[14]),
    .B(_115_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _375_ (
    .A(_077_),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(\loopy_t[14] ),
    .B(_067_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _377_ (
    .A(is_rendering),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _378_ (
    .A1(loopy[14]),
    .A2(_053_),
    .B1(_064_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2b_1 _379_ (
    .A_N(loopy[14]),
    .B(_118_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o211ai_1 _380_ (
    .A1(_128_),
    .A2(_129_),
    .B1(_130_),
    .C1(_079_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _381_ (
    .A(\loopy_t[14] ),
    .B(_074_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a41oi_1 _382_ (
    .A1(ce),
    .A2(_126_),
    .A3(_131_),
    .A4(_132_),
    .B1(_124_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor3b_1 _383_ (
    .A(_098_),
    .B(ppu_address_latch),
    .C_N(ce),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(fine_x_scroll[0]),
    .B(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _385_ (
    .A1(_040_),
    .A2(_133_),
    .B1(_134_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _386_ (
    .A(fine_x_scroll[1]),
    .B(_133_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21oi_1 _387_ (
    .A1(_043_),
    .A2(_133_),
    .B1(_135_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _388_ (
    .A0(fine_x_scroll[2]),
    .A1(din[2]),
    .S(_133_),
    .X(_032_)
  );
  sky130_fd_sc_hd__o21ai_0 _389_ (
    .A1(ppu_address_latch),
    .A2(_098_),
    .B1(ce),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o21bai_1 _390_ (
    .A1(_093_),
    .A2(_097_),
    .B1_N(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _391_ (
    .A(ppu_address_latch),
    .B(_097_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__and3_1 _392_ (
    .A(ppu_address_latch),
    .B(ce),
    .C(_097_),
    .X(_139_)
  );
  sky130_fd_sc_hd__nand3_1 _393_ (
    .A(ppu_address_latch),
    .B(ce),
    .C(_097_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o22ai_1 _394_ (
    .A1(din[4]),
    .A2(_100_),
    .B1(_140_),
    .B2(din[0]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21oi_1 _395_ (
    .A1(_041_),
    .A2(_137_),
    .B1(_141_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o22ai_1 _396_ (
    .A1(din[5]),
    .A2(_100_),
    .B1(_140_),
    .B2(din[1]),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _397_ (
    .A1(_042_),
    .A2(_137_),
    .B1(_142_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _398_ (
    .A(_074_),
    .B(_097_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o211ai_1 _399_ (
    .A1(_074_),
    .A2(_097_),
    .B1(_138_),
    .C1(ce),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand3_1 _400_ (
    .A(ce),
    .B(din[0]),
    .C(_074_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a22oi_1 _401_ (
    .A1(din[3]),
    .A2(_133_),
    .B1(_144_),
    .B2(\loopy_t[0] ),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _402_ (
    .A(_145_),
    .B(_146_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(\loopy_t[1] ),
    .B(_144_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _404_ (
    .A(din[1]),
    .B(_074_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a32oi_1 _405_ (
    .A1(ce),
    .A2(din[1]),
    .A3(_074_),
    .B1(_133_),
    .B2(din[4]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(_147_),
    .B(_149_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(din[2]),
    .B(_074_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(_099_),
    .B(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a221o_1 _409_ (
    .A1(din[5]),
    .A2(_133_),
    .B1(_144_),
    .B2(\loopy_t[2] ),
    .C1(_151_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _410_ (
    .A(din[3]),
    .B(_074_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _411_ (
    .A(_099_),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a221o_1 _412_ (
    .A1(din[6]),
    .A2(_133_),
    .B1(_144_),
    .B2(\loopy_t[3] ),
    .C1(_153_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _413_ (
    .A(din[4]),
    .B(_074_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _414_ (
    .A(_099_),
    .B(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a221o_1 _415_ (
    .A1(din[7]),
    .A2(_133_),
    .B1(_144_),
    .B2(\loopy_t[4] ),
    .C1(_155_),
    .X(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _416_ (
    .A(loopy[0]),
    .B(ce),
    .Y(_156_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _417_ (
    .A(cycle[5]),
    .SLEEP(cycle[4]),
    .X(_157_)
  );
  sky130_fd_sc_hd__or4b_1 _418_ (
    .A(cycle[5]),
    .B(cycle[4]),
    .C(cycle[7]),
    .D_N(cycle[6]),
    .X(_158_)
  );
  sky130_fd_sc_hd__a21oi_1 _419_ (
    .A1(cycle[8]),
    .A2(_158_),
    .B1(_049_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a211oi_1 _420_ (
    .A1(cycle[8]),
    .A2(_158_),
    .B1(_049_),
    .C1(_038_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a211o_1 _421_ (
    .A1(_059_),
    .A2(_157_),
    .B1(_066_),
    .C1(cycle[6]),
    .X(_161_)
  );
  sky130_fd_sc_hd__a211oi_1 _422_ (
    .A1(_059_),
    .A2(_157_),
    .B1(_066_),
    .C1(cycle[6]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(\loopy_t[0] ),
    .B(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o211ai_1 _424_ (
    .A1(_160_),
    .A2(_162_),
    .B1(_163_),
    .C1(is_rendering),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2_1 _425_ (
    .A(_159_),
    .B(_162_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _426_ (
    .A(_273_),
    .B(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o211ai_1 _427_ (
    .A1(loopy[0]),
    .A2(_166_),
    .B1(_164_),
    .C1(_079_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nand2_1 _428_ (
    .A(ppu_incr),
    .B(_038_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__a32oi_1 _429_ (
    .A1(_077_),
    .A2(_081_),
    .A3(_168_),
    .B1(_074_),
    .B2(din[0]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__a31oi_1 _430_ (
    .A1(ce),
    .A2(_167_),
    .A3(_169_),
    .B1(_156_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _431_ (
    .A(loopy[1]),
    .B(ce),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _432_ (
    .A(loopy[1]),
    .B(_160_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__xnor2_1 _433_ (
    .A(loopy[1]),
    .B(_160_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__o21ai_0 _434_ (
    .A1(_162_),
    .A2(_172_),
    .B1(is_rendering),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a21oi_1 _435_ (
    .A1(\loopy_t[1] ),
    .A2(_162_),
    .B1(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__o21ai_0 _436_ (
    .A1(is_rendering),
    .A2(loopy[1]),
    .B1(_079_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__xnor2_1 _437_ (
    .A(loopy[1]),
    .B(_081_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__o211ai_1 _438_ (
    .A1(_174_),
    .A2(_175_),
    .B1(ce),
    .C1(_148_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a21oi_1 _439_ (
    .A1(_077_),
    .A2(_176_),
    .B1(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nor2_1 _440_ (
    .A(_170_),
    .B(_178_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _441_ (
    .A(loopy[2]),
    .B(ce),
    .Y(_179_)
  );
  sky130_fd_sc_hd__xnor2_1 _442_ (
    .A(loopy[2]),
    .B(_171_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _443_ (
    .A(_162_),
    .B(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__o21ai_0 _444_ (
    .A1(\loopy_t[2] ),
    .A2(_161_),
    .B1(is_rendering),
    .Y(_182_)
  );
  sky130_fd_sc_hd__o22ai_1 _445_ (
    .A1(is_rendering),
    .A2(_037_),
    .B1(_181_),
    .B2(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a31oi_1 _446_ (
    .A1(_274_),
    .A2(loopy[0]),
    .A3(loopy[1]),
    .B1(loopy[2]),
    .Y(_184_)
  );
  sky130_fd_sc_hd__o311ai_0 _447_ (
    .A1(_078_),
    .A2(_082_),
    .A3(_184_),
    .B1(_150_),
    .C1(ce),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _448_ (
    .A1(_079_),
    .A2(_183_),
    .B1(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nor2_1 _449_ (
    .A(_179_),
    .B(_186_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _450_ (
    .A(loopy[3]),
    .B(ce),
    .Y(_187_)
  );
  sky130_fd_sc_hd__o21ai_0 _451_ (
    .A1(_037_),
    .A2(_171_),
    .B1(_036_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand4_1 _452_ (
    .A(loopy[3]),
    .B(loopy[2]),
    .C(loopy[1]),
    .D(_160_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a21oi_1 _453_ (
    .A1(_188_),
    .A2(_189_),
    .B1(_162_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o21ai_0 _454_ (
    .A1(\loopy_t[3] ),
    .A2(_161_),
    .B1(is_rendering),
    .Y(_191_)
  );
  sky130_fd_sc_hd__o22ai_1 _455_ (
    .A1(is_rendering),
    .A2(_036_),
    .B1(_190_),
    .B2(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _456_ (
    .A(_079_),
    .B(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _457_ (
    .A(_036_),
    .B(_083_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o211ai_1 _458_ (
    .A1(_036_),
    .A2(_083_),
    .B1(_194_),
    .C1(_077_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__a41oi_1 _459_ (
    .A1(ce),
    .A2(_152_),
    .A3(_193_),
    .A4(_195_),
    .B1(_187_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _460_ (
    .A(loopy[4]),
    .B(ce),
    .Y(_196_)
  );
  sky130_fd_sc_hd__o21ai_0 _461_ (
    .A1(_036_),
    .A2(_083_),
    .B1(_035_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o311ai_0 _462_ (
    .A1(_035_),
    .A2(_036_),
    .A3(_083_),
    .B1(_197_),
    .C1(_077_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor2_1 _463_ (
    .A(_035_),
    .B(_189_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__xnor2_1 _464_ (
    .A(loopy[4]),
    .B(_189_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nor2_1 _465_ (
    .A(_162_),
    .B(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__o21ai_0 _466_ (
    .A1(\loopy_t[4] ),
    .A2(_161_),
    .B1(is_rendering),
    .Y(_202_)
  );
  sky130_fd_sc_hd__o22ai_1 _467_ (
    .A1(is_rendering),
    .A2(_035_),
    .B1(_201_),
    .B2(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _468_ (
    .A(_079_),
    .B(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a41oi_1 _469_ (
    .A1(ce),
    .A2(_154_),
    .A3(_198_),
    .A4(_204_),
    .B1(_196_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a21o_1 _470_ (
    .A1(loopy[14]),
    .A2(_053_),
    .B1(loopy[5]),
    .X(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _471_ (
    .A(\loopy_t[5] ),
    .B(_067_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__a31oi_1 _472_ (
    .A1(_056_),
    .A2(_068_),
    .A3(_205_),
    .B1(_273_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__o21ai_0 _473_ (
    .A1(is_rendering),
    .A2(loopy[5]),
    .B1(_079_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__a21oi_1 _474_ (
    .A1(_206_),
    .A2(_207_),
    .B1(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__a311oi_1 _475_ (
    .A1(loopy[4]),
    .A2(loopy[3]),
    .A3(_082_),
    .B1(loopy[5]),
    .C1(ppu_incr),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nor3_1 _476_ (
    .A(_078_),
    .B(_085_),
    .C(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand2_1 _477_ (
    .A(ppu_address_latch),
    .B(din[5]),
    .Y(_212_)
  );
  sky130_fd_sc_hd__o21ai_0 _478_ (
    .A1(_073_),
    .A2(_212_),
    .B1(ce),
    .Y(_213_)
  );
  sky130_fd_sc_hd__o32a_1 _479_ (
    .A1(_209_),
    .A2(_211_),
    .A3(_213_),
    .B1(ce),
    .B2(loopy[5]),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _480_ (
    .A(loopy[6]),
    .B(ce),
    .Y(_214_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _481_ (
    .A(loopy[6]),
    .SLEEP(is_rendering),
    .X(_215_)
  );
  sky130_fd_sc_hd__nor3b_1 _482_ (
    .A(loopy[6]),
    .B(_056_),
    .C_N(_048_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__a21oi_1 _483_ (
    .A1(loopy[6]),
    .A2(_056_),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__o21ai_0 _484_ (
    .A1(\loopy_t[6] ),
    .A2(_068_),
    .B1(is_rendering),
    .Y(_218_)
  );
  sky130_fd_sc_hd__a21oi_1 _485_ (
    .A1(_068_),
    .A2(_217_),
    .B1(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o21ai_0 _486_ (
    .A1(_215_),
    .A2(_219_),
    .B1(_079_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _487_ (
    .A(loopy[6]),
    .SLEEP(_085_),
    .X(_221_)
  );
  sky130_fd_sc_hd__a32oi_1 _488_ (
    .A1(_077_),
    .A2(_086_),
    .A3(_221_),
    .B1(_074_),
    .B2(din[6]),
    .Y(_222_)
  );
  sky130_fd_sc_hd__a31oi_1 _489_ (
    .A1(ce),
    .A2(_220_),
    .A3(_222_),
    .B1(_214_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _490_ (
    .A(loopy[7]),
    .B(ce),
    .Y(_223_)
  );
  sky130_fd_sc_hd__nand2_1 _491_ (
    .A(loopy[6]),
    .B(_055_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__xor2_1 _492_ (
    .A(loopy[7]),
    .B(_224_),
    .X(_225_)
  );
  sky130_fd_sc_hd__nor3_1 _493_ (
    .A(_057_),
    .B(_067_),
    .C(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__o21ai_0 _494_ (
    .A1(_045_),
    .A2(_068_),
    .B1(is_rendering),
    .Y(_227_)
  );
  sky130_fd_sc_hd__o221ai_1 _495_ (
    .A1(loopy[7]),
    .A2(is_rendering),
    .B1(_226_),
    .B2(_227_),
    .C1(_079_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__xnor2_1 _496_ (
    .A(loopy[7]),
    .B(_086_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(_077_),
    .B(_229_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__nand2_1 _498_ (
    .A(din[7]),
    .B(_074_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__a41oi_1 _499_ (
    .A1(ce),
    .A2(_228_),
    .A3(_230_),
    .A4(_231_),
    .B1(_223_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor2_1 _500_ (
    .A(loopy[8]),
    .B(ce),
    .Y(_232_)
  );
  sky130_fd_sc_hd__a31oi_1 _501_ (
    .A1(loopy[7]),
    .A2(loopy[6]),
    .A3(_055_),
    .B1(loopy[8]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand4_1 _502_ (
    .A(loopy[8]),
    .B(loopy[7]),
    .C(loopy[6]),
    .D(_055_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nand3b_1 _503_ (
    .A_N(_057_),
    .B(_068_),
    .C(_234_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__a21oi_1 _504_ (
    .A1(is_rendering),
    .A2(_235_),
    .B1(_233_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__and2_0 _505_ (
    .A(\loopy_t[8] ),
    .B(_067_),
    .X(_237_)
  );
  sky130_fd_sc_hd__o221ai_1 _506_ (
    .A1(loopy[8]),
    .A2(is_rendering),
    .B1(_236_),
    .B2(_237_),
    .C1(_079_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__a31oi_1 _507_ (
    .A1(loopy[7]),
    .A2(loopy[6]),
    .A3(_085_),
    .B1(loopy[8]),
    .Y(_239_)
  );
  sky130_fd_sc_hd__or3_1 _508_ (
    .A(_078_),
    .B(_087_),
    .C(_239_),
    .X(_240_)
  );
  sky130_fd_sc_hd__nand2_1 _509_ (
    .A(\loopy_t[8] ),
    .B(_074_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__a41oi_1 _510_ (
    .A1(ce),
    .A2(_238_),
    .A3(_240_),
    .A4(_241_),
    .B1(_232_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2b_1 _511_ (
    .A_N(loopy[9]),
    .B(_234_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__o211ai_1 _512_ (
    .A1(_048_),
    .A2(_056_),
    .B1(_068_),
    .C1(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nand2_1 _513_ (
    .A(\loopy_t[9] ),
    .B(_067_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__o21ai_0 _514_ (
    .A1(loopy[9]),
    .A2(is_rendering),
    .B1(_079_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__a31oi_1 _515_ (
    .A1(is_rendering),
    .A2(_243_),
    .A3(_244_),
    .B1(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__o21ai_0 _516_ (
    .A1(loopy[9]),
    .A2(_087_),
    .B1(_077_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nand2_1 _517_ (
    .A(\loopy_t[9] ),
    .B(_074_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__o211ai_1 _518_ (
    .A1(_088_),
    .A2(_247_),
    .B1(_248_),
    .C1(ce),
    .Y(_249_)
  );
  sky130_fd_sc_hd__o22a_1 _519_ (
    .A1(loopy[9]),
    .A2(ce),
    .B1(_246_),
    .B2(_249_),
    .X(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _520_ (
    .A(_136_),
    .B(_143_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nand3b_1 _521_ (
    .A_N(ain[2]),
    .B(read),
    .C(_071_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nand2_1 _522_ (
    .A(ppu_address_latch),
    .B(_251_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__o22ai_1 _523_ (
    .A1(ppu_address_latch),
    .A2(ce),
    .B1(_072_),
    .B2(_136_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a21oi_1 _524_ (
    .A1(_252_),
    .A2(_253_),
    .B1(_250_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _525_ (
    .A(din[2]),
    .B(_096_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__a21oi_1 _526_ (
    .A1(_274_),
    .A2(_096_),
    .B1(_254_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor3_1 _527_ (
    .A(din[3]),
    .B(_095_),
    .C(_100_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o22ai_1 _528_ (
    .A1(din[1]),
    .A2(_096_),
    .B1(_101_),
    .B2(\loopy_t[11] ),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nor2_1 _529_ (
    .A(_255_),
    .B(_256_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _530_ (
    .A(loopy[10]),
    .B(ce),
    .Y(_257_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _531_ (
    .A(loopy[10]),
    .SLEEP(is_rendering),
    .X(_258_)
  );
  sky130_fd_sc_hd__xnor2_1 _532_ (
    .A(loopy[10]),
    .B(_199_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nor2_1 _533_ (
    .A(\loopy_t[10] ),
    .B(_161_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__a211oi_1 _534_ (
    .A1(_161_),
    .A2(_259_),
    .B1(_260_),
    .C1(_273_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__o21ai_0 _535_ (
    .A1(_258_),
    .A2(_261_),
    .B1(_079_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__o21ai_0 _536_ (
    .A1(loopy[10]),
    .A2(_088_),
    .B1(_077_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _537_ (
    .A(_089_),
    .B(_263_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__a21oi_1 _538_ (
    .A1(\loopy_t[10] ),
    .A2(_074_),
    .B1(_264_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__a31oi_1 _539_ (
    .A1(ce),
    .A2(_262_),
    .A3(_265_),
    .B1(_257_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a22oi_1 _540_ (
    .A1(\loopy_t[8] ),
    .A2(_137_),
    .B1(_139_),
    .B2(din[6]),
    .Y(_266_)
  );
  sky130_fd_sc_hd__o21ai_0 _541_ (
    .A1(_040_),
    .A2(_100_),
    .B1(_266_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a22oi_1 _542_ (
    .A1(\loopy_t[9] ),
    .A2(_137_),
    .B1(_139_),
    .B2(din[7]),
    .Y(_267_)
  );
  sky130_fd_sc_hd__o21ai_0 _543_ (
    .A1(_043_),
    .A2(_100_),
    .B1(_267_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a22o_1 _544_ (
    .A1(\loopy_t[14] ),
    .A2(_137_),
    .B1(_139_),
    .B2(din[2]),
    .X(_005_)
  );
  sky130_fd_sc_hd__o22ai_1 _545_ (
    .A1(din[3]),
    .A2(_140_),
    .B1(_250_),
    .B2(\loopy_t[5] ),
    .Y(_268_)
  );
  sky130_fd_sc_hd__a31oi_1 _546_ (
    .A1(ce),
    .A2(_044_),
    .A3(_074_),
    .B1(_268_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _547_ (
    .A(din[6]),
    .B(_097_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand3_1 _548_ (
    .A(ce),
    .B(_074_),
    .C(_269_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__o221a_1 _549_ (
    .A1(din[4]),
    .A2(_140_),
    .B1(_250_),
    .B2(\loopy_t[6] ),
    .C1(_270_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nand4_1 _550_ (
    .A(ppu_address_latch),
    .B(ce),
    .C(din[5]),
    .D(_097_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__o221ai_1 _551_ (
    .A1(_099_),
    .A2(_231_),
    .B1(_250_),
    .B2(_045_),
    .C1(_271_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__dfxtp_1 _552_ (
    .CLK(clk),
    .D(_015_),
    .Q(loopy[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _553_ (
    .CLK(clk),
    .D(_021_),
    .Q(loopy[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _554_ (
    .CLK(clk),
    .D(_022_),
    .Q(loopy[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _555_ (
    .CLK(clk),
    .D(_023_),
    .Q(loopy[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _556_ (
    .CLK(clk),
    .D(_024_),
    .Q(loopy[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _557_ (
    .CLK(clk),
    .D(_025_),
    .Q(loopy[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _558_ (
    .CLK(clk),
    .D(_026_),
    .Q(loopy[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _559_ (
    .CLK(clk),
    .D(_027_),
    .Q(loopy[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _560_ (
    .CLK(clk),
    .D(_028_),
    .Q(loopy[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _561_ (
    .CLK(clk),
    .D(_029_),
    .Q(loopy[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _562_ (
    .CLK(clk),
    .D(_016_),
    .Q(loopy[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _563_ (
    .CLK(clk),
    .D(_017_),
    .Q(loopy[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _564_ (
    .CLK(clk),
    .D(_018_),
    .Q(loopy[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _565_ (
    .CLK(clk),
    .D(_019_),
    .Q(loopy[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _566_ (
    .CLK(clk),
    .D(_020_),
    .Q(loopy[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _567_ (
    .CLK(clk),
    .D(_033_),
    .Q(ppu_address_latch)
  );
  sky130_fd_sc_hd__dfxtp_1 _568_ (
    .CLK(clk),
    .D(_000_),
    .Q(\loopy_t[0] )
  );
  sky130_fd_sc_hd__dfxtp_1 _569_ (
    .CLK(clk),
    .D(_006_),
    .Q(\loopy_t[1] )
  );
  sky130_fd_sc_hd__dfxtp_1 _570_ (
    .CLK(clk),
    .D(_007_),
    .Q(\loopy_t[2] )
  );
  sky130_fd_sc_hd__dfxtp_1 _571_ (
    .CLK(clk),
    .D(_008_),
    .Q(\loopy_t[3] )
  );
  sky130_fd_sc_hd__dfxtp_1 _572_ (
    .CLK(clk),
    .D(_009_),
    .Q(\loopy_t[4] )
  );
  sky130_fd_sc_hd__dfxtp_1 _573_ (
    .CLK(clk),
    .D(_010_),
    .Q(\loopy_t[5] )
  );
  sky130_fd_sc_hd__dfxtp_1 _574_ (
    .CLK(clk),
    .D(_011_),
    .Q(\loopy_t[6] )
  );
  sky130_fd_sc_hd__dfxtp_1 _575_ (
    .CLK(clk),
    .D(_012_),
    .Q(\loopy_t[7] )
  );
  sky130_fd_sc_hd__dfxtp_1 _576_ (
    .CLK(clk),
    .D(_013_),
    .Q(\loopy_t[8] )
  );
  sky130_fd_sc_hd__dfxtp_1 _577_ (
    .CLK(clk),
    .D(_014_),
    .Q(\loopy_t[9] )
  );
  sky130_fd_sc_hd__dfxtp_1 _578_ (
    .CLK(clk),
    .D(_001_),
    .Q(\loopy_t[10] )
  );
  sky130_fd_sc_hd__dfxtp_1 _579_ (
    .CLK(clk),
    .D(_002_),
    .Q(\loopy_t[11] )
  );
  sky130_fd_sc_hd__dfxtp_1 _580_ (
    .CLK(clk),
    .D(_003_),
    .Q(\loopy_t[12] )
  );
  sky130_fd_sc_hd__dfxtp_1 _581_ (
    .CLK(clk),
    .D(_004_),
    .Q(\loopy_t[13] )
  );
  sky130_fd_sc_hd__dfxtp_1 _582_ (
    .CLK(clk),
    .D(_005_),
    .Q(\loopy_t[14] )
  );
  sky130_fd_sc_hd__dfxtp_1 _583_ (
    .CLK(clk),
    .D(_030_),
    .Q(fine_x_scroll[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _584_ (
    .CLK(clk),
    .D(_031_),
    .Q(fine_x_scroll[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _585_ (
    .CLK(clk),
    .D(_032_),
    .Q(fine_x_scroll[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _586_ (
    .CLK(clk),
    .D(_034_),
    .Q(ppu_incr)
  );
  assign \loopy_x[0]  = fine_x_scroll[0];
  assign \loopy_x[1]  = fine_x_scroll[1];
  assign \loopy_x[2]  = fine_x_scroll[2];
  assign \loopy_v[0]  = loopy[0];
  assign \loopy_v[1]  = loopy[1];
  assign \loopy_v[2]  = loopy[2];
  assign \loopy_v[3]  = loopy[3];
  assign \loopy_v[4]  = loopy[4];
  assign \loopy_v[5]  = loopy[5];
  assign \loopy_v[6]  = loopy[6];
  assign \loopy_v[7]  = loopy[7];
  assign \loopy_v[8]  = loopy[8];
  assign \loopy_v[9]  = loopy[9];
  assign \loopy_v[10]  = loopy[10];
  assign \loopy_v[11]  = loopy[11];
  assign \loopy_v[12]  = loopy[12];
  assign \loopy_v[13]  = loopy[13];
  assign \loopy_v[14]  = loopy[14];
endmodule
