/* Generated by Yosys 0.16 (git sha1 UNKNOWN, clang 13.1.6 -fPIC -Os) */

module RX(HCLK, HRESETn, SCK, SDI, DATA, BRCK, BWCK);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  output BRCK;
  wire BRCK;
  output BWCK;
  wire BWCK;
  output [31:0] DATA;
  wire [31:0] DATA;
  input HCLK;
  wire HCLK;
  input HRESETn;
  wire HRESETn;
  input SCK;
  wire SCK;
  wire SCK_SYNC;
  input SDI;
  wire SDI;
  wire SDI_SYNC;
  wire \sck_sync[0] ;
  wire \sdi_sync[0] ;
  wire \state[0] ;
  wire \state[1] ;
  wire \state[2] ;
  wire \state[3] ;
  sky130_fd_sc_hd__clkinv_1 _110_ (
    .A(\state[0] ),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor4b_1 _111_ (
    .A(\state[1] ),
    .B(\state[0] ),
    .C(\state[2] ),
    .D_N(\state[3] ),
    .Y(BRCK)
  );
  sky130_fd_sc_hd__or4b_1 _112_ (
    .A(\state[0] ),
    .B(\state[3] ),
    .C(\state[2] ),
    .D_N(\state[1] ),
    .X(_096_)
  );
  sky130_fd_sc_hd__clkinv_1 _113_ (
    .A(_096_),
    .Y(BWCK)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(DATA[1]),
    .B(BWCK),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(DATA[0]),
    .B(_096_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(_097_),
    .B(_098_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _117_ (
    .A(DATA[2]),
    .B(BWCK),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(DATA[1]),
    .B(_096_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _119_ (
    .A(_099_),
    .B(_100_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _120_ (
    .A(DATA[3]),
    .B(BWCK),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(DATA[2]),
    .B(_096_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _122_ (
    .A(_101_),
    .B(_102_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _123_ (
    .A(DATA[4]),
    .B(BWCK),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(DATA[3]),
    .B(_096_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _125_ (
    .A(_103_),
    .B(_104_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _126_ (
    .A(DATA[5]),
    .B(BWCK),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _127_ (
    .A(DATA[4]),
    .B(_096_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(_105_),
    .B(_106_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _129_ (
    .A(DATA[6]),
    .B(BWCK),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _130_ (
    .A(DATA[5]),
    .B(_096_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _131_ (
    .A(_107_),
    .B(_108_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _132_ (
    .A(DATA[7]),
    .B(BWCK),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _133_ (
    .A(DATA[6]),
    .B(_096_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(_109_),
    .B(_036_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _135_ (
    .A(DATA[8]),
    .B(BWCK),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _136_ (
    .A(DATA[7]),
    .B(_096_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _137_ (
    .A(_037_),
    .B(_038_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _138_ (
    .A(DATA[9]),
    .B(BWCK),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _139_ (
    .A(DATA[8]),
    .B(_096_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(_039_),
    .B(_040_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _141_ (
    .A(DATA[10]),
    .B(BWCK),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _142_ (
    .A(DATA[9]),
    .B(_096_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(_041_),
    .B(_042_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _144_ (
    .A(DATA[11]),
    .B(BWCK),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _145_ (
    .A(DATA[10]),
    .B(_096_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _146_ (
    .A(_043_),
    .B(_044_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _147_ (
    .A(DATA[12]),
    .B(BWCK),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _148_ (
    .A(DATA[11]),
    .B(_096_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _149_ (
    .A(_045_),
    .B(_046_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _150_ (
    .A(DATA[13]),
    .B(BWCK),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(DATA[12]),
    .B(_096_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _152_ (
    .A(_047_),
    .B(_048_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _153_ (
    .A(DATA[14]),
    .B(BWCK),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _154_ (
    .A(DATA[13]),
    .B(_096_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _155_ (
    .A(_049_),
    .B(_050_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _156_ (
    .A(DATA[15]),
    .B(BWCK),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _157_ (
    .A(DATA[14]),
    .B(_096_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _158_ (
    .A(_051_),
    .B(_052_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _159_ (
    .A(DATA[16]),
    .B(BWCK),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _160_ (
    .A(DATA[15]),
    .B(_096_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _161_ (
    .A(_053_),
    .B(_054_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(DATA[17]),
    .B(BWCK),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _163_ (
    .A(DATA[16]),
    .B(_096_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _164_ (
    .A(_055_),
    .B(_056_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _165_ (
    .A(DATA[18]),
    .B(BWCK),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _166_ (
    .A(DATA[17]),
    .B(_096_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(_057_),
    .B(_058_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(DATA[19]),
    .B(BWCK),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _169_ (
    .A(DATA[18]),
    .B(_096_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(_059_),
    .B(_060_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _171_ (
    .A(DATA[20]),
    .B(BWCK),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _172_ (
    .A(DATA[19]),
    .B(_096_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(_061_),
    .B(_062_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _174_ (
    .A(DATA[21]),
    .B(BWCK),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(DATA[20]),
    .B(_096_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(_063_),
    .B(_064_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _177_ (
    .A(DATA[22]),
    .B(BWCK),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(DATA[21]),
    .B(_096_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _179_ (
    .A(_065_),
    .B(_066_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _180_ (
    .A(DATA[23]),
    .B(BWCK),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(DATA[22]),
    .B(_096_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(_067_),
    .B(_068_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(DATA[24]),
    .B(BWCK),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _184_ (
    .A(DATA[23]),
    .B(_096_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(_069_),
    .B(_070_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(DATA[25]),
    .B(BWCK),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _187_ (
    .A(DATA[24]),
    .B(_096_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(_071_),
    .B(_072_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(DATA[26]),
    .B(BWCK),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(DATA[25]),
    .B(_096_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _191_ (
    .A(_073_),
    .B(_074_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(DATA[27]),
    .B(BWCK),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(DATA[26]),
    .B(_096_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(_075_),
    .B(_076_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(DATA[28]),
    .B(BWCK),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _196_ (
    .A(DATA[27]),
    .B(_096_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(_077_),
    .B(_078_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _198_ (
    .A(DATA[29]),
    .B(BWCK),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(DATA[28]),
    .B(_096_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _200_ (
    .A(_079_),
    .B(_080_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(DATA[30]),
    .B(BWCK),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _202_ (
    .A(DATA[29]),
    .B(_096_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(_081_),
    .B(_082_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(DATA[31]),
    .B(BWCK),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _205_ (
    .A(DATA[30]),
    .B(_096_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(_083_),
    .B(_084_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(SDI_SYNC),
    .B(BWCK),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _208_ (
    .A(DATA[31]),
    .B(_096_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(_085_),
    .B(_086_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor4b_1 _210_ (
    .A(\state[1] ),
    .B(\state[0] ),
    .C(\state[3] ),
    .D_N(\state[2] ),
    .Y(_087_)
  );
  sky130_fd_sc_hd__or4b_1 _211_ (
    .A(\state[1] ),
    .B(\state[0] ),
    .C(\state[3] ),
    .D_N(\state[2] ),
    .X(_088_)
  );
  sky130_fd_sc_hd__nor4b_1 _212_ (
    .A(\state[1] ),
    .B(\state[3] ),
    .C(\state[2] ),
    .D_N(\state[0] ),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor4_1 _213_ (
    .A(BRCK),
    .B(BWCK),
    .C(_087_),
    .D(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a31oi_1 _214_ (
    .A1(SCK_SYNC),
    .A2(_096_),
    .A3(_088_),
    .B1(BRCK),
    .Y(_091_)
  );
  sky130_fd_sc_hd__mux2i_1 _215_ (
    .A0(_091_),
    .A1(_095_),
    .S(_090_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor4b_1 _216_ (
    .A(\state[3] ),
    .B(\state[2] ),
    .C(SCK_SYNC),
    .D_N(\state[0] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _217_ (
    .A(\state[1] ),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor4_1 _218_ (
    .A(BRCK),
    .B(BWCK),
    .C(_087_),
    .D(_093_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o21ai_0 _219_ (
    .A1(SCK_SYNC),
    .A2(_088_),
    .B1(_096_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a21o_1 _220_ (
    .A1(\state[2] ),
    .A2(_090_),
    .B1(_094_),
    .X(_034_)
  );
  sky130_fd_sc_hd__a22o_1 _221_ (
    .A1(SCK_SYNC),
    .A2(_087_),
    .B1(_090_),
    .B2(\state[3] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__dfrtp_1 _222_ (
    .CLK(HCLK),
    .D(_000_),
    .Q(DATA[0]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _223_ (
    .CLK(HCLK),
    .D(_001_),
    .Q(DATA[1]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _224_ (
    .CLK(HCLK),
    .D(_002_),
    .Q(DATA[2]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _225_ (
    .CLK(HCLK),
    .D(_003_),
    .Q(DATA[3]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _226_ (
    .CLK(HCLK),
    .D(_004_),
    .Q(DATA[4]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _227_ (
    .CLK(HCLK),
    .D(_005_),
    .Q(DATA[5]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _228_ (
    .CLK(HCLK),
    .D(_006_),
    .Q(DATA[6]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _229_ (
    .CLK(HCLK),
    .D(_007_),
    .Q(DATA[7]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _230_ (
    .CLK(HCLK),
    .D(_008_),
    .Q(DATA[8]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _231_ (
    .CLK(HCLK),
    .D(_009_),
    .Q(DATA[9]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _232_ (
    .CLK(HCLK),
    .D(_010_),
    .Q(DATA[10]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _233_ (
    .CLK(HCLK),
    .D(_011_),
    .Q(DATA[11]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _234_ (
    .CLK(HCLK),
    .D(_012_),
    .Q(DATA[12]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _235_ (
    .CLK(HCLK),
    .D(_013_),
    .Q(DATA[13]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _236_ (
    .CLK(HCLK),
    .D(_014_),
    .Q(DATA[14]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _237_ (
    .CLK(HCLK),
    .D(_015_),
    .Q(DATA[15]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _238_ (
    .CLK(HCLK),
    .D(_016_),
    .Q(DATA[16]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _239_ (
    .CLK(HCLK),
    .D(_017_),
    .Q(DATA[17]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _240_ (
    .CLK(HCLK),
    .D(_018_),
    .Q(DATA[18]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _241_ (
    .CLK(HCLK),
    .D(_019_),
    .Q(DATA[19]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _242_ (
    .CLK(HCLK),
    .D(_020_),
    .Q(DATA[20]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _243_ (
    .CLK(HCLK),
    .D(_021_),
    .Q(DATA[21]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _244_ (
    .CLK(HCLK),
    .D(_022_),
    .Q(DATA[22]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _245_ (
    .CLK(HCLK),
    .D(_023_),
    .Q(DATA[23]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _246_ (
    .CLK(HCLK),
    .D(_024_),
    .Q(DATA[24]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _247_ (
    .CLK(HCLK),
    .D(_025_),
    .Q(DATA[25]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _248_ (
    .CLK(HCLK),
    .D(_026_),
    .Q(DATA[26]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _249_ (
    .CLK(HCLK),
    .D(_027_),
    .Q(DATA[27]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _250_ (
    .CLK(HCLK),
    .D(_028_),
    .Q(DATA[28]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _251_ (
    .CLK(HCLK),
    .D(_029_),
    .Q(DATA[29]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _252_ (
    .CLK(HCLK),
    .D(_030_),
    .Q(DATA[30]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _253_ (
    .CLK(HCLK),
    .D(_031_),
    .Q(DATA[31]),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfstp_2 _254_ (
    .CLK(HCLK),
    .D(_032_),
    .Q(\state[0] ),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _255_ (
    .CLK(HCLK),
    .D(_033_),
    .Q(\state[1] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _256_ (
    .CLK(HCLK),
    .D(_034_),
    .Q(\state[2] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _257_ (
    .CLK(HCLK),
    .D(_035_),
    .Q(\state[3] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfstp_2 _258_ (
    .CLK(HCLK),
    .D(SCK),
    .Q(\sck_sync[0] ),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfstp_2 _259_ (
    .CLK(HCLK),
    .D(\sck_sync[0] ),
    .Q(SCK_SYNC),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _260_ (
    .CLK(HCLK),
    .D(SDI),
    .Q(\sdi_sync[0] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _261_ (
    .CLK(HCLK),
    .D(\sdi_sync[0] ),
    .Q(SDI_SYNC),
    .RESET_B(HRESETn)
  );
endmodule

module TDI_AHB(SCK, SDI, SDO, SDOE, HCLK, HRESETn, HADDR, HTRANS, HSIZE, HWRITE, HWDATA, HREADY, HRDATA, HALT, RSTn);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire BRCK;
  wire BWCK;
  wire \CYCLES[0] ;
  wire \CYCLES[10] ;
  wire \CYCLES[11] ;
  wire \CYCLES[12] ;
  wire \CYCLES[13] ;
  wire \CYCLES[14] ;
  wire \CYCLES[15] ;
  wire \CYCLES[1] ;
  wire \CYCLES[2] ;
  wire \CYCLES[3] ;
  wire \CYCLES[4] ;
  wire \CYCLES[5] ;
  wire \CYCLES[6] ;
  wire \CYCLES[7] ;
  wire \CYCLES[8] ;
  wire \CYCLES[9] ;
  output [31:0] HADDR;
  wire [31:0] HADDR;
  output HALT;
  wire HALT;
  input HCLK;
  wire HCLK;
  input [31:0] HRDATA;
  wire [31:0] HRDATA;
  input HREADY;
  wire HREADY;
  input HRESETn;
  wire HRESETn;
  output [2:0] HSIZE;
  wire [2:0] HSIZE;
  output [1:0] HTRANS;
  wire [1:0] HTRANS;
  output [31:0] HWDATA;
  wire [31:0] HWDATA;
  output HWRITE;
  wire HWRITE;
  output RSTn;
  wire RSTn;
  input SCK;
  wire SCK;
  input SDI;
  wire SDI;
  output SDO;
  wire SDO;
  output SDOE;
  wire SDOE;
  wire \WADDR[0] ;
  wire \WADDR[10] ;
  wire \WADDR[11] ;
  wire \WADDR[12] ;
  wire \WADDR[13] ;
  wire \WADDR[14] ;
  wire \WADDR[15] ;
  wire \WADDR[16] ;
  wire \WADDR[17] ;
  wire \WADDR[18] ;
  wire \WADDR[19] ;
  wire \WADDR[1] ;
  wire \WADDR[20] ;
  wire \WADDR[21] ;
  wire \WADDR[22] ;
  wire \WADDR[23] ;
  wire \WADDR[24] ;
  wire \WADDR[25] ;
  wire \WADDR[26] ;
  wire \WADDR[27] ;
  wire \WADDR[28] ;
  wire \WADDR[29] ;
  wire \WADDR[2] ;
  wire \WADDR[30] ;
  wire \WADDR[31] ;
  wire \WADDR[3] ;
  wire \WADDR[4] ;
  wire \WADDR[5] ;
  wire \WADDR[6] ;
  wire \WADDR[7] ;
  wire \WADDR[8] ;
  wire \WADDR[9] ;
  wire \bit_cntr[0] ;
  wire \bit_cntr[1] ;
  wire \bit_cntr[2] ;
  wire \bit_cntr[3] ;
  wire \bit_cntr[4] ;
  wire \bit_cntr[5] ;
  wire \bit_cntr[6] ;
  wire \bit_cntr[7] ;
  wire \bit_cntr_next[0] ;
  wire \bit_cntr_next[1] ;
  wire \bit_cntr_next[2] ;
  wire \bit_cntr_next[3] ;
  wire \bit_cntr_next[4] ;
  wire \bit_cntr_next[5] ;
  wire \bit_cntr_next[6] ;
  wire \bit_cntr_next[7] ;
  wire \nstate[0] ;
  wire \nstate[10] ;
  wire \nstate[11] ;
  wire \nstate[12] ;
  wire \nstate[13] ;
  wire \nstate[14] ;
  wire \nstate[15] ;
  wire \nstate[1] ;
  wire \nstate[2] ;
  wire \nstate[3] ;
  wire \nstate[4] ;
  wire \nstate[5] ;
  wire \nstate[6] ;
  wire \nstate[7] ;
  wire \nstate[8] ;
  wire \nstate[9] ;
  wire \shifter[10] ;
  wire \shifter[11] ;
  wire \shifter[12] ;
  wire \shifter[13] ;
  wire \shifter[14] ;
  wire \shifter[15] ;
  wire \shifter[16] ;
  wire \shifter[17] ;
  wire \shifter[18] ;
  wire \shifter[19] ;
  wire \shifter[1] ;
  wire \shifter[20] ;
  wire \shifter[21] ;
  wire \shifter[22] ;
  wire \shifter[23] ;
  wire \shifter[24] ;
  wire \shifter[25] ;
  wire \shifter[26] ;
  wire \shifter[27] ;
  wire \shifter[28] ;
  wire \shifter[29] ;
  wire \shifter[2] ;
  wire \shifter[30] ;
  wire \shifter[31] ;
  wire \shifter[3] ;
  wire \shifter[4] ;
  wire \shifter[5] ;
  wire \shifter[6] ;
  wire \shifter[7] ;
  wire \shifter[8] ;
  wire \shifter[9] ;
  wire \state[0] ;
  wire \state[10] ;
  wire \state[11] ;
  wire \state[12] ;
  wire \state[13] ;
  wire \state[14] ;
  wire \state[15] ;
  wire \state[1] ;
  wire \state[2] ;
  wire \state[3] ;
  wire \state[4] ;
  wire \state[5] ;
  wire \state[6] ;
  wire \state[7] ;
  wire \state[8] ;
  wire \state[9] ;
  sky130_fd_sc_hd__clkinv_1 _345_ (
    .A(\bit_cntr[3] ),
    .Y(_083_)
  );
  sky130_fd_sc_hd__clkinv_1 _346_ (
    .A(\state[1] ),
    .Y(_084_)
  );
  sky130_fd_sc_hd__clkinv_1 _347_ (
    .A(\state[2] ),
    .Y(_085_)
  );
  sky130_fd_sc_hd__clkinv_1 _348_ (
    .A(\state[5] ),
    .Y(_086_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(\state[6] ),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _350_ (
    .A(BWCK),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(\CYCLES[0] ),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _352_ (
    .A(\CYCLES[6] ),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(\CYCLES[13] ),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _354_ (
    .A(\CYCLES[14] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _355_ (
    .A(\shifter[31] ),
    .Y(_093_)
  );
  sky130_fd_sc_hd__clkinv_1 _356_ (
    .A(HRDATA[31]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(\bit_cntr_next[0] ),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor3_1 _358_ (
    .A(\bit_cntr[0] ),
    .B(\bit_cntr[1] ),
    .C(\bit_cntr[2] ),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor4_1 _359_ (
    .A(\bit_cntr[0] ),
    .B(\bit_cntr[1] ),
    .C(\bit_cntr[2] ),
    .D(\bit_cntr[3] ),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor3_1 _360_ (
    .A(\bit_cntr[7] ),
    .B(\bit_cntr[6] ),
    .C(\bit_cntr[5] ),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand3_1 _361_ (
    .A(\bit_cntr[4] ),
    .B(_097_),
    .C(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor4_1 _362_ (
    .A(\state[13] ),
    .B(\state[12] ),
    .C(\state[15] ),
    .D(\state[14] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__or4_1 _363_ (
    .A(\state[13] ),
    .B(\state[12] ),
    .C(\state[15] ),
    .D(\state[14] ),
    .X(_101_)
  );
  sky130_fd_sc_hd__nor3_1 _364_ (
    .A(\state[9] ),
    .B(\state[11] ),
    .C(\state[10] ),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor4_1 _365_ (
    .A(\state[9] ),
    .B(\state[8] ),
    .C(\state[11] ),
    .D(\state[10] ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(_100_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(\state[1] ),
    .B(\state[0] ),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor4_1 _368_ (
    .A(\state[5] ),
    .B(\state[4] ),
    .C(\state[7] ),
    .D(\state[6] ),
    .Y(_106_)
  );
  sky130_fd_sc_hd__or4_1 _369_ (
    .A(\state[5] ),
    .B(\state[4] ),
    .C(\state[7] ),
    .D(\state[6] ),
    .X(_107_)
  );
  sky130_fd_sc_hd__nand4b_1 _370_ (
    .A_N(\state[3] ),
    .B(\state[2] ),
    .C(_105_),
    .D(_106_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(_104_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand4_1 _372_ (
    .A(\state[3] ),
    .B(_085_),
    .C(_105_),
    .D(_106_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _373_ (
    .A(_104_),
    .SLEEP(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nor3_1 _374_ (
    .A(\state[1] ),
    .B(\state[3] ),
    .C(\state[2] ),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor4_1 _375_ (
    .A(\state[1] ),
    .B(\state[0] ),
    .C(\state[3] ),
    .D(\state[2] ),
    .Y(_113_)
  );
  sky130_fd_sc_hd__or4_1 _376_ (
    .A(\state[1] ),
    .B(\state[0] ),
    .C(\state[3] ),
    .D(\state[2] ),
    .X(_114_)
  );
  sky130_fd_sc_hd__or3_1 _377_ (
    .A(\state[7] ),
    .B(\state[6] ),
    .C(_114_),
    .X(_115_)
  );
  sky130_fd_sc_hd__nor3_1 _378_ (
    .A(\state[5] ),
    .B(\state[7] ),
    .C(\state[6] ),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand3_1 _379_ (
    .A(\state[4] ),
    .B(_113_),
    .C(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a21oi_1 _380_ (
    .A1(_110_),
    .A2(_117_),
    .B1(_104_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor3_1 _381_ (
    .A(\bit_cntr[7] ),
    .B(\bit_cntr[6] ),
    .C(\bit_cntr[4] ),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor4_1 _382_ (
    .A(\bit_cntr[7] ),
    .B(\bit_cntr[6] ),
    .C(\bit_cntr[4] ),
    .D(\bit_cntr[5] ),
    .Y(_120_)
  );
  sky130_fd_sc_hd__and3_1 _383_ (
    .A(\bit_cntr[3] ),
    .B(_096_),
    .C(_120_),
    .X(_121_)
  );
  sky130_fd_sc_hd__nand3_1 _384_ (
    .A(\bit_cntr[3] ),
    .B(_096_),
    .C(_120_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor4b_1 _385_ (
    .A(\state[1] ),
    .B(\state[3] ),
    .C(\state[2] ),
    .D_N(\state[0] ),
    .Y(_123_)
  );
  sky130_fd_sc_hd__and4_1 _386_ (
    .A(_100_),
    .B(_103_),
    .C(_106_),
    .D(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd__nand4_1 _387_ (
    .A(_100_),
    .B(_103_),
    .C(_106_),
    .D(_123_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor4b_1 _388_ (
    .A(\state[0] ),
    .B(\state[3] ),
    .C(\state[2] ),
    .D_N(\state[1] ),
    .Y(_126_)
  );
  sky130_fd_sc_hd__and4_1 _389_ (
    .A(_100_),
    .B(_103_),
    .C(_106_),
    .D(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd__or4b_1 _390_ (
    .A(\state[8] ),
    .B(\state[11] ),
    .C(\state[10] ),
    .D_N(\state[9] ),
    .X(_128_)
  );
  sky130_fd_sc_hd__nor4_1 _391_ (
    .A(_101_),
    .B(_107_),
    .C(_114_),
    .D(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__or4_1 _392_ (
    .A(_122_),
    .B(_124_),
    .C(_127_),
    .D(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nand3_1 _393_ (
    .A(\state[0] ),
    .B(_106_),
    .C(_112_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o22ai_1 _394_ (
    .A1(_099_),
    .A2(_109_),
    .B1(_118_),
    .B2(_130_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand3_1 _395_ (
    .A(\bit_cntr[5] ),
    .B(_097_),
    .C(_119_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__or3_1 _396_ (
    .A(\state[5] ),
    .B(\state[4] ),
    .C(_114_),
    .X(_134_)
  );
  sky130_fd_sc_hd__nor4b_1 _397_ (
    .A(\state[6] ),
    .B(_104_),
    .C(_134_),
    .D_N(\state[7] ),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor2_1 _398_ (
    .A(_133_),
    .B(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor4_1 _399_ (
    .A(_086_),
    .B(\state[4] ),
    .C(_104_),
    .D(_115_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor4_1 _400_ (
    .A(\state[7] ),
    .B(_087_),
    .C(_104_),
    .D(_134_),
    .Y(HWRITE)
  );
  sky130_fd_sc_hd__nand3_1 _401_ (
    .A(\state[8] ),
    .B(_100_),
    .C(_102_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor3_1 _402_ (
    .A(_107_),
    .B(_114_),
    .C(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor2_1 _403_ (
    .A(HWRITE),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nor3_1 _404_ (
    .A(_137_),
    .B(HWRITE),
    .C(_139_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor4b_1 _405_ (
    .A(\state[9] ),
    .B(\state[11] ),
    .C(\state[10] ),
    .D_N(\state[8] ),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand4_1 _406_ (
    .A(_100_),
    .B(_106_),
    .C(_113_),
    .D(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21o_1 _407_ (
    .A1(_136_),
    .A2(_141_),
    .B1(_132_),
    .X(_144_)
  );
  sky130_fd_sc_hd__a31o_1 _408_ (
    .A1(BRCK),
    .A2(_095_),
    .A3(_144_),
    .B1(\bit_cntr[0] ),
    .X(\bit_cntr_next[0] )
  );
  sky130_fd_sc_hd__o21bai_1 _409_ (
    .A1(_104_),
    .A2(_108_),
    .B1_N(_127_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor4_1 _410_ (
    .A(_118_),
    .B(_129_),
    .C(_139_),
    .D(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__clkinv_1 _411_ (
    .A(_146_),
    .Y(SDOE)
  );
  sky130_fd_sc_hd__nor2_1 _412_ (
    .A(_135_),
    .B(HWRITE),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _413_ (
    .A(_133_),
    .B(_147_),
    .Y(HTRANS[1])
  );
  sky130_fd_sc_hd__mux2_1 _414_ (
    .A0(HWDATA[0]),
    .A1(\WADDR[0] ),
    .S(HWRITE),
    .X(HADDR[0])
  );
  sky130_fd_sc_hd__mux2_1 _415_ (
    .A0(HWDATA[1]),
    .A1(\WADDR[1] ),
    .S(HWRITE),
    .X(HADDR[1])
  );
  sky130_fd_sc_hd__mux2_1 _416_ (
    .A0(HWDATA[2]),
    .A1(\WADDR[2] ),
    .S(HWRITE),
    .X(HADDR[2])
  );
  sky130_fd_sc_hd__mux2_1 _417_ (
    .A0(HWDATA[3]),
    .A1(\WADDR[3] ),
    .S(HWRITE),
    .X(HADDR[3])
  );
  sky130_fd_sc_hd__mux2_1 _418_ (
    .A0(HWDATA[4]),
    .A1(\WADDR[4] ),
    .S(HWRITE),
    .X(HADDR[4])
  );
  sky130_fd_sc_hd__mux2_1 _419_ (
    .A0(HWDATA[5]),
    .A1(\WADDR[5] ),
    .S(HWRITE),
    .X(HADDR[5])
  );
  sky130_fd_sc_hd__mux2_1 _420_ (
    .A0(HWDATA[6]),
    .A1(\WADDR[6] ),
    .S(HWRITE),
    .X(HADDR[6])
  );
  sky130_fd_sc_hd__mux2_1 _421_ (
    .A0(HWDATA[7]),
    .A1(\WADDR[7] ),
    .S(HWRITE),
    .X(HADDR[7])
  );
  sky130_fd_sc_hd__mux2_1 _422_ (
    .A0(HWDATA[8]),
    .A1(\WADDR[8] ),
    .S(HWRITE),
    .X(HADDR[8])
  );
  sky130_fd_sc_hd__mux2_1 _423_ (
    .A0(HWDATA[9]),
    .A1(\WADDR[9] ),
    .S(HWRITE),
    .X(HADDR[9])
  );
  sky130_fd_sc_hd__mux2_1 _424_ (
    .A0(HWDATA[10]),
    .A1(\WADDR[10] ),
    .S(HWRITE),
    .X(HADDR[10])
  );
  sky130_fd_sc_hd__mux2_1 _425_ (
    .A0(HWDATA[11]),
    .A1(\WADDR[11] ),
    .S(HWRITE),
    .X(HADDR[11])
  );
  sky130_fd_sc_hd__mux2_1 _426_ (
    .A0(HWDATA[12]),
    .A1(\WADDR[12] ),
    .S(HWRITE),
    .X(HADDR[12])
  );
  sky130_fd_sc_hd__mux2_1 _427_ (
    .A0(HWDATA[13]),
    .A1(\WADDR[13] ),
    .S(HWRITE),
    .X(HADDR[13])
  );
  sky130_fd_sc_hd__mux2_1 _428_ (
    .A0(HWDATA[14]),
    .A1(\WADDR[14] ),
    .S(HWRITE),
    .X(HADDR[14])
  );
  sky130_fd_sc_hd__mux2_1 _429_ (
    .A0(HWDATA[15]),
    .A1(\WADDR[15] ),
    .S(HWRITE),
    .X(HADDR[15])
  );
  sky130_fd_sc_hd__mux2_1 _430_ (
    .A0(HWDATA[16]),
    .A1(\WADDR[16] ),
    .S(HWRITE),
    .X(HADDR[16])
  );
  sky130_fd_sc_hd__mux2_1 _431_ (
    .A0(HWDATA[17]),
    .A1(\WADDR[17] ),
    .S(HWRITE),
    .X(HADDR[17])
  );
  sky130_fd_sc_hd__mux2_1 _432_ (
    .A0(HWDATA[18]),
    .A1(\WADDR[18] ),
    .S(HWRITE),
    .X(HADDR[18])
  );
  sky130_fd_sc_hd__mux2_1 _433_ (
    .A0(HWDATA[19]),
    .A1(\WADDR[19] ),
    .S(HWRITE),
    .X(HADDR[19])
  );
  sky130_fd_sc_hd__mux2_1 _434_ (
    .A0(HWDATA[20]),
    .A1(\WADDR[20] ),
    .S(HWRITE),
    .X(HADDR[20])
  );
  sky130_fd_sc_hd__mux2_1 _435_ (
    .A0(HWDATA[21]),
    .A1(\WADDR[21] ),
    .S(HWRITE),
    .X(HADDR[21])
  );
  sky130_fd_sc_hd__mux2_1 _436_ (
    .A0(HWDATA[22]),
    .A1(\WADDR[22] ),
    .S(HWRITE),
    .X(HADDR[22])
  );
  sky130_fd_sc_hd__mux2_1 _437_ (
    .A0(HWDATA[23]),
    .A1(\WADDR[23] ),
    .S(HWRITE),
    .X(HADDR[23])
  );
  sky130_fd_sc_hd__mux2_1 _438_ (
    .A0(HWDATA[24]),
    .A1(\WADDR[24] ),
    .S(HWRITE),
    .X(HADDR[24])
  );
  sky130_fd_sc_hd__mux2_1 _439_ (
    .A0(HWDATA[25]),
    .A1(\WADDR[25] ),
    .S(HWRITE),
    .X(HADDR[25])
  );
  sky130_fd_sc_hd__mux2_1 _440_ (
    .A0(HWDATA[26]),
    .A1(\WADDR[26] ),
    .S(HWRITE),
    .X(HADDR[26])
  );
  sky130_fd_sc_hd__mux2_1 _441_ (
    .A0(HWDATA[27]),
    .A1(\WADDR[27] ),
    .S(HWRITE),
    .X(HADDR[27])
  );
  sky130_fd_sc_hd__mux2_1 _442_ (
    .A0(HWDATA[28]),
    .A1(\WADDR[28] ),
    .S(HWRITE),
    .X(HADDR[28])
  );
  sky130_fd_sc_hd__mux2_1 _443_ (
    .A0(HWDATA[29]),
    .A1(\WADDR[29] ),
    .S(HWRITE),
    .X(HADDR[29])
  );
  sky130_fd_sc_hd__mux2_1 _444_ (
    .A0(HWDATA[30]),
    .A1(\WADDR[30] ),
    .S(HWRITE),
    .X(HADDR[30])
  );
  sky130_fd_sc_hd__mux2_1 _445_ (
    .A0(HWDATA[31]),
    .A1(\WADDR[31] ),
    .S(HWRITE),
    .X(HADDR[31])
  );
  sky130_fd_sc_hd__xor2_1 _446_ (
    .A(\bit_cntr_next[0] ),
    .B(\bit_cntr_next[1] ),
    .X(_148_)
  );
  sky130_fd_sc_hd__a31o_1 _447_ (
    .A1(BRCK),
    .A2(_144_),
    .A3(_148_),
    .B1(\bit_cntr[1] ),
    .X(\bit_cntr_next[1] )
  );
  sky130_fd_sc_hd__and3_1 _448_ (
    .A(\bit_cntr_next[0] ),
    .B(\bit_cntr_next[2] ),
    .C(\bit_cntr_next[1] ),
    .X(_149_)
  );
  sky130_fd_sc_hd__a21oi_1 _449_ (
    .A1(\bit_cntr_next[0] ),
    .A2(\bit_cntr_next[1] ),
    .B1(\bit_cntr_next[2] ),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _450_ (
    .A(_149_),
    .B(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a31o_1 _451_ (
    .A1(BRCK),
    .A2(_144_),
    .A3(_151_),
    .B1(\bit_cntr[2] ),
    .X(\bit_cntr_next[2] )
  );
  sky130_fd_sc_hd__and2_0 _452_ (
    .A(\bit_cntr_next[3] ),
    .B(_149_),
    .X(_152_)
  );
  sky130_fd_sc_hd__o21ai_0 _453_ (
    .A1(\bit_cntr_next[3] ),
    .A2(_149_),
    .B1(BRCK),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o22ai_1 _454_ (
    .A1(_083_),
    .A2(BRCK),
    .B1(_152_),
    .B2(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a22o_1 _455_ (
    .A1(\bit_cntr[3] ),
    .A2(_122_),
    .B1(_144_),
    .B2(_154_),
    .X(\bit_cntr_next[3] )
  );
  sky130_fd_sc_hd__nor2_1 _456_ (
    .A(\bit_cntr_next[4] ),
    .B(_152_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__and3_1 _457_ (
    .A(\bit_cntr_next[4] ),
    .B(\bit_cntr_next[3] ),
    .C(_149_),
    .X(_156_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _458_ (
    .A(\bit_cntr[4] ),
    .SLEEP(BRCK),
    .X(_157_)
  );
  sky130_fd_sc_hd__o21ai_0 _459_ (
    .A1(_155_),
    .A2(_156_),
    .B1(BRCK),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a32o_1 _460_ (
    .A1(_144_),
    .A2(_157_),
    .A3(_158_),
    .B1(_099_),
    .B2(\bit_cntr[4] ),
    .X(\bit_cntr_next[4] )
  );
  sky130_fd_sc_hd__xnor2_1 _461_ (
    .A(\bit_cntr_next[5] ),
    .B(_156_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _462_ (
    .A(\bit_cntr[5] ),
    .B(BRCK),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a21oi_1 _463_ (
    .A1(BRCK),
    .A2(_159_),
    .B1(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a22o_1 _464_ (
    .A1(\bit_cntr[5] ),
    .A2(_133_),
    .B1(_144_),
    .B2(_161_),
    .X(\bit_cntr_next[5] )
  );
  sky130_fd_sc_hd__nand3_1 _465_ (
    .A(\bit_cntr_next[5] ),
    .B(\bit_cntr_next[6] ),
    .C(_156_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a21o_1 _466_ (
    .A1(\bit_cntr_next[5] ),
    .A2(_156_),
    .B1(\bit_cntr_next[6] ),
    .X(_163_)
  );
  sky130_fd_sc_hd__a41o_1 _467_ (
    .A1(BRCK),
    .A2(_144_),
    .A3(_162_),
    .A4(_163_),
    .B1(\bit_cntr[6] ),
    .X(\bit_cntr_next[6] )
  );
  sky130_fd_sc_hd__xnor2_1 _468_ (
    .A(\bit_cntr_next[7] ),
    .B(_162_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a31o_1 _469_ (
    .A1(BRCK),
    .A2(_144_),
    .A3(_164_),
    .B1(\bit_cntr[7] ),
    .X(\bit_cntr_next[7] )
  );
  sky130_fd_sc_hd__nor4_1 _470_ (
    .A(_124_),
    .B(_135_),
    .C(_137_),
    .D(HWRITE),
    .Y(_165_)
  );
  sky130_fd_sc_hd__and2_0 _471_ (
    .A(_146_),
    .B(_165_),
    .X(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _472_ (
    .A(_146_),
    .B(_165_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o21ai_0 _473_ (
    .A1(_104_),
    .A2(_108_),
    .B1(_143_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _474_ (
    .A(_118_),
    .B(_121_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor3_1 _475_ (
    .A(_099_),
    .B(_104_),
    .C(_108_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__a21oi_1 _476_ (
    .A1(_122_),
    .A2(_124_),
    .B1(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__o21ai_0 _477_ (
    .A1(_127_),
    .A2(_129_),
    .B1(_121_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__o2111ai_1 _478_ (
    .A1(_133_),
    .A2(_140_),
    .B1(_169_),
    .C1(_171_),
    .D1(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a21o_1 _479_ (
    .A1(\state[0] ),
    .A2(_166_),
    .B1(_173_),
    .X(_329_)
  );
  sky130_fd_sc_hd__nand2b_1 _480_ (
    .A_N(HWDATA[25]),
    .B(HWDATA[24]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor4bb_1 _481_ (
    .A(HWDATA[28]),
    .B(HWDATA[30]),
    .C_N(HWDATA[31]),
    .D_N(HWDATA[29]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor4b_1 _482_ (
    .A(HWDATA[27]),
    .B(HWDATA[26]),
    .C(_174_),
    .D_N(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nor2_1 _483_ (
    .A(_122_),
    .B(_125_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand2_1 _484_ (
    .A(_121_),
    .B(_124_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__a22oi_1 _485_ (
    .A1(_122_),
    .A2(_127_),
    .B1(_176_),
    .B2(_177_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__or3_1 _486_ (
    .A(_104_),
    .B(_122_),
    .C(_131_),
    .X(_180_)
  );
  sky130_fd_sc_hd__o21ai_0 _487_ (
    .A1(_084_),
    .A2(_167_),
    .B1(_179_),
    .Y(_336_)
  );
  sky130_fd_sc_hd__nand2b_1 _488_ (
    .A_N(HWDATA[24]),
    .B(HWDATA[25]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor4b_1 _489_ (
    .A(HWDATA[27]),
    .B(_181_),
    .C(HWDATA[26]),
    .D_N(_175_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__and3_1 _490_ (
    .A(_121_),
    .B(_124_),
    .C(_182_),
    .X(_183_)
  );
  sky130_fd_sc_hd__a21oi_1 _491_ (
    .A1(_099_),
    .A2(_109_),
    .B1(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__o21ai_0 _492_ (
    .A1(_085_),
    .A2(_167_),
    .B1(_184_),
    .Y(_337_)
  );
  sky130_fd_sc_hd__nor2_1 _493_ (
    .A(_111_),
    .B(_121_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand3b_1 _494_ (
    .A_N(HWDATA[27]),
    .B(HWDATA[26]),
    .C(_175_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__nor4_1 _495_ (
    .A(HWDATA[24]),
    .B(HWDATA[25]),
    .C(_180_),
    .D(_186_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a211o_1 _496_ (
    .A1(\state[3] ),
    .A2(_166_),
    .B1(_185_),
    .C1(_187_),
    .X(_338_)
  );
  sky130_fd_sc_hd__nand3_1 _497_ (
    .A(\state[4] ),
    .B(_146_),
    .C(_165_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__or3_1 _498_ (
    .A(_104_),
    .B(_117_),
    .C(_121_),
    .X(_189_)
  );
  sky130_fd_sc_hd__o311ai_0 _499_ (
    .A1(_174_),
    .A2(_178_),
    .A3(_186_),
    .B1(_188_),
    .C1(_189_),
    .Y(_339_)
  );
  sky130_fd_sc_hd__nand3b_1 _500_ (
    .A_N(HWDATA[26]),
    .B(_175_),
    .C(HWDATA[27]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor3_1 _501_ (
    .A(_174_),
    .B(_178_),
    .C(_190_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _502_ (
    .A1(_133_),
    .A2(_137_),
    .B1(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__o21ai_0 _503_ (
    .A1(_086_),
    .A2(_167_),
    .B1(_192_),
    .Y(_340_)
  );
  sky130_fd_sc_hd__nor2b_1 _504_ (
    .A(_133_),
    .B_N(_137_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a21oi_1 _505_ (
    .A1(_133_),
    .A2(HWRITE),
    .B1(_193_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o21ai_0 _506_ (
    .A1(_087_),
    .A2(_167_),
    .B1(_194_),
    .Y(_341_)
  );
  sky130_fd_sc_hd__nand2_1 _507_ (
    .A(_133_),
    .B(_135_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__o41ai_1 _508_ (
    .A1(HWDATA[24]),
    .A2(HWDATA[25]),
    .A3(_178_),
    .A4(_190_),
    .B1(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__a21o_1 _509_ (
    .A1(\state[7] ),
    .A2(_166_),
    .B1(_196_),
    .X(_342_)
  );
  sky130_fd_sc_hd__nand3_1 _510_ (
    .A(\state[8] ),
    .B(_146_),
    .C(_165_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__mux2i_1 _511_ (
    .A0(_135_),
    .A1(_139_),
    .S(_133_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nand2_1 _512_ (
    .A(_197_),
    .B(_198_),
    .Y(_343_)
  );
  sky130_fd_sc_hd__a21oi_1 _513_ (
    .A1(_186_),
    .A2(_190_),
    .B1(HWDATA[25]),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nand2_1 _514_ (
    .A(_122_),
    .B(_129_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__o41ai_1 _515_ (
    .A1(_176_),
    .A2(_178_),
    .A3(_182_),
    .A4(_199_),
    .B1(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__a21o_1 _516_ (
    .A1(\state[9] ),
    .A2(_166_),
    .B1(_201_),
    .X(_344_)
  );
  sky130_fd_sc_hd__a21oi_1 _517_ (
    .A1(HWDATA[24]),
    .A2(HWDATA[25]),
    .B1(_186_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nor3_1 _518_ (
    .A(_178_),
    .B(_182_),
    .C(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nor4_1 _519_ (
    .A(_176_),
    .B(_178_),
    .C(_182_),
    .D(_202_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__o21a_1 _520_ (
    .A1(HWDATA[25]),
    .A2(_190_),
    .B1(_204_),
    .X(_000_)
  );
  sky130_fd_sc_hd__and3b_1 _521_ (
    .A_N(\bit_cntr[3] ),
    .B(\bit_cntr[2] ),
    .C(\bit_cntr[1] ),
    .X(_205_)
  );
  sky130_fd_sc_hd__nand3_1 _522_ (
    .A(\bit_cntr[0] ),
    .B(_120_),
    .C(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nor2_1 _523_ (
    .A(_125_),
    .B(_206_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nand3_1 _524_ (
    .A(BRCK),
    .B(_120_),
    .C(_205_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nor2_1 _525_ (
    .A(\bit_cntr[0] ),
    .B(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _526_ (
    .A(\bit_cntr[0] ),
    .SLEEP(_208_),
    .X(_210_)
  );
  sky130_fd_sc_hd__o21ai_0 _527_ (
    .A1(\CYCLES[0] ),
    .A2(_207_),
    .B1(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nor4_1 _528_ (
    .A(_089_),
    .B(_104_),
    .C(_131_),
    .D(_206_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nor2_1 _529_ (
    .A(_211_),
    .B(_212_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _530_ (
    .A(\CYCLES[1] ),
    .B(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__a211oi_1 _531_ (
    .A1(\CYCLES[1] ),
    .A2(_212_),
    .B1(_213_),
    .C1(_209_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a21oi_1 _532_ (
    .A1(\CYCLES[1] ),
    .A2(_212_),
    .B1(\CYCLES[2] ),
    .Y(_214_)
  );
  sky130_fd_sc_hd__and3_1 _533_ (
    .A(\CYCLES[0] ),
    .B(\CYCLES[1] ),
    .C(\CYCLES[2] ),
    .X(_215_)
  );
  sky130_fd_sc_hd__o21a_1 _534_ (
    .A1(_207_),
    .A2(_209_),
    .B1(_215_),
    .X(_216_)
  );
  sky130_fd_sc_hd__nor3_1 _535_ (
    .A(_209_),
    .B(_214_),
    .C(_216_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21ai_0 _536_ (
    .A1(\CYCLES[3] ),
    .A2(_216_),
    .B1(_210_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__a21oi_1 _537_ (
    .A1(\CYCLES[3] ),
    .A2(_216_),
    .B1(_217_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a21oi_1 _538_ (
    .A1(\CYCLES[3] ),
    .A2(_216_),
    .B1(\CYCLES[4] ),
    .Y(_218_)
  );
  sky130_fd_sc_hd__and3_1 _539_ (
    .A(\CYCLES[3] ),
    .B(\CYCLES[4] ),
    .C(_215_),
    .X(_219_)
  );
  sky130_fd_sc_hd__a211oi_1 _540_ (
    .A1(_207_),
    .A2(_219_),
    .B1(_218_),
    .C1(_209_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a21oi_1 _541_ (
    .A1(_207_),
    .A2(_219_),
    .B1(\CYCLES[5] ),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand4_1 _542_ (
    .A(\CYCLES[3] ),
    .B(\CYCLES[4] ),
    .C(\CYCLES[5] ),
    .D(_215_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nor4_1 _543_ (
    .A(_104_),
    .B(_131_),
    .C(_206_),
    .D(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nor3_1 _544_ (
    .A(_209_),
    .B(_220_),
    .C(_222_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor4_1 _545_ (
    .A(_090_),
    .B(_125_),
    .C(_206_),
    .D(_221_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__o21ai_0 _546_ (
    .A1(\CYCLES[6] ),
    .A2(_222_),
    .B1(_210_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nor2_1 _547_ (
    .A(_223_),
    .B(_224_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_0 _548_ (
    .A1(\CYCLES[7] ),
    .A2(_223_),
    .B1(_210_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__a21oi_1 _549_ (
    .A1(\CYCLES[7] ),
    .A2(_223_),
    .B1(_225_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a21oi_1 _550_ (
    .A1(\CYCLES[7] ),
    .A2(_223_),
    .B1(\CYCLES[8] ),
    .Y(_226_)
  );
  sky130_fd_sc_hd__and3_1 _551_ (
    .A(\CYCLES[7] ),
    .B(\CYCLES[8] ),
    .C(_223_),
    .X(_227_)
  );
  sky130_fd_sc_hd__nor3_1 _552_ (
    .A(_209_),
    .B(_226_),
    .C(_227_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__o21ai_0 _553_ (
    .A1(\CYCLES[9] ),
    .A2(_227_),
    .B1(_210_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__a21oi_1 _554_ (
    .A1(\CYCLES[9] ),
    .A2(_227_),
    .B1(_228_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a21oi_1 _555_ (
    .A1(\CYCLES[9] ),
    .A2(_227_),
    .B1(\CYCLES[10] ),
    .Y(_229_)
  );
  sky130_fd_sc_hd__and4_1 _556_ (
    .A(\CYCLES[7] ),
    .B(\CYCLES[8] ),
    .C(\CYCLES[9] ),
    .D(\CYCLES[10] ),
    .X(_230_)
  );
  sky130_fd_sc_hd__and2_0 _557_ (
    .A(_223_),
    .B(_230_),
    .X(_231_)
  );
  sky130_fd_sc_hd__nor3_1 _558_ (
    .A(_209_),
    .B(_229_),
    .C(_231_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__o21ai_0 _559_ (
    .A1(\CYCLES[11] ),
    .A2(_231_),
    .B1(_210_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__a21oi_1 _560_ (
    .A1(\CYCLES[11] ),
    .A2(_231_),
    .B1(_232_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a21oi_1 _561_ (
    .A1(\CYCLES[11] ),
    .A2(_231_),
    .B1(\CYCLES[12] ),
    .Y(_233_)
  );
  sky130_fd_sc_hd__and4_1 _562_ (
    .A(\CYCLES[11] ),
    .B(\CYCLES[12] ),
    .C(_223_),
    .D(_230_),
    .X(_234_)
  );
  sky130_fd_sc_hd__nand4_1 _563_ (
    .A(\CYCLES[11] ),
    .B(\CYCLES[12] ),
    .C(_223_),
    .D(_230_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nor3_1 _564_ (
    .A(_209_),
    .B(_233_),
    .C(_234_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o21ai_0 _565_ (
    .A1(\CYCLES[13] ),
    .A2(_234_),
    .B1(_210_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__a21oi_1 _566_ (
    .A1(\CYCLES[13] ),
    .A2(_234_),
    .B1(_236_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21oi_1 _567_ (
    .A1(\CYCLES[13] ),
    .A2(_234_),
    .B1(\CYCLES[14] ),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor3_1 _568_ (
    .A(_091_),
    .B(_092_),
    .C(_235_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nor3_1 _569_ (
    .A(_209_),
    .B(_237_),
    .C(_238_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__o31ai_1 _570_ (
    .A1(_091_),
    .A2(_092_),
    .A3(_235_),
    .B1(\CYCLES[15] ),
    .Y(_239_)
  );
  sky130_fd_sc_hd__or4_1 _571_ (
    .A(_091_),
    .B(_092_),
    .C(\CYCLES[15] ),
    .D(_235_),
    .X(_240_)
  );
  sky130_fd_sc_hd__a21oi_1 _572_ (
    .A1(_239_),
    .A2(_240_),
    .B1(_209_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _573_ (
    .A0(\WADDR[0] ),
    .A1(HWDATA[0]),
    .S(_193_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _574_ (
    .A0(\WADDR[1] ),
    .A1(HWDATA[1]),
    .S(_193_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _575_ (
    .A0(\WADDR[2] ),
    .A1(HWDATA[2]),
    .S(_193_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _576_ (
    .A0(\WADDR[3] ),
    .A1(HWDATA[3]),
    .S(_193_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _577_ (
    .A0(\WADDR[4] ),
    .A1(HWDATA[4]),
    .S(_193_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _578_ (
    .A0(\WADDR[5] ),
    .A1(HWDATA[5]),
    .S(_193_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _579_ (
    .A0(\WADDR[6] ),
    .A1(HWDATA[6]),
    .S(_193_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _580_ (
    .A0(\WADDR[7] ),
    .A1(HWDATA[7]),
    .S(_193_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _581_ (
    .A0(\WADDR[8] ),
    .A1(HWDATA[8]),
    .S(_193_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _582_ (
    .A0(\WADDR[9] ),
    .A1(HWDATA[9]),
    .S(_193_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _583_ (
    .A0(\WADDR[10] ),
    .A1(HWDATA[10]),
    .S(_193_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _584_ (
    .A0(\WADDR[11] ),
    .A1(HWDATA[11]),
    .S(_193_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _585_ (
    .A0(\WADDR[12] ),
    .A1(HWDATA[12]),
    .S(_193_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _586_ (
    .A0(\WADDR[13] ),
    .A1(HWDATA[13]),
    .S(_193_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _587_ (
    .A0(\WADDR[14] ),
    .A1(HWDATA[14]),
    .S(_193_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _588_ (
    .A0(\WADDR[15] ),
    .A1(HWDATA[15]),
    .S(_193_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _589_ (
    .A0(\WADDR[16] ),
    .A1(HWDATA[16]),
    .S(_193_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _590_ (
    .A0(\WADDR[17] ),
    .A1(HWDATA[17]),
    .S(_193_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _591_ (
    .A0(\WADDR[18] ),
    .A1(HWDATA[18]),
    .S(_193_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _592_ (
    .A0(\WADDR[19] ),
    .A1(HWDATA[19]),
    .S(_193_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _593_ (
    .A0(\WADDR[20] ),
    .A1(HWDATA[20]),
    .S(_193_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _594_ (
    .A0(\WADDR[21] ),
    .A1(HWDATA[21]),
    .S(_193_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _595_ (
    .A0(\WADDR[22] ),
    .A1(HWDATA[22]),
    .S(_193_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _596_ (
    .A0(\WADDR[23] ),
    .A1(HWDATA[23]),
    .S(_193_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _597_ (
    .A0(\WADDR[24] ),
    .A1(HWDATA[24]),
    .S(_193_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _598_ (
    .A0(\WADDR[25] ),
    .A1(HWDATA[25]),
    .S(_193_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _599_ (
    .A0(\WADDR[26] ),
    .A1(HWDATA[26]),
    .S(_193_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _600_ (
    .A0(\WADDR[27] ),
    .A1(HWDATA[27]),
    .S(_193_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _601_ (
    .A0(\WADDR[28] ),
    .A1(HWDATA[28]),
    .S(_193_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _602_ (
    .A0(\WADDR[29] ),
    .A1(HWDATA[29]),
    .S(_193_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _603_ (
    .A0(\WADDR[30] ),
    .A1(HWDATA[30]),
    .S(_193_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _604_ (
    .A0(\WADDR[31] ),
    .A1(HWDATA[31]),
    .S(_193_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _605_ (
    .A(_097_),
    .B(_120_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nand3_1 _606_ (
    .A(_097_),
    .B(_120_),
    .C(_129_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a22o_1 _607_ (
    .A1(_121_),
    .A2(_129_),
    .B1(_242_),
    .B2(RSTn),
    .X(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _608_ (
    .A(HALT),
    .B(_169_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__o21ai_0 _609_ (
    .A1(_111_),
    .A2(_122_),
    .B1(_243_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o311ai_0 _610_ (
    .A1(_118_),
    .A2(_139_),
    .A3(_145_),
    .B1(_241_),
    .C1(BWCK),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a41oi_1 _611_ (
    .A1(BWCK),
    .A2(_097_),
    .A3(_120_),
    .A4(_139_),
    .B1(_177_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__a21oi_1 _612_ (
    .A1(_244_),
    .A2(_245_),
    .B1(_204_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nor4_1 _613_ (
    .A(_176_),
    .B(_180_),
    .C(_182_),
    .D(_202_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__o311ai_0 _614_ (
    .A1(_118_),
    .A2(_127_),
    .A3(_168_),
    .B1(_241_),
    .C1(BWCK),
    .Y(_248_)
  );
  sky130_fd_sc_hd__or3_1 _615_ (
    .A(_088_),
    .B(_143_),
    .C(_241_),
    .X(_249_)
  );
  sky130_fd_sc_hd__a31oi_1 _616_ (
    .A1(_180_),
    .A2(_248_),
    .A3(_249_),
    .B1(_247_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__mux2i_1 _617_ (
    .A0(HRDATA[0]),
    .A1(\shifter[1] ),
    .S(_249_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__and2_0 _618_ (
    .A(_089_),
    .B(_182_),
    .X(_252_)
  );
  sky130_fd_sc_hd__mux2i_1 _619_ (
    .A0(_252_),
    .A1(_251_),
    .S(_180_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__mux2_1 _620_ (
    .A0(SDO),
    .A1(_253_),
    .S(_246_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2i_1 _621_ (
    .A0(HRDATA[1]),
    .A1(\shifter[2] ),
    .S(_249_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nand2_1 _622_ (
    .A(\CYCLES[1] ),
    .B(_183_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o21ai_0 _623_ (
    .A1(_177_),
    .A2(_254_),
    .B1(_255_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__mux2_1 _624_ (
    .A0(\shifter[1] ),
    .A1(_256_),
    .S(_246_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2i_1 _625_ (
    .A0(HRDATA[2]),
    .A1(\shifter[3] ),
    .S(_249_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nand2_1 _626_ (
    .A(\CYCLES[2] ),
    .B(_183_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__o21ai_0 _627_ (
    .A1(_177_),
    .A2(_257_),
    .B1(_258_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__mux2_1 _628_ (
    .A0(\shifter[2] ),
    .A1(_259_),
    .S(_246_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2i_1 _629_ (
    .A0(HRDATA[3]),
    .A1(\shifter[4] ),
    .S(_249_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nand2_1 _630_ (
    .A(\CYCLES[3] ),
    .B(_183_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__o21ai_0 _631_ (
    .A1(_177_),
    .A2(_260_),
    .B1(_261_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__mux2_1 _632_ (
    .A0(\shifter[3] ),
    .A1(_262_),
    .S(_246_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2i_1 _633_ (
    .A0(HRDATA[4]),
    .A1(\shifter[5] ),
    .S(_249_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nand2_1 _634_ (
    .A(\CYCLES[4] ),
    .B(_183_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__o21ai_0 _635_ (
    .A1(_177_),
    .A2(_263_),
    .B1(_264_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__mux2_1 _636_ (
    .A0(\shifter[4] ),
    .A1(_265_),
    .S(_246_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2i_1 _637_ (
    .A0(HRDATA[5]),
    .A1(\shifter[6] ),
    .S(_249_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nand2_1 _638_ (
    .A(\CYCLES[5] ),
    .B(_183_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__o21ai_0 _639_ (
    .A1(_177_),
    .A2(_266_),
    .B1(_267_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__mux2_1 _640_ (
    .A0(\shifter[5] ),
    .A1(_268_),
    .S(_246_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2i_1 _641_ (
    .A0(HRDATA[6]),
    .A1(\shifter[7] ),
    .S(_249_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand2_1 _642_ (
    .A(\CYCLES[6] ),
    .B(_183_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__o21ai_0 _643_ (
    .A1(_177_),
    .A2(_269_),
    .B1(_270_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__mux2_1 _644_ (
    .A0(\shifter[6] ),
    .A1(_271_),
    .S(_246_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _645_ (
    .A0(HRDATA[7]),
    .A1(\shifter[8] ),
    .S(_249_),
    .X(_272_)
  );
  sky130_fd_sc_hd__and2_0 _646_ (
    .A(\CYCLES[7] ),
    .B(_183_),
    .X(_273_)
  );
  sky130_fd_sc_hd__a211o_1 _647_ (
    .A1(_180_),
    .A2(_272_),
    .B1(_273_),
    .C1(_203_),
    .X(_274_)
  );
  sky130_fd_sc_hd__mux2_1 _648_ (
    .A0(\shifter[7] ),
    .A1(_274_),
    .S(_250_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2i_1 _649_ (
    .A0(HRDATA[8]),
    .A1(\shifter[9] ),
    .S(_249_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__nand2_1 _650_ (
    .A(\CYCLES[8] ),
    .B(_183_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__o21ai_0 _651_ (
    .A1(_177_),
    .A2(_275_),
    .B1(_276_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__mux2_1 _652_ (
    .A0(\shifter[8] ),
    .A1(_277_),
    .S(_246_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2i_1 _653_ (
    .A0(HRDATA[9]),
    .A1(\shifter[10] ),
    .S(_249_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__nand2_1 _654_ (
    .A(\CYCLES[9] ),
    .B(_183_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__o21ai_0 _655_ (
    .A1(_177_),
    .A2(_278_),
    .B1(_279_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__mux2_1 _656_ (
    .A0(\shifter[9] ),
    .A1(_280_),
    .S(_246_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2i_1 _657_ (
    .A0(HRDATA[10]),
    .A1(\shifter[11] ),
    .S(_249_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nand2_1 _658_ (
    .A(\CYCLES[10] ),
    .B(_183_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__o21ai_0 _659_ (
    .A1(_177_),
    .A2(_281_),
    .B1(_282_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__mux2_1 _660_ (
    .A0(\shifter[10] ),
    .A1(_283_),
    .S(_246_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2i_1 _661_ (
    .A0(HRDATA[11]),
    .A1(\shifter[12] ),
    .S(_249_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand2_1 _662_ (
    .A(\CYCLES[11] ),
    .B(_183_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__o21ai_0 _663_ (
    .A1(_177_),
    .A2(_284_),
    .B1(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__mux2_1 _664_ (
    .A0(\shifter[11] ),
    .A1(_286_),
    .S(_246_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2i_1 _665_ (
    .A0(HRDATA[12]),
    .A1(\shifter[13] ),
    .S(_249_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__nand2_1 _666_ (
    .A(\CYCLES[12] ),
    .B(_183_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__o21ai_0 _667_ (
    .A1(_177_),
    .A2(_287_),
    .B1(_288_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__mux2_1 _668_ (
    .A0(\shifter[12] ),
    .A1(_289_),
    .S(_246_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2i_1 _669_ (
    .A0(HRDATA[13]),
    .A1(\shifter[14] ),
    .S(_249_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__nand2_1 _670_ (
    .A(\CYCLES[13] ),
    .B(_183_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__o21ai_0 _671_ (
    .A1(_177_),
    .A2(_290_),
    .B1(_291_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__mux2_1 _672_ (
    .A0(\shifter[13] ),
    .A1(_292_),
    .S(_246_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2i_1 _673_ (
    .A0(HRDATA[14]),
    .A1(\shifter[15] ),
    .S(_249_),
    .Y(_293_)
  );
  sky130_fd_sc_hd__nand2_1 _674_ (
    .A(\CYCLES[14] ),
    .B(_183_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__o21ai_0 _675_ (
    .A1(_177_),
    .A2(_293_),
    .B1(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__mux2_1 _676_ (
    .A0(\shifter[14] ),
    .A1(_295_),
    .S(_246_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2i_1 _677_ (
    .A0(HRDATA[15]),
    .A1(\shifter[16] ),
    .S(_249_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__nand2_1 _678_ (
    .A(\CYCLES[15] ),
    .B(_183_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__o21ai_0 _679_ (
    .A1(_177_),
    .A2(_296_),
    .B1(_297_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__mux2_1 _680_ (
    .A0(\shifter[15] ),
    .A1(_298_),
    .S(_246_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2i_1 _681_ (
    .A0(HRDATA[16]),
    .A1(\shifter[17] ),
    .S(_249_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__nor2_1 _682_ (
    .A(_177_),
    .B(_299_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__mux2_1 _683_ (
    .A0(\shifter[16] ),
    .A1(_300_),
    .S(_246_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2i_1 _684_ (
    .A0(HRDATA[17]),
    .A1(\shifter[18] ),
    .S(_249_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__nor2_1 _685_ (
    .A(_177_),
    .B(_301_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__mux2_1 _686_ (
    .A0(\shifter[17] ),
    .A1(_302_),
    .S(_246_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2i_1 _687_ (
    .A0(HRDATA[18]),
    .A1(\shifter[19] ),
    .S(_249_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__nor2_1 _688_ (
    .A(_177_),
    .B(_303_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__mux2_1 _689_ (
    .A0(\shifter[18] ),
    .A1(_304_),
    .S(_246_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2i_1 _690_ (
    .A0(HRDATA[19]),
    .A1(\shifter[20] ),
    .S(_249_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__nor2_1 _691_ (
    .A(_177_),
    .B(_305_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__mux2_1 _692_ (
    .A0(\shifter[19] ),
    .A1(_306_),
    .S(_246_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2i_1 _693_ (
    .A0(HRDATA[20]),
    .A1(\shifter[21] ),
    .S(_249_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__nor2_1 _694_ (
    .A(_177_),
    .B(_307_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__mux2_1 _695_ (
    .A0(\shifter[20] ),
    .A1(_308_),
    .S(_246_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2i_1 _696_ (
    .A0(HRDATA[21]),
    .A1(\shifter[22] ),
    .S(_249_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__nor2_1 _697_ (
    .A(_177_),
    .B(_309_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__mux2_1 _698_ (
    .A0(\shifter[21] ),
    .A1(_310_),
    .S(_246_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2i_1 _699_ (
    .A0(HRDATA[22]),
    .A1(\shifter[23] ),
    .S(_249_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__nor2_1 _700_ (
    .A(_177_),
    .B(_311_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__mux2_1 _701_ (
    .A0(\shifter[22] ),
    .A1(_312_),
    .S(_246_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2i_1 _702_ (
    .A0(HRDATA[23]),
    .A1(\shifter[24] ),
    .S(_249_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__nor2_1 _703_ (
    .A(_177_),
    .B(_313_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__mux2_1 _704_ (
    .A0(\shifter[23] ),
    .A1(_314_),
    .S(_246_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2i_1 _705_ (
    .A0(HRDATA[24]),
    .A1(\shifter[25] ),
    .S(_249_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__nor2_1 _706_ (
    .A(_177_),
    .B(_315_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__mux2_1 _707_ (
    .A0(\shifter[24] ),
    .A1(_316_),
    .S(_246_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2i_1 _708_ (
    .A0(HRDATA[25]),
    .A1(\shifter[26] ),
    .S(_249_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__nor2_1 _709_ (
    .A(_177_),
    .B(_317_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__mux2_1 _710_ (
    .A0(\shifter[25] ),
    .A1(_318_),
    .S(_246_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2i_1 _711_ (
    .A0(HRDATA[26]),
    .A1(\shifter[27] ),
    .S(_249_),
    .Y(_319_)
  );
  sky130_fd_sc_hd__nor2_1 _712_ (
    .A(_177_),
    .B(_319_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__mux2_1 _713_ (
    .A0(\shifter[26] ),
    .A1(_320_),
    .S(_246_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2i_1 _714_ (
    .A0(HRDATA[27]),
    .A1(\shifter[28] ),
    .S(_249_),
    .Y(_321_)
  );
  sky130_fd_sc_hd__nor2_1 _715_ (
    .A(_177_),
    .B(_321_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__mux2_1 _716_ (
    .A0(\shifter[27] ),
    .A1(_322_),
    .S(_246_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2i_1 _717_ (
    .A0(HRDATA[28]),
    .A1(\shifter[29] ),
    .S(_249_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__nor2_1 _718_ (
    .A(_177_),
    .B(_323_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__mux2_1 _719_ (
    .A0(\shifter[28] ),
    .A1(_324_),
    .S(_246_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux2i_1 _720_ (
    .A0(HRDATA[29]),
    .A1(\shifter[30] ),
    .S(_249_),
    .Y(_325_)
  );
  sky130_fd_sc_hd__nor2_1 _721_ (
    .A(_177_),
    .B(_325_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__mux2_1 _722_ (
    .A0(\shifter[29] ),
    .A1(_326_),
    .S(_246_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2i_1 _723_ (
    .A0(HRDATA[30]),
    .A1(\shifter[31] ),
    .S(_249_),
    .Y(_327_)
  );
  sky130_fd_sc_hd__nor2_1 _724_ (
    .A(_177_),
    .B(_327_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__mux2_1 _725_ (
    .A0(\shifter[30] ),
    .A1(_328_),
    .S(_246_),
    .X(_081_)
  );
  sky130_fd_sc_hd__o22ai_1 _726_ (
    .A1(_093_),
    .A2(_246_),
    .B1(_249_),
    .B2(_094_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__buf_1 _727_ (
    .A(\state[10] ),
    .X(_330_)
  );
  sky130_fd_sc_hd__buf_1 _728_ (
    .A(\state[11] ),
    .X(_331_)
  );
  sky130_fd_sc_hd__buf_1 _729_ (
    .A(\state[12] ),
    .X(_332_)
  );
  sky130_fd_sc_hd__buf_1 _730_ (
    .A(\state[13] ),
    .X(_333_)
  );
  sky130_fd_sc_hd__buf_1 _731_ (
    .A(\state[14] ),
    .X(_334_)
  );
  sky130_fd_sc_hd__buf_1 _732_ (
    .A(\state[15] ),
    .X(_335_)
  );
  \$_DLATCH_N_  \nstate_reg[0]  /* _733_ */ (
    .D(_329_),
    .E(_000_),
    .Q(\nstate[0] )
  );
  \$_DLATCH_N_  \nstate_reg[1]  /* _734_ */ (
    .D(_336_),
    .E(_000_),
    .Q(\nstate[1] )
  );
  \$_DLATCH_N_  \nstate_reg[2]  /* _735_ */ (
    .D(_337_),
    .E(_000_),
    .Q(\nstate[2] )
  );
  \$_DLATCH_N_  \nstate_reg[3]  /* _736_ */ (
    .D(_338_),
    .E(_000_),
    .Q(\nstate[3] )
  );
  \$_DLATCH_N_  \nstate_reg[4]  /* _737_ */ (
    .D(_339_),
    .E(_000_),
    .Q(\nstate[4] )
  );
  \$_DLATCH_N_  \nstate_reg[5]  /* _738_ */ (
    .D(_340_),
    .E(_000_),
    .Q(\nstate[5] )
  );
  \$_DLATCH_N_  \nstate_reg[6]  /* _739_ */ (
    .D(_341_),
    .E(_000_),
    .Q(\nstate[6] )
  );
  \$_DLATCH_N_  \nstate_reg[7]  /* _740_ */ (
    .D(_342_),
    .E(_000_),
    .Q(\nstate[7] )
  );
  \$_DLATCH_N_  \nstate_reg[8]  /* _741_ */ (
    .D(_343_),
    .E(_000_),
    .Q(\nstate[8] )
  );
  \$_DLATCH_N_  \nstate_reg[9]  /* _742_ */ (
    .D(_344_),
    .E(_000_),
    .Q(\nstate[9] )
  );
  \$_DLATCH_N_  \nstate_reg[10]  /* _743_ */ (
    .D(_330_),
    .E(_000_),
    .Q(\nstate[10] )
  );
  \$_DLATCH_N_  \nstate_reg[11]  /* _744_ */ (
    .D(_331_),
    .E(_000_),
    .Q(\nstate[11] )
  );
  \$_DLATCH_N_  \nstate_reg[12]  /* _745_ */ (
    .D(_332_),
    .E(_000_),
    .Q(\nstate[12] )
  );
  \$_DLATCH_N_  \nstate_reg[13]  /* _746_ */ (
    .D(_333_),
    .E(_000_),
    .Q(\nstate[13] )
  );
  \$_DLATCH_N_  \nstate_reg[14]  /* _747_ */ (
    .D(_334_),
    .E(_000_),
    .Q(\nstate[14] )
  );
  \$_DLATCH_N_  \nstate_reg[15]  /* _748_ */ (
    .D(_335_),
    .E(_000_),
    .Q(\nstate[15] )
  );
  sky130_fd_sc_hd__dfrtp_1 _749_ (
    .CLK(HCLK),
    .D(_001_),
    .Q(\CYCLES[0] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _750_ (
    .CLK(HCLK),
    .D(_002_),
    .Q(\CYCLES[1] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _751_ (
    .CLK(HCLK),
    .D(_003_),
    .Q(\CYCLES[2] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _752_ (
    .CLK(HCLK),
    .D(_004_),
    .Q(\CYCLES[3] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _753_ (
    .CLK(HCLK),
    .D(_005_),
    .Q(\CYCLES[4] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _754_ (
    .CLK(HCLK),
    .D(_006_),
    .Q(\CYCLES[5] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _755_ (
    .CLK(HCLK),
    .D(_007_),
    .Q(\CYCLES[6] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _756_ (
    .CLK(HCLK),
    .D(_008_),
    .Q(\CYCLES[7] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _757_ (
    .CLK(HCLK),
    .D(_009_),
    .Q(\CYCLES[8] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _758_ (
    .CLK(HCLK),
    .D(_010_),
    .Q(\CYCLES[9] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _759_ (
    .CLK(HCLK),
    .D(_011_),
    .Q(\CYCLES[10] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _760_ (
    .CLK(HCLK),
    .D(_012_),
    .Q(\CYCLES[11] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _761_ (
    .CLK(HCLK),
    .D(_013_),
    .Q(\CYCLES[12] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _762_ (
    .CLK(HCLK),
    .D(_014_),
    .Q(\CYCLES[13] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _763_ (
    .CLK(HCLK),
    .D(_015_),
    .Q(\CYCLES[14] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _764_ (
    .CLK(HCLK),
    .D(_016_),
    .Q(\CYCLES[15] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _765_ (
    .CLK(HCLK),
    .D(_017_),
    .Q(\WADDR[0] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _766_ (
    .CLK(HCLK),
    .D(_018_),
    .Q(\WADDR[1] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _767_ (
    .CLK(HCLK),
    .D(_019_),
    .Q(\WADDR[2] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _768_ (
    .CLK(HCLK),
    .D(_020_),
    .Q(\WADDR[3] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _769_ (
    .CLK(HCLK),
    .D(_021_),
    .Q(\WADDR[4] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _770_ (
    .CLK(HCLK),
    .D(_022_),
    .Q(\WADDR[5] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _771_ (
    .CLK(HCLK),
    .D(_023_),
    .Q(\WADDR[6] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _772_ (
    .CLK(HCLK),
    .D(_024_),
    .Q(\WADDR[7] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _773_ (
    .CLK(HCLK),
    .D(_025_),
    .Q(\WADDR[8] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _774_ (
    .CLK(HCLK),
    .D(_026_),
    .Q(\WADDR[9] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _775_ (
    .CLK(HCLK),
    .D(_027_),
    .Q(\WADDR[10] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _776_ (
    .CLK(HCLK),
    .D(_028_),
    .Q(\WADDR[11] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _777_ (
    .CLK(HCLK),
    .D(_029_),
    .Q(\WADDR[12] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _778_ (
    .CLK(HCLK),
    .D(_030_),
    .Q(\WADDR[13] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _779_ (
    .CLK(HCLK),
    .D(_031_),
    .Q(\WADDR[14] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _780_ (
    .CLK(HCLK),
    .D(_032_),
    .Q(\WADDR[15] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _781_ (
    .CLK(HCLK),
    .D(_033_),
    .Q(\WADDR[16] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _782_ (
    .CLK(HCLK),
    .D(_034_),
    .Q(\WADDR[17] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _783_ (
    .CLK(HCLK),
    .D(_035_),
    .Q(\WADDR[18] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _784_ (
    .CLK(HCLK),
    .D(_036_),
    .Q(\WADDR[19] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _785_ (
    .CLK(HCLK),
    .D(_037_),
    .Q(\WADDR[20] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _786_ (
    .CLK(HCLK),
    .D(_038_),
    .Q(\WADDR[21] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _787_ (
    .CLK(HCLK),
    .D(_039_),
    .Q(\WADDR[22] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _788_ (
    .CLK(HCLK),
    .D(_040_),
    .Q(\WADDR[23] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _789_ (
    .CLK(HCLK),
    .D(_041_),
    .Q(\WADDR[24] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _790_ (
    .CLK(HCLK),
    .D(_042_),
    .Q(\WADDR[25] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _791_ (
    .CLK(HCLK),
    .D(_043_),
    .Q(\WADDR[26] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _792_ (
    .CLK(HCLK),
    .D(_044_),
    .Q(\WADDR[27] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _793_ (
    .CLK(HCLK),
    .D(_045_),
    .Q(\WADDR[28] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _794_ (
    .CLK(HCLK),
    .D(_046_),
    .Q(\WADDR[29] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _795_ (
    .CLK(HCLK),
    .D(_047_),
    .Q(\WADDR[30] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _796_ (
    .CLK(HCLK),
    .D(_048_),
    .Q(\WADDR[31] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfstp_2 _797_ (
    .CLK(HCLK),
    .D(_049_),
    .Q(RSTn),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _798_ (
    .CLK(HCLK),
    .D(_050_),
    .Q(HALT),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfstp_2 _799_ (
    .CLK(HCLK),
    .D(\nstate[0] ),
    .Q(\state[0] ),
    .SET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _800_ (
    .CLK(HCLK),
    .D(\nstate[1] ),
    .Q(\state[1] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _801_ (
    .CLK(HCLK),
    .D(\nstate[2] ),
    .Q(\state[2] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _802_ (
    .CLK(HCLK),
    .D(\nstate[3] ),
    .Q(\state[3] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _803_ (
    .CLK(HCLK),
    .D(\nstate[4] ),
    .Q(\state[4] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _804_ (
    .CLK(HCLK),
    .D(\nstate[5] ),
    .Q(\state[5] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _805_ (
    .CLK(HCLK),
    .D(\nstate[6] ),
    .Q(\state[6] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _806_ (
    .CLK(HCLK),
    .D(\nstate[7] ),
    .Q(\state[7] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _807_ (
    .CLK(HCLK),
    .D(\nstate[8] ),
    .Q(\state[8] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _808_ (
    .CLK(HCLK),
    .D(\nstate[9] ),
    .Q(\state[9] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _809_ (
    .CLK(HCLK),
    .D(\nstate[10] ),
    .Q(\state[10] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _810_ (
    .CLK(HCLK),
    .D(\nstate[11] ),
    .Q(\state[11] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _811_ (
    .CLK(HCLK),
    .D(\nstate[12] ),
    .Q(\state[12] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _812_ (
    .CLK(HCLK),
    .D(\nstate[13] ),
    .Q(\state[13] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _813_ (
    .CLK(HCLK),
    .D(\nstate[14] ),
    .Q(\state[14] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _814_ (
    .CLK(HCLK),
    .D(\nstate[15] ),
    .Q(\state[15] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _815_ (
    .CLK(HCLK),
    .D(\bit_cntr_next[0] ),
    .Q(\bit_cntr[0] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _816_ (
    .CLK(HCLK),
    .D(\bit_cntr_next[1] ),
    .Q(\bit_cntr[1] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _817_ (
    .CLK(HCLK),
    .D(\bit_cntr_next[2] ),
    .Q(\bit_cntr[2] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _818_ (
    .CLK(HCLK),
    .D(\bit_cntr_next[3] ),
    .Q(\bit_cntr[3] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _819_ (
    .CLK(HCLK),
    .D(\bit_cntr_next[4] ),
    .Q(\bit_cntr[4] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _820_ (
    .CLK(HCLK),
    .D(\bit_cntr_next[5] ),
    .Q(\bit_cntr[5] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _821_ (
    .CLK(HCLK),
    .D(\bit_cntr_next[6] ),
    .Q(\bit_cntr[6] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _822_ (
    .CLK(HCLK),
    .D(\bit_cntr_next[7] ),
    .Q(\bit_cntr[7] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _823_ (
    .CLK(HCLK),
    .D(_051_),
    .Q(SDO),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _824_ (
    .CLK(HCLK),
    .D(_052_),
    .Q(\shifter[1] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _825_ (
    .CLK(HCLK),
    .D(_053_),
    .Q(\shifter[2] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _826_ (
    .CLK(HCLK),
    .D(_054_),
    .Q(\shifter[3] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _827_ (
    .CLK(HCLK),
    .D(_055_),
    .Q(\shifter[4] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _828_ (
    .CLK(HCLK),
    .D(_056_),
    .Q(\shifter[5] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _829_ (
    .CLK(HCLK),
    .D(_057_),
    .Q(\shifter[6] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _830_ (
    .CLK(HCLK),
    .D(_058_),
    .Q(\shifter[7] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _831_ (
    .CLK(HCLK),
    .D(_059_),
    .Q(\shifter[8] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _832_ (
    .CLK(HCLK),
    .D(_060_),
    .Q(\shifter[9] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _833_ (
    .CLK(HCLK),
    .D(_061_),
    .Q(\shifter[10] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _834_ (
    .CLK(HCLK),
    .D(_062_),
    .Q(\shifter[11] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _835_ (
    .CLK(HCLK),
    .D(_063_),
    .Q(\shifter[12] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _836_ (
    .CLK(HCLK),
    .D(_064_),
    .Q(\shifter[13] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _837_ (
    .CLK(HCLK),
    .D(_065_),
    .Q(\shifter[14] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _838_ (
    .CLK(HCLK),
    .D(_066_),
    .Q(\shifter[15] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _839_ (
    .CLK(HCLK),
    .D(_067_),
    .Q(\shifter[16] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _840_ (
    .CLK(HCLK),
    .D(_068_),
    .Q(\shifter[17] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _841_ (
    .CLK(HCLK),
    .D(_069_),
    .Q(\shifter[18] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _842_ (
    .CLK(HCLK),
    .D(_070_),
    .Q(\shifter[19] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _843_ (
    .CLK(HCLK),
    .D(_071_),
    .Q(\shifter[20] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _844_ (
    .CLK(HCLK),
    .D(_072_),
    .Q(\shifter[21] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _845_ (
    .CLK(HCLK),
    .D(_073_),
    .Q(\shifter[22] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _846_ (
    .CLK(HCLK),
    .D(_074_),
    .Q(\shifter[23] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _847_ (
    .CLK(HCLK),
    .D(_075_),
    .Q(\shifter[24] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _848_ (
    .CLK(HCLK),
    .D(_076_),
    .Q(\shifter[25] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _849_ (
    .CLK(HCLK),
    .D(_077_),
    .Q(\shifter[26] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _850_ (
    .CLK(HCLK),
    .D(_078_),
    .Q(\shifter[27] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _851_ (
    .CLK(HCLK),
    .D(_079_),
    .Q(\shifter[28] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _852_ (
    .CLK(HCLK),
    .D(_080_),
    .Q(\shifter[29] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _853_ (
    .CLK(HCLK),
    .D(_081_),
    .Q(\shifter[30] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__dfrtp_1 _854_ (
    .CLK(HCLK),
    .D(_082_),
    .Q(\shifter[31] ),
    .RESET_B(HRESETn)
  );
  sky130_fd_sc_hd__conb_1 _855_ (
    .HI(HSIZE[1])
  );
  sky130_fd_sc_hd__conb_1 _856_ (
    .LO(HSIZE[0])
  );
  sky130_fd_sc_hd__conb_1 _857_ (
    .LO(HSIZE[2])
  );
  sky130_fd_sc_hd__conb_1 _858_ (
    .LO(HTRANS[0])
  );
  RX Rec (
    .BRCK(BRCK),
    .BWCK(BWCK),
    .DATA(HWDATA),
    .HCLK(HCLK),
    .HRESETn(HRESETn),
    .SCK(SCK),
    .SDI(SDI)
  );
endmodule
