/* Generated by Yosys 0.13 (git sha1 UNKNOWN, clang 13.0.0 -fPIC -Os) */

module CSADD(clk, rst, x, y, sum);
  wire _0_;
  wire _1_;
  wire _2_;
  input clk;
  wire hsum2;
  input rst;
  wire sc;
  output sum;
  input x;
  input y;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(rst),
    .Y(_1_)
  );
  sky130_fd_sc_hd__xor3_1 _4_ (
    .A(sc),
    .B(y),
    .C(x),
    .X(hsum2)
  );
  sky130_fd_sc_hd__maj3_1 _5_ (
    .A(sc),
    .B(y),
    .C(x),
    .X(_0_)
  );
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(rst),
    .Y(_2_)
  );
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(clk),
    .D(hsum2),
    .Q(sum),
    .RESET_B(_1_)
  );
  sky130_fd_sc_hd__dfrtp_1 _8_ (
    .CLK(clk),
    .D(_0_),
    .Q(sc),
    .RESET_B(_2_)
  );
endmodule

module TCMP(clk, rst, a, s);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  input clk;
  input rst;
  output s;
  wire z;
  sky130_fd_sc_hd__clkinv_1 _4_ (
    .A(rst),
    .Y(_2_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _5_ (
    .A(z),
    .SLEEP(a),
    .X(_1_)
  );
  sky130_fd_sc_hd__xor2_1 _6_ (
    .A(z),
    .B(a),
    .X(_0_)
  );
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(rst),
    .Y(_3_)
  );
  sky130_fd_sc_hd__dfrtp_1 _8_ (
    .CLK(clk),
    .D(_0_),
    .Q(s),
    .RESET_B(_2_)
  );
  sky130_fd_sc_hd__dfrtp_1 _9_ (
    .CLK(clk),
    .D(_1_),
    .Q(z),
    .RESET_B(_3_)
  );
endmodule

module spm(clk, rst, x, y, p);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input clk;
  output p;
  wire \pp[10] ;
  wire \pp[11] ;
  wire \pp[12] ;
  wire \pp[13] ;
  wire \pp[14] ;
  wire \pp[15] ;
  wire \pp[16] ;
  wire \pp[17] ;
  wire \pp[18] ;
  wire \pp[19] ;
  wire \pp[1] ;
  wire \pp[20] ;
  wire \pp[21] ;
  wire \pp[22] ;
  wire \pp[23] ;
  wire \pp[24] ;
  wire \pp[25] ;
  wire \pp[26] ;
  wire \pp[27] ;
  wire \pp[28] ;
  wire \pp[29] ;
  wire \pp[2] ;
  wire \pp[30] ;
  wire \pp[31] ;
  wire \pp[3] ;
  wire \pp[4] ;
  wire \pp[5] ;
  wire \pp[6] ;
  wire \pp[7] ;
  wire \pp[8] ;
  wire \pp[9] ;
  input rst;
  input [31:0] x;
  input y;
  sky130_fd_sc_hd__and2_0 _32_ (
    .A(y),
    .B(x[0]),
    .X(_00_)
  );
  sky130_fd_sc_hd__and2_0 _33_ (
    .A(y),
    .B(x[31]),
    .X(_31_)
  );
  sky130_fd_sc_hd__and2_0 _34_ (
    .A(y),
    .B(x[1]),
    .X(_24_)
  );
  sky130_fd_sc_hd__and2_0 _35_ (
    .A(y),
    .B(x[2]),
    .X(_25_)
  );
  sky130_fd_sc_hd__and2_0 _36_ (
    .A(y),
    .B(x[3]),
    .X(_26_)
  );
  sky130_fd_sc_hd__and2_0 _37_ (
    .A(y),
    .B(x[4]),
    .X(_27_)
  );
  sky130_fd_sc_hd__and2_0 _38_ (
    .A(y),
    .B(x[5]),
    .X(_28_)
  );
  sky130_fd_sc_hd__and2_0 _39_ (
    .A(y),
    .B(x[6]),
    .X(_29_)
  );
  sky130_fd_sc_hd__and2_0 _40_ (
    .A(y),
    .B(x[7]),
    .X(_30_)
  );
  sky130_fd_sc_hd__and2_0 _41_ (
    .A(y),
    .B(x[8]),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2_0 _42_ (
    .A(y),
    .B(x[9]),
    .X(_02_)
  );
  sky130_fd_sc_hd__and2_0 _43_ (
    .A(y),
    .B(x[10]),
    .X(_03_)
  );
  sky130_fd_sc_hd__and2_0 _44_ (
    .A(y),
    .B(x[11]),
    .X(_04_)
  );
  sky130_fd_sc_hd__and2_0 _45_ (
    .A(y),
    .B(x[12]),
    .X(_05_)
  );
  sky130_fd_sc_hd__and2_0 _46_ (
    .A(y),
    .B(x[13]),
    .X(_06_)
  );
  sky130_fd_sc_hd__and2_0 _47_ (
    .A(y),
    .B(x[14]),
    .X(_07_)
  );
  sky130_fd_sc_hd__and2_0 _48_ (
    .A(y),
    .B(x[15]),
    .X(_08_)
  );
  sky130_fd_sc_hd__and2_0 _49_ (
    .A(y),
    .B(x[16]),
    .X(_09_)
  );
  sky130_fd_sc_hd__and2_0 _50_ (
    .A(y),
    .B(x[17]),
    .X(_10_)
  );
  sky130_fd_sc_hd__and2_0 _51_ (
    .A(y),
    .B(x[18]),
    .X(_11_)
  );
  sky130_fd_sc_hd__and2_0 _52_ (
    .A(y),
    .B(x[19]),
    .X(_12_)
  );
  sky130_fd_sc_hd__and2_0 _53_ (
    .A(y),
    .B(x[20]),
    .X(_13_)
  );
  sky130_fd_sc_hd__and2_0 _54_ (
    .A(y),
    .B(x[21]),
    .X(_14_)
  );
  sky130_fd_sc_hd__and2_0 _55_ (
    .A(y),
    .B(x[22]),
    .X(_15_)
  );
  sky130_fd_sc_hd__and2_0 _56_ (
    .A(y),
    .B(x[23]),
    .X(_16_)
  );
  sky130_fd_sc_hd__and2_0 _57_ (
    .A(y),
    .B(x[24]),
    .X(_17_)
  );
  sky130_fd_sc_hd__and2_0 _58_ (
    .A(y),
    .B(x[25]),
    .X(_18_)
  );
  sky130_fd_sc_hd__and2_0 _59_ (
    .A(y),
    .B(x[26]),
    .X(_19_)
  );
  sky130_fd_sc_hd__and2_0 _60_ (
    .A(y),
    .B(x[27]),
    .X(_20_)
  );
  sky130_fd_sc_hd__and2_0 _61_ (
    .A(y),
    .B(x[28]),
    .X(_21_)
  );
  sky130_fd_sc_hd__and2_0 _62_ (
    .A(y),
    .B(x[29]),
    .X(_22_)
  );
  sky130_fd_sc_hd__and2_0 _63_ (
    .A(y),
    .B(x[30]),
    .X(_23_)
  );
  CSADD csa0 (
    .clk(clk),
    .rst(rst),
    .sum(p),
    .x(_00_),
    .y(\pp[1] )
  );
  CSADD \genblk1[10].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[10] ),
    .x(_03_),
    .y(\pp[11] )
  );
  CSADD \genblk1[11].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[11] ),
    .x(_04_),
    .y(\pp[12] )
  );
  CSADD \genblk1[12].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[12] ),
    .x(_05_),
    .y(\pp[13] )
  );
  CSADD \genblk1[13].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[13] ),
    .x(_06_),
    .y(\pp[14] )
  );
  CSADD \genblk1[14].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[14] ),
    .x(_07_),
    .y(\pp[15] )
  );
  CSADD \genblk1[15].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[15] ),
    .x(_08_),
    .y(\pp[16] )
  );
  CSADD \genblk1[16].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[16] ),
    .x(_09_),
    .y(\pp[17] )
  );
  CSADD \genblk1[17].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[17] ),
    .x(_10_),
    .y(\pp[18] )
  );
  CSADD \genblk1[18].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[18] ),
    .x(_11_),
    .y(\pp[19] )
  );
  CSADD \genblk1[19].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[19] ),
    .x(_12_),
    .y(\pp[20] )
  );
  CSADD \genblk1[1].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[1] ),
    .x(_24_),
    .y(\pp[2] )
  );
  CSADD \genblk1[20].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[20] ),
    .x(_13_),
    .y(\pp[21] )
  );
  CSADD \genblk1[21].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[21] ),
    .x(_14_),
    .y(\pp[22] )
  );
  CSADD \genblk1[22].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[22] ),
    .x(_15_),
    .y(\pp[23] )
  );
  CSADD \genblk1[23].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[23] ),
    .x(_16_),
    .y(\pp[24] )
  );
  CSADD \genblk1[24].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[24] ),
    .x(_17_),
    .y(\pp[25] )
  );
  CSADD \genblk1[25].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[25] ),
    .x(_18_),
    .y(\pp[26] )
  );
  CSADD \genblk1[26].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[26] ),
    .x(_19_),
    .y(\pp[27] )
  );
  CSADD \genblk1[27].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[27] ),
    .x(_20_),
    .y(\pp[28] )
  );
  CSADD \genblk1[28].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[28] ),
    .x(_21_),
    .y(\pp[29] )
  );
  CSADD \genblk1[29].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[29] ),
    .x(_22_),
    .y(\pp[30] )
  );
  CSADD \genblk1[2].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[2] ),
    .x(_25_),
    .y(\pp[3] )
  );
  CSADD \genblk1[30].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[30] ),
    .x(_23_),
    .y(\pp[31] )
  );
  CSADD \genblk1[3].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[3] ),
    .x(_26_),
    .y(\pp[4] )
  );
  CSADD \genblk1[4].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[4] ),
    .x(_27_),
    .y(\pp[5] )
  );
  CSADD \genblk1[5].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[5] ),
    .x(_28_),
    .y(\pp[6] )
  );
  CSADD \genblk1[6].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[6] ),
    .x(_29_),
    .y(\pp[7] )
  );
  CSADD \genblk1[7].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[7] ),
    .x(_30_),
    .y(\pp[8] )
  );
  CSADD \genblk1[8].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[8] ),
    .x(_01_),
    .y(\pp[9] )
  );
  CSADD \genblk1[9].csa  (
    .clk(clk),
    .rst(rst),
    .sum(\pp[9] ),
    .x(_02_),
    .y(\pp[10] )
  );
  TCMP tcmp (
    .a(_31_),
    .clk(clk),
    .rst(rst),
    .s(\pp[31] )
  );
endmodule
